//! **EF-9.0 -- what "refines sooner" buys. Measurement only; no output change.**
//!
//! `ELEVATION_FIELD_ARCHITECTURE_RESEARCH.md` §8.3, milestone EF-9.0. This file
//! builds no refinement and changes no generated byte. It answers one question
//! with a number: would an importance-driven tile order (river corridors,
//! steep ground, settlements first) capture materially more of what
//! refinement adds than today's centre-distance order -- the gate that decides
//! whether EF-9.1 onward is worth building at all.
//!
//! ```text
//! cargo test --release -p cartalith-civ --test ef9_refinement_gain -- --ignored --nocapture
//! EF9_SEEDS=483920 EF9_GRIDS=512x384 EF9_WINDOW=8 EF9_K=2 ...   # a cheaper run
//! ```
//!
//! # Why a test file and not the doc's `examples/ef9_refinement_gain.rs`
//!
//! The plan names an example. `cargo test` does not run `#[test]`s inside an
//! example, and EF-9.0 needs a committed regression test of the pure scoring
//! functions beside the (ignored) measurement. An integration test holds both,
//! in the crate the plan chose (`cartalith-civ`: the lowest that builds
//! settlements and ways and still reaches `cartalith-engine`).
//!
//! # Where this follows the plan, and where it states a deviation
//!
//! * **Tiles.** The plan says "every tile" at every level up to `z_base + 6`.
//!   Level 10 alone is 4^10 = 1 048 576 tiles of 256^2 texels, so deep levels
//!   are measured as `K x K` **windows** of `W x W` contiguous tiles (defaults
//!   3x3 windows of 16x16 tiles, `W` capped at the level's own width, so
//!   levels with `2^z <= W` are measured **whole**). A window is also the
//!   unit `_nearest_tiles` actually orders -- the tiles one viewport wants --
//!   so (a) is scored on the question it answers today. Deviation, disclosed
//!   in the report.
//! * **Levels** run `z_base ..= z_base + 6` = 4..=10 at the shipped 256 px tile.
//!   The plan's "LOD entry level" is not a constant anywhere; `z_base` is the
//!   first level whose octave schedule is non-zero-capable, so it is the
//!   lowest level where "refinement adds nothing yet" can be observed
//!   directly (G_pt must be 0 there). Labelled judgement.
//! * **River gain** (`tile_rivers`, "not drawn") is NOT measured here: it
//!   needs a `carve_rivers = false` world (§5 EF-1: the carved world's `field`
//!   and `flow_discharge` are not self-consistent) and a `TilePlacement` per
//!   tile. It is reported as not run, never as 0.
//! * **Gain scalar.** The plan names the four gains but not the per-tile
//!   scalar the capture curve sums; this uses each gain's **RMS** (G_pt also
//!   keeps its max). Labelled judgement.
//!
//! Must never: edit generation or simulation code, or be read as a speed
//! (timings are explicitly outside EF-9.0).

use std::collections::BTreeMap;

use cartalith_engine::bake::{pyramid_tile, PyramidTile};
use cartalith_engine::elevation::{curvature_energy, world_amplify_opts, world_elevation_tile};
use cartalith_spatial::pyramid::{pyramid_tile_bounds, ChunkId};
use cartalith_spatial::FloatRegion;
use cartalith_terrain::amplify::{sample_elevation, z_base_for_tile_size, AmplifyOpts};
use cartalith_terrain::analysis;
use rayon::prelude::*;

/// Shipped tile size in texels: `cartalith_godot::lod_bridge::TILE_PX` (256).
/// Restated because `cartalith-godot` is not a dependency of this crate; the
/// measurement test asserts [`z_base_for_tile_size`] of it is 4, the value
/// every EF test pins.
const TILE_PX: usize = 256;
/// Octaves stop growing at `z_base + 6` (`world_amplify_opts` /
/// `lod_bridge::MAX_LEVEL = 10` at `z_base = 4`): the plan's "recorded knee".
const KNEE_OCTAVES: i32 = 6;
/// Default window edge in tiles. Judgement: 16x16 = 256 tiles is the order of
/// one desktop viewport's tile count at a deep level (`MAX_LOD_TILES_PER_UPDATE`
/// is the same order); not a measurement.
const DEFAULT_WINDOW: u32 = 16;
/// Default windows per axis per level. Judgement: 3x3 spreads windows over
/// land and sea; sea-only windows are counted and skipped, never scored 0.
const DEFAULT_K: u32 = 3;
/// The plan's three budgets, as integer percent of a window's tiles.
const BUDGETS: [u32; 3] = [10, 25, 50];
/// Q3's default gate (§8.5): GO if the oracle captures at least this multiple
/// of today's order at the 25 % budget, median across worlds.
const GATE_RATIO: f64 = 1.5;
/// Landmark fine scale in km: `landmark.rs::SCALE_FINE_KM` (3.0), the radius
/// the plan names for the `|tpi|` input. Restated (private there).
const TPI_FINE_KM: f64 = 3.0;
/// `landmark.rs::SCALE_MIN_CELLS` / `SCALE_MAX_CELLS`: the clamp it applies.
const TPI_MIN_CELLS: i64 = 2;
const TPI_MAX_CELLS: i64 = 40;
/// Bin edge in cells for the way-segment index. Judgement (speed only; the
/// result is exact, the bins only prune).
const WAY_BIN: usize = 16;

// ---------------------------------------------------------------- pure maths

/// Average (tie-shared) 1-based ranks of `v`; the standard tie treatment for
/// Spearman. Non-finite values must be removed by the caller.
fn average_ranks(v: &[f64]) -> Vec<f64> {
    let mut idx: Vec<usize> = (0..v.len()).collect();
    idx.sort_by(|&a, &b| v[a].partial_cmp(&v[b]).expect("finite input"));
    let mut r = vec![0.0; v.len()];
    let mut i = 0;
    while i < idx.len() {
        let mut j = i;
        while j + 1 < idx.len() && v[idx[j + 1]] == v[idx[i]] {
            j += 1;
        }
        let rank = (i + j) as f64 / 2.0 + 1.0;
        for &k in &idx[i..=j] {
            r[k] = rank;
        }
        i = j + 1;
    }
    r
}

/// Spearman rank correlation of two series, over the pairs where **both** are
/// finite (an absent input is `NaN` and is excluded, never ranked as 0).
/// `None` when fewer than 3 pairs remain or either side is constant.
fn spearman(a: &[f64], b: &[f64]) -> Option<f64> {
    assert_eq!(a.len(), b.len(), "spearman needs paired series");
    let (mut x, mut y) = (Vec::new(), Vec::new());
    for (&p, &q) in a.iter().zip(b) {
        if p.is_finite() && q.is_finite() {
            x.push(p);
            y.push(q);
        }
    }
    if x.len() < 3 {
        return None;
    }
    let (rx, ry) = (average_ranks(&x), average_ranks(&y));
    let n = rx.len() as f64;
    let (mx, my) = (rx.iter().sum::<f64>() / n, ry.iter().sum::<f64>() / n);
    let (mut cov, mut vx, mut vy) = (0.0, 0.0, 0.0);
    for (p, q) in rx.iter().zip(&ry) {
        cov += (p - mx) * (q - my);
        vx += (p - mx) * (p - mx);
        vy += (q - my) * (q - my);
    }
    if vx <= 0.0 || vy <= 0.0 {
        return None;
    }
    Some(cov / (vx * vy).sqrt())
}

/// SplitMix64 finaliser: the tie-break hash, so tied scores are ordered
/// without favouring low indices (which would be a spatial bias).
fn mix(mut z: u64) -> u64 {
    z = z.wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Indices ordered by score **descending**; a non-finite (absent) score sorts
/// last; ties are broken by [`mix`] of `(index, salt)` so a tie never acts as
/// a free spatial ordering.
fn order_desc(scores: &[f64], salt: u64) -> Vec<usize> {
    let mut idx: Vec<usize> = (0..scores.len()).collect();
    idx.sort_by(|&a, &b| {
        let (sa, sb) = (scores[a], scores[b]);
        match (sa.is_finite(), sb.is_finite()) {
            (true, true) => sb.partial_cmp(&sa).unwrap().then(mix(a as u64 ^ salt).cmp(&mix(b as u64 ^ salt))),
            (true, false) => std::cmp::Ordering::Less,
            (false, true) => std::cmp::Ordering::Greater,
            (false, false) => mix(a as u64 ^ salt).cmp(&mix(b as u64 ^ salt)),
        }
    });
    idx
}

/// Today's order, reproduced from `viewport_host.gd::_nearest_tiles` at a
/// single level (`group` is constant, `f == 1`): ascending squared distance
/// from the tile **index** `(col, row)` to the view centre `centre`
/// (`((c0 + c1) * 0.5, (r0 + r1) * 0.5)`), ties by position in the input.
fn centre_distance_order(tiles: &[(u32, u32)], centre: (f64, f64)) -> Vec<usize> {
    let d = |i: usize| {
        let (dx, dy) = (tiles[i].0 as f64 - centre.0, tiles[i].1 as f64 - centre.1);
        dx * dx + dy * dy
    };
    let mut idx: Vec<usize> = (0..tiles.len()).collect();
    idx.sort_by(|&a, &b| d(a).partial_cmp(&d(b)).unwrap().then(a.cmp(&b)));
    idx
}

/// Number of tiles a `pct` % budget refines out of `n`: `ceil(n * pct / 100)`
/// in integer arithmetic (a budget never rounds to zero tiles).
fn budget_count(n: usize, pct: u32) -> usize {
    (n * pct as usize).div_ceil(100)
}

/// Share of the summed `gain` captured by the first `budget_count` tiles of
/// `order`. `None` when the total gain is not positive (nothing to capture:
/// a sea window), never 0 or 1.
fn capture_share(gain: &[f64], order: &[usize], pct: u32) -> Option<f64> {
    let total: f64 = gain.iter().sum();
    if !(total > 0.0) {
        return None;
    }
    let k = budget_count(gain.len(), pct);
    Some(order.iter().take(k).map(|&i| gain[i]).sum::<f64>() / total)
}

/// Smallest fraction of tiles (in `order`) whose gain reaches `target` of the
/// total: the "how much of the level must be refined" number. `None` as above.
fn fraction_for_share(gain: &[f64], order: &[usize], target: f64) -> Option<f64> {
    let total: f64 = gain.iter().sum();
    if !(total > 0.0) {
        return None;
    }
    let mut acc = 0.0;
    for (n, &i) in order.iter().enumerate() {
        acc += gain[i];
        if acc >= target * total {
            return Some((n + 1) as f64 / gain.len() as f64);
        }
    }
    Some(1.0)
}

/// Linear-interpolated quantile `q` in `[0,1]` of `v` (any order); `None` for
/// an empty slice. Used for medians and distribution summaries.
fn quantile(v: &[f64], q: f64) -> Option<f64> {
    let mut s: Vec<f64> = v.iter().copied().filter(|x| x.is_finite()).collect();
    if s.is_empty() {
        return None;
    }
    s.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let pos = q.clamp(0.0, 1.0) * (s.len() - 1) as f64;
    let (lo, hi) = (pos.floor() as usize, pos.ceil() as usize);
    Some(s[lo] + (s[hi] - s[lo]) * (pos - lo as f64))
}

/// Median of the `Some` values; `None` if there are none.
fn median_opt(v: &[Option<f64>]) -> Option<f64> {
    let x: Vec<f64> = v.iter().flatten().copied().collect();
    quantile(&x, 0.5)
}

/// Bilinear sample of a `w x h` row-major raster at continuous `(u, v)` in
/// texel units, clamped at the edges.
fn bilinear_clamped(d: &[f32], w: usize, h: usize, u: f64, v: f64) -> f32 {
    let u = u.clamp(0.0, (w - 1) as f64);
    let v = v.clamp(0.0, (h - 1) as f64);
    let (x0, y0) = (u.floor() as usize, v.floor() as usize);
    let (x1, y1) = ((x0 + 1).min(w - 1), (y0 + 1).min(h - 1));
    let (fx, fy) = (u - x0 as f64, v - y0 as f64);
    let a = d[y0 * w + x0] as f64 * (1.0 - fx) + d[y0 * w + x1] as f64 * fx;
    let b = d[y1 * w + x0] as f64 * (1.0 - fx) + d[y1 * w + x1] as f64 * fx;
    (a * (1.0 - fy) + b * fy) as f32
}

/// The parent tile's texels bilinearly resampled onto the child's grid: what
/// the screen shows if the child is **not** refined (G_scr's baseline).
///
/// A child covers one quadrant of its parent's bounds, and a tile's texel `i`
/// sits at fraction `i / (w - 1)` of its bounds (`pyramid_tile_bounds`; the
/// EF-0 tests pin it), so child texel `ox` lands at parent texel
/// `(col & 1) * (w - 1) / 2 + ox / 2`, and likewise for rows.
fn resample_parent(parent: &[f32], w: usize, h: usize, col: u32, row: u32) -> Vec<f32> {
    let (qx, qy) = ((col & 1) as f64, (row & 1) as f64);
    let mut out = Vec::with_capacity(w * h);
    for oy in 0..h {
        let v = qy * (h - 1) as f64 / 2.0 + oy as f64 / 2.0;
        for ox in 0..w {
            let u = qx * (w - 1) as f64 / 2.0 + ox as f64 / 2.0;
            out.push(bilinear_clamped(parent, w, h, u, v));
        }
    }
    out
}

/// RMS over the interior texels of `|grad(a) - grad(b)|` (central
/// differences, field units per texel): G_grad's core. `0` for identical
/// rasters; needs `w, h >= 3`.
fn gradient_rms_diff(a: &[f32], b: &[f32], w: usize, h: usize) -> f64 {
    assert!(w >= 3 && h >= 3 && a.len() >= w * h && b.len() >= w * h);
    let mut acc = 0.0;
    let mut n = 0usize;
    for y in 1..h - 1 {
        for x in 1..w - 1 {
            let g = |d: &[f32]| {
                (
                    (d[y * w + x + 1] as f64 - d[y * w + x - 1] as f64) * 0.5,
                    (d[(y + 1) * w + x] as f64 - d[(y - 1) * w + x] as f64) * 0.5,
                )
            };
            let (ga, gb) = (g(a), g(b));
            acc += (ga.0 - gb.0).powi(2) + (ga.1 - gb.1).powi(2);
            n += 1;
        }
    }
    (acc / n as f64).sqrt()
}

/// Root-mean-square of `a - b`. `0` for identical rasters.
fn rms_diff(a: &[f32], b: &[f32]) -> f64 {
    let s: f64 = a.iter().zip(b).map(|(&p, &q)| (p as f64 - q as f64).powi(2)).sum();
    (s / a.len() as f64).sqrt()
}

/// Inclusive coarse-cell footprint `(x0, x1, y0, y1)` of a tile's bounds.
/// Cell `i` is the lattice square `[i, i + 1]` of the coarse sample space, so
/// the footprint is `floor(b.x) ..= ceil(b.x + b.w) - 1`, never empty (a tile
/// narrower than a cell still sees the cell it sits in) and clamped to the
/// grid. Judgement: the plan says "aggregated over the footprint" without
/// fixing the cell convention.
fn footprint_cells(b: &FloatRegion, gw: usize, gh: usize) -> (usize, usize, usize, usize) {
    let axis = |lo: f64, len: f64, n: usize| {
        let a = (lo.floor().max(0.0) as usize).min(n - 1);
        let hi = ((lo + len).ceil() as i64 - 1).max(a as i64) as usize;
        (a, hi.min(n - 1))
    };
    let (x0, x1) = axis(b.x, b.w, gw);
    let (y0, y1) = axis(b.y, b.h, gh);
    (x0, x1, y0, y1)
}

/// Length of segment `p -> q` inside the axis-aligned box
/// `[x0, x1] x [y0, y1]` (Liang-Barsky); `0` when outside or degenerate.
fn clipped_length(p: (f64, f64), q: (f64, f64), x0: f64, x1: f64, y0: f64, y1: f64) -> f64 {
    let (dx, dy) = (q.0 - p.0, q.1 - p.1);
    let (mut t0, mut t1) = (0.0f64, 1.0f64);
    for (pp, qq) in [(-dx, p.0 - x0), (dx, x1 - p.0), (-dy, p.1 - y0), (dy, y1 - p.1)] {
        if pp == 0.0 {
            if qq < 0.0 {
                return 0.0;
            }
        } else {
            let r = qq / pp;
            if pp < 0.0 {
                if r > t1 {
                    return 0.0;
                }
                t0 = t0.max(r);
            } else {
                if r < t0 {
                    return 0.0;
                }
                t1 = t1.min(r);
            }
        }
    }
    if t1 <= t0 {
        return 0.0;
    }
    (t1 - t0) * dx.hypot(dy)
}

// ---------------------------------------------------------------- tile gains

/// The four gains of one tile (EF-9.0 §8.3). Every field is a measurement over
/// the tile's own texels.
#[derive(Clone, Copy, Debug)]
struct Gains {
    /// RMS over texels of `|sample(z) - sample(z - 1)|`: the top octave alone.
    g_pt_rms: f64,
    /// Max of the same.
    g_pt_max: f64,
    /// RMS of `tile - bilinear(parent)`: what is on screen if not refined.
    g_scr: f64,
    /// RMS gradient difference behind `g_scr`.
    g_grad: f64,
    /// `curvature_energy(tile) / curvature_energy(parent upsample)`; `None`
    /// when the denominator is 0 (a flat parent has no defined ratio).
    g_curv: Option<f64>,
}

/// Measures one tile: synthesises it through `pyramid_tile` (the very call
/// `world_elevation_tile` makes), its parent likewise, and the `z - 1` point
/// samples at the tile's own texel coordinates.
///
/// Must never be given `id.z == 0` (no parent) -- levels start at `z_base`.
fn tile_gain(coarse: &[f32], gw: usize, gh: usize, opts: &AmplifyOpts, tile_px: usize, id: ChunkId) -> Gains {
    assert!(id.z >= 1, "a root tile has no parent to compare against");
    let tile = pyramid_tile(coarse, gw, gh, id, tile_px, opts);
    let pid = ChunkId { z: id.z - 1, col: id.col >> 1, row: id.row >> 1 };
    let parent: PyramidTile = pyramid_tile(coarse, gw, gh, pid, tile_px, opts);
    let (w, h) = (tile.w, tile.h);
    let base = resample_parent(&parent.data, w, h, id.col, id.row);
    let g_scr = rms_diff(&tile.data, &base);
    let g_grad = gradient_rms_diff(&tile.data, &base, w, h);
    let (ce_t, ce_b) = (curvature_energy(&tile.data, w, h), curvature_energy(&base, w, h));
    let g_curv = if ce_b > 0.0 { Some(ce_t / ce_b) } else { None };

    let b = pyramid_tile_bounds(gw, gh, id.z as i32, id.col, id.row);
    let (mut acc, mut mx) = (0.0f64, 0.0f64);
    for oy in 0..h {
        for ox in 0..w {
            let cx = b.x + ox as f64 / (w - 1) as f64 * b.w;
            let cy = b.y + oy as f64 / (h - 1) as f64 * b.h;
            let d = (tile.data[oy * w + ox] as f64 - sample_elevation(coarse, gw, gh, cx, cy, id.z as i32 - 1, opts) as f64).abs();
            acc += d * d;
            mx = mx.max(d);
        }
    }
    Gains { g_pt_rms: (acc / (w * h) as f64).sqrt(), g_pt_max: mx, g_scr, g_grad, g_curv }
}

/// Names of the per-tile inputs, in [`Feat`] order. §8.3's list.
const INPUTS: [&str; 10] = [
    "slope_mean",
    "slope_max",
    "abs_curv_mean",
    "abs_tpi_mean",
    "stream_order_max",
    "land_fraction",
    "boundary_fraction",
    "volcanic_max",
    "settlement_count",
    "way_length",
];
/// One tile's inputs; `NaN` = **absent** (the world does not carry the field),
/// never 0.
type Feat = [f64; INPUTS.len()];

/// Per-world coarse rasters and point sets the tile inputs aggregate.
struct WorldInputs {
    gw: usize,
    gh: usize,
    sea: f64,
    field: Vec<f32>,
    slope: Vec<f32>,
    abs_curv: Vec<f32>,
    abs_tpi: Vec<f32>,
    order: Option<Vec<i16>>,
    boundary: Option<Vec<u8>>,
    volcanic: Option<Vec<f32>>,
    settlements: Vec<(usize, usize)>,
    segs: Vec<[f64; 4]>,
    bins: Vec<Vec<u32>>,
    bw: usize,
}

impl WorldInputs {
    /// Builds the coarse rasters once per world. A zero-length `boundary_type`
    /// or `volcanic_field` (a `Loaded` save) maps to `None`, not to zeros
    /// (`MISTAKES.md`: never encode "no value" as a plausible value).
    #[allow(clippy::too_many_arguments)]
    fn build(
        field: &[f32],
        gw: usize,
        gh: usize,
        sea: f64,
        world: bool,
        map_km: f64,
        order: Option<&[i16]>,
        boundary: &[u8],
        volcanic: &[f32],
        settlements: Vec<(usize, usize)>,
        ways: &[Vec<(f64, f64)>],
    ) -> Self {
        let n = gw * gh;
        let cell_km = map_km / gw as f64;
        let r_fine = ((TPI_FINE_KM / cell_km).round() as i64).clamp(TPI_MIN_CELLS, TPI_MAX_CELLS);
        let abs = |v: Vec<f32>| v.into_iter().map(f32::abs).collect::<Vec<_>>();
        let bw = gw.div_ceil(WAY_BIN);
        let bh = gh.div_ceil(WAY_BIN);
        let mut segs = Vec::new();
        let mut bins: Vec<Vec<u32>> = vec![Vec::new(); bw * bh];
        for pts in ways {
            for s in pts.windows(2) {
                let id = segs.len() as u32;
                segs.push([s[0].0, s[0].1, s[1].0, s[1].1]);
                let (lx, hx) = (s[0].0.min(s[1].0).max(0.0), s[0].0.max(s[1].0).max(0.0));
                let (ly, hy) = (s[0].1.min(s[1].1).max(0.0), s[0].1.max(s[1].1).max(0.0));
                for by in (ly as usize / WAY_BIN).min(bh - 1)..=(hy as usize / WAY_BIN).min(bh - 1) {
                    for bx in (lx as usize / WAY_BIN).min(bw - 1)..=(hx as usize / WAY_BIN).min(bw - 1) {
                        bins[by * bw + bx].push(id);
                    }
                }
            }
        }
        WorldInputs {
            gw,
            gh,
            sea,
            field: field.to_vec(),
            slope: analysis::slope(field, gw, gh),
            abs_curv: abs(analysis::curvature_at(field, gw, gh, 2, world)),
            abs_tpi: abs(analysis::tpi(field, gw, gh, r_fine, world)),
            order: order.filter(|o| o.len() == n).map(|o| o.to_vec()),
            boundary: (boundary.len() == n).then(|| boundary.to_vec()),
            volcanic: (volcanic.len() == n).then(|| volcanic.to_vec()),
            settlements,
            segs,
            bins,
            bw,
        }
    }

    /// The tile's inputs over its coarse-cell footprint ([`footprint_cells`]).
    fn features(&self, b: &FloatRegion) -> Feat {
        let (x0, x1, y0, y1) = footprint_cells(b, self.gw, self.gh);
        let (mut sum_s, mut max_s, mut sum_c, mut sum_t) = (0.0f64, 0.0f64, 0.0f64, 0.0f64);
        let (mut land, mut bnd, mut max_o, mut max_v) = (0usize, 0usize, i16::MIN, f32::MIN);
        let mut cnt = 0usize;
        for y in y0..=y1 {
            for x in x0..=x1 {
                let i = y * self.gw + x;
                cnt += 1;
                sum_s += self.slope[i] as f64;
                max_s = max_s.max(self.slope[i] as f64);
                sum_c += self.abs_curv[i] as f64;
                sum_t += self.abs_tpi[i] as f64;
                land += (self.field[i] as f64 > self.sea) as usize;
                if let Some(bt) = &self.boundary {
                    bnd += (bt[i] != 0) as usize;
                }
                if let Some(o) = &self.order {
                    max_o = max_o.max(o[i]);
                }
                if let Some(v) = &self.volcanic {
                    max_v = max_v.max(v[i]);
                }
            }
        }
        let c = cnt as f64;
        let settle = self.settlements.iter().filter(|&&(sx, sy)| sx >= x0 && sx <= x1 && sy >= y0 && sy <= y1).count();
        let way = self.way_length(x0 as f64, (x1 + 1) as f64, y0 as f64, (y1 + 1) as f64);
        [
            sum_s / c,
            max_s,
            sum_c / c,
            sum_t / c,
            if self.order.is_some() { max_o as f64 } else { f64::NAN },
            land as f64 / c,
            if self.boundary.is_some() { bnd as f64 / c } else { f64::NAN },
            if self.volcanic.is_some() { max_v as f64 } else { f64::NAN },
            settle as f64,
            way,
        ]
    }

    /// Total length (cell units) of way segments inside the box, via the bins.
    fn way_length(&self, x0: f64, x1: f64, y0: f64, y1: f64) -> f64 {
        let bh = self.bins.len() / self.bw;
        let mut ids: Vec<u32> = Vec::new();
        for by in (y0 as usize / WAY_BIN).min(bh - 1)..=((y1 as usize) / WAY_BIN).min(bh - 1) {
            for bx in (x0 as usize / WAY_BIN).min(self.bw - 1)..=((x1 as usize) / WAY_BIN).min(self.bw - 1) {
                ids.extend_from_slice(&self.bins[by * self.bw + bx]);
            }
        }
        ids.sort_unstable();
        ids.dedup();
        ids.iter()
            .map(|&i| {
                let s = self.segs[i as usize];
                clipped_length((s[0], s[1]), (s[2], s[3]), x0, x1, y0, y1)
            })
            .sum()
    }
}

/// One measured tile.
struct Row {
    col: u32,
    row: u32,
    gains: Gains,
    feat: Feat,
}

/// Window origins `(col0, row0)` for level `z`: a `k x k` lattice of
/// `w x w`-tile windows spread over the level, origins snapped to even
/// indices (so every window holds whole sibling groups), `w` capped at the
/// level width. A level no wider than `w` yields its one whole-level window.
fn window_origins(z: u32, w: u32, k: u32) -> (u32, Vec<(u32, u32)>) {
    let n = 1u32 << z;
    let w = w.min(n);
    if w == n {
        return (w, vec![(0, 0)]);
    }
    let span = n - w;
    let mut out = Vec::new();
    for j in 0..k {
        for i in 0..k {
            let at = |t: u32| ((span as f64 * (t as f64 + 0.5) / k as f64) as u32) & !1;
            out.push((at(i), at(j)));
        }
    }
    out.dedup();
    (w, out)
}

/// Measures every tile of one window (rayon over tiles).
fn measure_window(coarse: &[f32], inp: &WorldInputs, opts: &AmplifyOpts, tile_px: usize, z: u32, org: (u32, u32), w: u32) -> Vec<Row> {
    let ids: Vec<(u32, u32)> = (0..w).flat_map(|r| (0..w).map(move |c| (org.0 + c, org.1 + r))).collect();
    ids.par_iter()
        .map(|&(col, row)| {
            let id = ChunkId { z, col, row };
            let gains = tile_gain(coarse, inp.gw, inp.gh, opts, tile_px, id);
            let feat = inp.features(&pyramid_tile_bounds(inp.gw, inp.gh, z as i32, col, row));
            Row { col, row, gains, feat }
        })
        .collect()
}

// ------------------------------------------------------------- aggregation

/// Capture curves of one window at [`BUDGETS`].
struct Capture {
    /// (a) today's order.
    a: [Option<f64>; 3],
    /// (b) the oracle, sorted by measured G_scr.
    b: [Option<f64>; 3],
    /// (c) each input alone, descending (absent last).
    c: Vec<[Option<f64>; 3]>,
    /// Smallest fraction of the window's tiles reaching 80 % of G_scr under
    /// (b) and under (a).
    need80_b: Option<f64>,
    need80_a: Option<f64>,
}

/// Scores one window's rows under every order. `salt` seeds the tie-break.
fn capture_window(rows: &[Row], w: u32, org: (u32, u32), salt: u64) -> Capture {
    let gain: Vec<f64> = rows.iter().map(|r| r.gains.g_scr).collect();
    let tiles: Vec<(u32, u32)> = rows.iter().map(|r| (r.col, r.row)).collect();
    let centre = (org.0 as f64 + (w - 1) as f64 / 2.0, org.1 as f64 + (w - 1) as f64 / 2.0);
    let order_a = centre_distance_order(&tiles, centre);
    let order_b = order_desc(&gain, salt);
    let cap = |o: &[usize]| BUDGETS.map(|p| capture_share(&gain, o, p));
    let c = (0..INPUTS.len())
        .map(|k| {
            let s: Vec<f64> = rows.iter().map(|r| r.feat[k]).collect();
            if s.iter().all(|v| !v.is_finite()) {
                [None; 3]
            } else {
                cap(&order_desc(&s, salt ^ (k as u64 + 1)))
            }
        })
        .collect();
    Capture {
        a: cap(&order_a),
        b: cap(&order_b),
        c,
        need80_b: fraction_for_share(&gain, &order_b, 0.8),
        need80_a: fraction_for_share(&gain, &order_a, 0.8),
    }
}

/// Everything recorded for one `(world, level)` cell.
struct Cell {
    n_tiles: usize,
    windows: usize,
    windows_skipped: usize,
    /// Median over the cell's windows, per budget.
    a: [Option<f64>; 3],
    b: [Option<f64>; 3],
    c: Vec<[Option<f64>; 3]>,
    need80_b: Option<f64>,
    need80_a: Option<f64>,
    /// `rho[input][gain]`, gains ordered `[g_pt_rms, g_scr, g_grad, g_curv]`.
    rho: Vec<[Option<f64>; 4]>,
    /// min / median / p90 / max of G_scr and G_pt (rms) over the tiles.
    scr_q: [Option<f64>; 4],
    pt_q: [Option<f64>; 4],
    /// Largest |G_pt max| seen (the control's exact-zero check reads it).
    pt_max: f64,
}

/// Folds one `(world, level)` cell's windows into a [`Cell`].
fn summarise(windows: &[(Vec<Row>, u32, (u32, u32))], salt: u64) -> Cell {
    let caps: Vec<Capture> = windows.iter().map(|(r, w, o)| capture_window(r, *w, *o, salt)).collect();
    let live: Vec<&Capture> = caps.iter().filter(|c| c.b[0].is_some()).collect();
    let med = |f: &dyn Fn(&Capture) -> [Option<f64>; 3]| -> [Option<f64>; 3] {
        let mut o = [None; 3];
        for (k, slot) in o.iter_mut().enumerate() {
            let v: Vec<Option<f64>> = live.iter().map(|c| f(c)[k]).collect();
            *slot = median_opt(&v);
        }
        o
    };
    let all: Vec<&Row> = windows.iter().flat_map(|(r, _, _)| r.iter()).collect();
    let gains: [Vec<f64>; 4] = [
        all.iter().map(|r| r.gains.g_pt_rms).collect(),
        all.iter().map(|r| r.gains.g_scr).collect(),
        all.iter().map(|r| r.gains.g_grad).collect(),
        all.iter().map(|r| r.gains.g_curv.unwrap_or(f64::NAN)).collect(),
    ];
    let rho = (0..INPUTS.len())
        .map(|k| {
            let x: Vec<f64> = all.iter().map(|r| r.feat[k]).collect();
            [0, 1, 2, 3].map(|g| spearman(&x, &gains[g]))
        })
        .collect();
    let q = |v: &[f64]| [quantile(v, 0.0), quantile(v, 0.5), quantile(v, 0.9), quantile(v, 1.0)];
    Cell {
        n_tiles: all.len(),
        windows: windows.len(),
        windows_skipped: windows.len() - live.len(),
        a: med(&|c| c.a),
        b: med(&|c| c.b),
        c: (0..INPUTS.len())
            .map(|k| {
                let mut o = [None; 3];
                for (p, slot) in o.iter_mut().enumerate() {
                    let v: Vec<Option<f64>> = live.iter().map(|c| c.c[k][p]).collect();
                    *slot = median_opt(&v);
                }
                o
            })
            .collect(),
        need80_b: median_opt(&live.iter().map(|c| c.need80_b).collect::<Vec<_>>()),
        need80_a: median_opt(&live.iter().map(|c| c.need80_a).collect::<Vec<_>>()),
        rho,
        scr_q: q(&gains[1]),
        pt_q: q(&gains[0]),
        pt_max: all.iter().map(|r| r.gains.g_pt_max).fold(0.0, f64::max),
    }
}

// ------------------------------------------------------------ the civ chain

/// A generated world plus everything the inputs need. Built by the same call
/// chain as `examples/_memlane_peak.rs` (itself `compute_civilisation`'s
/// default auto-populate path) so settlements and ways are the app's.
struct World {
    ws: cartalith_engine::WorldState,
    p: cartalith_engine::WorldParams,
    settlements: Vec<(usize, usize)>,
    ways: Vec<Vec<(f64, f64)>>,
}

/// Generates one world with the shipped app's parameters (the seven
/// divergence flags `_memlane_peak` documents) and runs the civ chain to
/// settlements and consolidated ways. Must never write any setting or file.
fn build_world(gw: usize, gh: usize, seed: i32) -> World {
    let mut p = cartalith_engine::WorldParams::defaults(gw, gh, seed);
    p.crater.physical_model = true;
    p.volc.exclude_transform = true;
    p.volc.edifice_model = true;
    p.integrate_drainage = true;
    p.tect.narrow_plate_base_blur = true;
    p.passes.glacial = true;
    p.geology_model = true;
    p.map_width_km = 800.0;
    let ws = cartalith_engine::generate_terrain(&p);
    let (world, sea, km) = (p.world, ws.sea_level, p.map_width_km);
    let opts = &p.civ;
    let want = opts.want_counts();
    let wb = cartalith_civ::build_water_bodies(&ws.field, gw, gh, sea, world, Some(&ws.rainfall));
    let biome = cartalith_civ::build_biome_raster(&wb.classification, &ws.temperature, &ws.rainfall);
    let soil_slope = cartalith_civ::build_slope_field(&ws.field, gw, gh, world);
    let lith = cartalith_civ::build_lithology(&ws.field, &ws.age_field, &ws.volcanic_field, &ws.crust_field, &ws.resistance_field, &ws.rainfall, sea);
    let soil = cartalith_civ::build_soil_fertility(&lith, &ws.temperature, &ws.rainfall, &soil_slope, &ws.age_field);
    let thresh_flow = cartalith_hydrology::river_flow_thresh(gw, gh, gw, km);
    let water = cartalith_civ::build_water_access(&ws.flow_discharge, &ws.field, gw, gh, sea, thresh_flow);
    let cap = cartalith_civ::build_carrying_capacity(&soil, &water, Some(&biome), &ws.temperature, &ws.field, sea, 0.0, None);
    let resources = cartalith_civ::build_resource_potentials(
        &lith, Some(&ws.boundary_type), Some(&ws.shear_field), Some(&ws.flow_discharge), Some(&biome), &ws.field, &ws.rainfall, &ws.age_field, gw, gh, sea,
        Some(&ws.volcanic_field), true, false,
    );
    let raw_slope = cartalith_civ::build_raw_slope_field(&ws.field, gw, gh, world);
    let corridors = cartalith_civ::build_route_corridors(&ws.field, &raw_slope, Some(&ws.flow_discharge), gw, gh, sea, world, thresh_flow);
    let landmass = cartalith_civ::build_landmass_quality(&ws.field, Some(&cap), gw, gh, sea, world);
    let coast_reach = cartalith_civ::build_coast_reach(&cartalith_terrain::vector::trace_coastline(&ws.field, gw, gh, sea), &wb.classification, gw, gh);
    let flood = cartalith_civ::build_flood_field(&ws.field, &ws.flow_discharge, &raw_slope, gw, gh, sea);
    let (river_order, river_polys) =
        cartalith_civ::fresh_river_network(&ws.field, &ws.flow_discharge, gw, gh, sea, world, p.river_density, km, ws.integrated_drainage);
    let river_reach = cartalith_civ::build_river_reach(&river_polys, &river_order, gw, gh);
    let ctx = cartalith_civ::SuitabilityCtx {
        water_bodies: Some(&wb.classification),
        corridor: Some(&corridors),
        landmass: Some(&landmass.quality),
        flow: Some(&ws.flow_discharge),
        river_reach: Some(&river_reach),
        coast_reach: Some(&coast_reach),
        resources: Some(&resources),
        rain: Some(&ws.rainfall),
        flood: Some(&flood),
        slope_raw: Some(&raw_slope),
        flow_thresh: thresh_flow,
    };
    let suit = cartalith_civ::build_settlement_suitability(&soil, &water, &cap, &ws.field, &soil_slope, gw, gh, sea, Some(&ctx));
    let (thresh, supp_r) = match want {
        Some(w) => cartalith_civ::civ_want_counts_seed_params(gw, w.iter().sum()),
        None => (opts.seed_thresh, (gw as f64 / opts.seed_suppress_div.max(1.0)).floor().max(6.0)),
    };
    let seeds = cartalith_civ::find_settlement_seeds(&suit, gw, gh, thresh, supp_r);
    let mut placements = cartalith_civ::place_settlements_with_counts(
        &seeds, &suit, &ws.field, &wb.classification, &wb.fill_level, gw, gh, sea, world, opts.factions.max(1), &flood, &ws.flow_discharge, thresh_flow, km, want,
    );
    let passes = if want.is_some() { 1 } else { cartalith_civ::CIV_AUTO_WORLD_PASSES };
    let topology = cartalith_civ::civ_iterative_network(
        &mut placements, passes, gw, gh, sea, &ws.field, &ws.flow_discharge, &river_order, &biome, &wb.classification, world, km,
    );
    let mut rng = cartalith_civ::civ_name_rng();
    let named = cartalith_civ::name_and_populate_settlements_with_rng(&placements, &mut rng, &[]);
    let ways = cartalith_civ::civ_consolidate_and_smooth_ways(&topology, &named, &ws.field, &wb.classification, gw, gh, km);
    World {
        settlements: named.iter().map(|s| (s.placement.x, s.placement.y)).collect(),
        ways: ways.iter().filter(|w| !w.hidden).map(|w| w.pts.clone()).collect(),
        ws,
        p,
    }
}

// ----------------------------------------------------------------- reporting

/// Formats an optional ratio as a 3-decimal number or `n/a`.
fn f3(v: Option<f64>) -> String {
    v.map_or("  n/a".into(), |x| format!("{x:6.3}"))
}

/// `median (min..max)` of the `Some` values.
fn mmm(v: &[Option<f64>]) -> String {
    let x: Vec<f64> = v.iter().flatten().copied().collect();
    match (quantile(&x, 0.5), quantile(&x, 0.0), quantile(&x, 1.0)) {
        (Some(m), Some(lo), Some(hi)) => format!("{m:6.3} ({lo:5.3}..{hi:5.3})"),
        _ => "  n/a".into(),
    }
}

/// Reads a `usize`-ish env override.
fn env_u32(name: &str, default: u32) -> u32 {
    std::env::var(name).ok().and_then(|s| s.parse().ok()).unwrap_or(default)
}

/// **The EF-9.0 measurement.** Ignored: it generates six worlds and synthesises
/// tens of thousands of 256^2 tiles (minutes in release). Prints the tables the
/// plan's §8.4 records and the gate verdict.
#[test]
#[ignore = "EF-9.0 measurement: minutes in release; run with --release --ignored --nocapture"]
fn ef9_0_refinement_gain_measurement() {
    assert_eq!(z_base_for_tile_size(TILE_PX), 4, "the shipped z_base the EF tests pin");
    let seeds: Vec<i32> = std::env::var("EF9_SEEDS")
        .map(|s| s.split(',').filter_map(|t| t.trim().parse().ok()).collect())
        .unwrap_or_else(|_| vec![483920, 24601, 71077345]);
    let grids: Vec<(usize, usize)> = std::env::var("EF9_GRIDS")
        .map(|s| s.split(',').filter_map(|t| t.split_once('x').and_then(|(a, b)| Some((a.trim().parse().ok()?, b.trim().parse().ok()?)))).collect())
        .unwrap_or_else(|_| vec![(2048, 1311), (512, 384)]);
    let (wsz, k) = (env_u32("EF9_WINDOW", DEFAULT_WINDOW), env_u32("EF9_K", DEFAULT_K));
    let z_base = z_base_for_tile_size(TILE_PX);
    let levels: Vec<u32> = (z_base..=z_base + KNEE_OCTAVES).map(|z| z as u32).collect();
    println!("EF-9.0 | tile {TILE_PX}px | levels {levels:?} | windows {k}x{k} of {wsz}x{wsz} tiles | seeds {seeds:?} | grids {grids:?}");

    // level -> (world label, cell)
    let mut cells: BTreeMap<u32, Vec<(String, Cell)>> = BTreeMap::new();
    let mut input_dist: Vec<(String, Vec<[f64; INPUTS.len()]>)> = Vec::new();
    for &(gw, gh) in &grids {
        for &seed in &seeds {
            let t = std::time::Instant::now();
            let wd = build_world(gw, gh, seed);
            let label = format!("{gw}x{gh}/s{seed}");
            let opts = world_amplify_opts(&wd.ws, &wd.p, TILE_PX);
            let inp = WorldInputs::build(
                &wd.ws.field, gw, gh, wd.ws.sea_level, wd.p.world, wd.p.map_width_km, wd.ws.stream_order.as_deref(), &wd.ws.boundary_type, &wd.ws.volcanic_field,
                wd.settlements.clone(), &wd.ways,
            );
            println!(
                "world {label}: generated in {:.1}s | settlements {} | ways {} segs {} | stream_order {} | boundary_type {} | volcanic_field {}",
                t.elapsed().as_secs_f64(),
                wd.settlements.len(),
                wd.ways.len(),
                inp.segs.len(),
                if inp.order.is_some() { "present" } else { "ABSENT" },
                if inp.boundary.is_some() { "present" } else { "ABSENT" },
                if inp.volcanic.is_some() { "present" } else { "ABSENT" },
            );
            // Defence: the harness's tile path is world_elevation_tile's own.
            let probe = ChunkId { z: (z_base + 2) as u32, col: 3, row: 2 };
            let via_engine = world_elevation_tile(&wd.ws, &wd.p, probe, TILE_PX).expect("tile");
            let direct = pyramid_tile(&wd.ws.field, gw, gh, probe, TILE_PX, &opts);
            assert!(via_engine.data.iter().zip(&direct.data).all(|(a, b)| a.to_bits() == b.to_bits()), "harness tile path must equal world_elevation_tile");

            let mut dist_rows = Vec::new();
            for &z in &levels {
                let tz = std::time::Instant::now();
                let (w, origins) = window_origins(z, wsz, k);
                let windows: Vec<(Vec<Row>, u32, (u32, u32))> =
                    origins.iter().map(|&o| (measure_window(&wd.ws.field, &inp, &opts, TILE_PX, z, o, w), w, o)).collect();
                for (rows, _, _) in &windows {
                    dist_rows.extend(rows.iter().map(|r| r.feat));
                }
                let cell = summarise(&windows, (seed as u64) << 8 | z as u64);
                println!("  z{z}: {} tiles in {} windows ({} skipped: no gain) in {:.1}s", cell.n_tiles, cell.windows, cell.windows_skipped, tz.elapsed().as_secs_f64());
                cells.entry(z).or_default().push((label.clone(), cell));
            }
            input_dist.push((label, dist_rows));
        }
    }

    // ---- input distributions (all measured tiles, all levels, per world)
    println!("\n== input distributions over measured tiles (min / median / p90 / max; absent shown as ABSENT) ==");
    for (label, rows) in &input_dist {
        println!("{label}  ({} tile-rows)", rows.len());
        for (k, name) in INPUTS.iter().enumerate() {
            let col: Vec<f64> = rows.iter().map(|r| r[k]).collect();
            if col.iter().all(|v| !v.is_finite()) {
                println!("    {name:<18} ABSENT");
            } else {
                println!(
                    "    {name:<18} {:9.4} / {:9.4} / {:9.4} / {:9.4}",
                    quantile(&col, 0.0).unwrap(),
                    quantile(&col, 0.5).unwrap(),
                    quantile(&col, 0.9).unwrap(),
                    quantile(&col, 1.0).unwrap()
                );
            }
        }
    }

    // ---- gain distributions and G_pt knee
    println!("\n== gain distributions per level: G_scr (RMS) min/median/p90/max, G_pt (RMS) median/max ==");
    for (z, v) in &cells {
        for (label, c) in v {
            println!("z{z} {label:<18} G_scr {} / {} / {} / {}   G_pt rms med {} max-of-max {:.5}", f3(c.scr_q[0]), f3(c.scr_q[1]), f3(c.scr_q[2]), f3(c.scr_q[3]), f3(c.pt_q[1]), c.pt_max);
        }
    }

    // ---- capture curves
    println!("\n== G_scr capture share at 10/25/50 % budgets, median over windows then median (min..max) over worlds ==");
    println!("random order would capture exactly the budget (0.10 / 0.25 / 0.50)");
    let mut gate_pairs: Vec<(u32, f64, Option<f64>)> = Vec::new();
    for (z, v) in &cells {
        println!("-- level z{z} ({} worlds)", v.len());
        let line = |name: &str, f: &dyn Fn(&Cell) -> [Option<f64>; 3]| {
            let cols: Vec<String> = (0..3).map(|p| mmm(&v.iter().map(|(_, c)| f(c)[p]).collect::<Vec<_>>())).collect();
            println!("   {name:<20} {} | {} | {}", cols[0], cols[1], cols[2]);
        };
        line("(a) centre distance", &|c| c.a);
        line("(b) oracle by G_scr", &|c| c.b);
        for (k, name) in INPUTS.iter().enumerate() {
            line(&format!("(c) {name}"), &|c| c.c[k]);
        }
        println!(
            "   tiles needed for 80% of G_scr: (b) {}  (a) {}",
            mmm(&v.iter().map(|(_, c)| c.need80_b).collect::<Vec<_>>()),
            mmm(&v.iter().map(|(_, c)| c.need80_a).collect::<Vec<_>>())
        );
        for (_, c) in v {
            if let (Some(a), Some(b)) = (c.a[1], c.b[1]) {
                if a > 0.0 {
                    let best_c = c.c.iter().filter_map(|x| x[1]).fold(f64::NAN, f64::max);
                    gate_pairs.push((*z, b / a, (best_c.is_finite()).then_some(best_c / a)));
                }
            }
        }
    }

    // ---- Spearman, pooled over (world, level) cells
    println!("\n== Spearman rho of each input vs each gain, median over (world, level) cells with z > z_base ==");
    println!("{:<18} {:>8} {:>8} {:>8} {:>8}", "input", "G_pt", "G_scr", "G_grad", "G_curv");
    for (k, name) in INPUTS.iter().enumerate() {
        let col = |g: usize| {
            let v: Vec<Option<f64>> = cells.iter().filter(|(z, _)| **z > z_base as u32).flat_map(|(_, v)| v.iter().map(move |(_, c)| c.rho[k][g])).collect();
            median_opt(&v)
        };
        println!("{name:<18} {:>8} {:>8} {:>8} {:>8}", f3(col(0)), f3(col(1)), f3(col(2)), f3(col(3)));
    }

    // ---- the gate
    let ratios: Vec<f64> = gate_pairs.iter().filter(|(z, _, _)| *z > z_base as u32).map(|x| x.1).collect();
    let best_c: Vec<f64> = gate_pairs.iter().filter(|(z, _, _)| *z > z_base as u32).filter_map(|x| x.2).collect();
    let med_b_over_a = quantile(&ratios, 0.5);
    let med_c_over_a = quantile(&best_c, 0.5);
    println!("\n== GATE (Q3 default: GO if oracle (b) >= {GATE_RATIO}x (a) at the 25 % budget, median across worlds) ==");
    for z in levels.iter().filter(|z| **z > z_base as u32) {
        let r: Vec<f64> = gate_pairs.iter().filter(|x| x.0 == *z).map(|x| x.1).collect();
        println!("z{z}: median (b)/(a) at 25 % = {} over {} worlds", f3(quantile(&r, 0.5)), r.len());
    }
    println!("pooled over worlds and levels z > z_base: median (b)/(a) = {} ; median best-single-input/(a) = {}", f3(med_b_over_a), f3(med_c_over_a));
    match med_b_over_a {
        Some(r) if r >= GATE_RATIO => println!("VERDICT (doc gate, oracle): GO  ({r:.3} >= {GATE_RATIO})"),
        Some(r) => println!("VERDICT (doc gate, oracle): NO-GO  ({r:.3} < {GATE_RATIO}): zoom depth alone is enough"),
        None => println!("VERDICT: not decidable -- no window with positive gain"),
    }
    match med_c_over_a {
        Some(r) => println!("achievable (best single input vs (a)): {r:.3}  [{} {GATE_RATIO}]", if r >= GATE_RATIO { ">=" } else { "<" }),
        None => println!("achievable: no input measured"),
    }
}

// --------------------------------------------------------- regression tests

#[cfg(test)]
mod tests {
    use super::*;

    /// Protects: the Spearman implementation on hand-computed values -- the
    /// perfect, reversed and tied cases -- and that an absent (`NaN`) pair is
    /// dropped rather than ranked as a number.
    #[test]
    fn spearman_matches_hand_computed_values() {
        let id = [1.0, 2.0, 3.0, 4.0, 5.0];
        assert!((spearman(&id, &[10.0, 20.0, 30.0, 40.0, 50.0]).unwrap() - 1.0).abs() < 1e-12);
        assert!((spearman(&id, &[5.0, 4.0, 3.0, 2.0, 1.0]).unwrap() + 1.0).abs() < 1e-12);
        // ranks a = [1.5,1.5,3.5,3.5], b = [1,2,3,4] -> cov 4, var 4 and 5 -> 4/sqrt(20)
        let rho = spearman(&[1.0, 1.0, 2.0, 2.0], &[1.0, 2.0, 3.0, 4.0]).unwrap();
        assert!((rho - 4.0 / 20.0f64.sqrt()).abs() < 1e-12, "ties share ranks: {rho}");
        // asymmetric ties (a three-way tie in the middle): ranks a = [1,3,3,3,5],
        // so cov 8, var 8 and 10 -> 8/sqrt(80). Ranking ties by first index
        // ([1,2,2,2,5]) would give 8/sqrt(92) instead.
        let rho = spearman(&[1.0, 2.0, 2.0, 2.0, 5.0], &id).unwrap();
        assert!((rho - 8.0 / 80.0f64.sqrt()).abs() < 1e-12, "three-way tie shares one rank: {rho}");
        // the NaN pair is excluded: the remaining 4 are perfectly monotone
        let r = spearman(&[1.0, f64::NAN, 3.0, 4.0, 5.0], &[1.0, 99.0, 3.0, 4.0, 5.0]).unwrap();
        assert!((r - 1.0).abs() < 1e-12);
        // constant or too-short series are undefined, not 0
        assert_eq!(spearman(&[2.0, 2.0, 2.0, 2.0], &[1.0, 2.0, 3.0, 4.0]), None);
        assert_eq!(spearman(&[1.0, 2.0], &[1.0, 2.0]), None);
    }

    /// Protects: the capture-share arithmetic and the integer budget rule
    /// (`ceil`, never zero tiles) against hand-summed gains, for the oracle
    /// order and for an arbitrary order, and that a zero-gain window is
    /// `None`, not 0 or 1.
    #[test]
    fn capture_share_and_budget_are_exact() {
        let gain = [1.0, 2.0, 3.0, 4.0, 10.0]; // total 20
        let oracle = order_desc(&gain, 7);
        assert_eq!(oracle, vec![4, 3, 2, 1, 0]);
        // n = 5: 10 % -> 1 tile, 25 % -> ceil(1.25) = 2, 50 % -> ceil(2.5) = 3
        assert_eq!([10, 25, 50].map(|p| budget_count(5, p)), [1, 2, 3]);
        assert_eq!(capture_share(&gain, &oracle, 10), Some(10.0 / 20.0));
        assert_eq!(capture_share(&gain, &oracle, 25), Some(14.0 / 20.0));
        assert_eq!(capture_share(&gain, &oracle, 50), Some(17.0 / 20.0));
        let natural = [0, 1, 2, 3, 4];
        assert_eq!(capture_share(&gain, &natural, 25), Some(3.0 / 20.0));
        assert_eq!(capture_share(&[0.0, 0.0], &[0, 1], 25), None);
        // smallest prefix reaching 80 % of 20 = 16: 10 + 4 + 3 = 17 -> 3 of 5 tiles
        assert_eq!(fraction_for_share(&gain, &oracle, 0.8), Some(3.0 / 5.0));
        // exactly reaching the target counts: 10 of 20 is the first tile alone
        assert_eq!(fraction_for_share(&gain, &oracle, 0.5), Some(1.0 / 5.0));
    }

    /// Protects: `order_desc` -- descending, absent (`NaN`) last, deterministic,
    /// a true permutation, and ties are NOT resolved in index order (which
    /// would hand every tied input a free spatial ordering).
    #[test]
    fn order_desc_ranks_absent_last_and_hashes_ties() {
        let o = order_desc(&[1.0, f64::NAN, 3.0, 2.0], 0);
        assert_eq!(o, vec![2, 3, 0, 1]);
        let tied = vec![5.0; 64];
        let a = order_desc(&tied, 1);
        assert_eq!(a, order_desc(&tied, 1), "deterministic");
        let mut s = a.clone();
        s.sort_unstable();
        assert_eq!(s, (0..64).collect::<Vec<_>>(), "a permutation");
        assert_ne!(a, (0..64).collect::<Vec<_>>(), "ties must not fall back to index order");
        assert_ne!(a, order_desc(&tied, 2), "the salt changes the tie-break");
    }

    /// Protects: `centre_distance_order` against `_nearest_tiles`'s rule on a
    /// 4x4 window: centre `(1.5, 1.5)`, the four middle tiles first (tied, so
    /// input order), corners last.
    #[test]
    fn centre_distance_order_matches_nearest_tiles() {
        let tiles: Vec<(u32, u32)> = (0..4).flat_map(|r| (0..4).map(move |c| (c, r))).collect();
        let o = centre_distance_order(&tiles, (1.5, 1.5));
        let first4: Vec<(u32, u32)> = o[..4].iter().map(|&i| tiles[i]).collect();
        assert_eq!(first4, vec![(1, 1), (2, 1), (1, 2), (2, 2)]);
        let last = tiles[*o.last().unwrap()];
        assert_eq!(last, (3, 3), "the farthest corner is last (ties by input order)");
        // an off-centre view moves the head of the order
        let o2 = centre_distance_order(&tiles, (0.0, 0.0));
        assert_eq!(tiles[o2[0]], (0, 0));
    }

    /// Protects: `clipped_length` (Liang-Barsky) on cases computable by hand --
    /// a horizontal run, a diagonal, fully outside, and a segment that starts
    /// outside and ends inside.
    #[test]
    fn clipped_length_matches_geometry() {
        let l = |p, q, b: [f64; 4]| clipped_length(p, q, b[0], b[1], b[2], b[3]);
        assert!((l((0.0, 0.0), (10.0, 0.0), [2.0, 5.0, -1.0, 1.0]) - 3.0).abs() < 1e-12);
        assert!((l((0.0, 0.0), (4.0, 4.0), [1.0, 3.0, 1.0, 3.0]) - 2.0 * 2.0f64.sqrt()).abs() < 1e-12);
        assert_eq!(l((0.0, 5.0), (10.0, 5.0), [2.0, 5.0, -1.0, 1.0]), 0.0);
        assert!((l((-5.0, 0.0), (3.0, 0.0), [0.0, 10.0, -1.0, 1.0]) - 3.0).abs() < 1e-12);
        assert_eq!(l((1.0, 1.0), (1.0, 1.0), [0.0, 2.0, 0.0, 2.0]), 0.0, "zero-length");
    }

    /// Protects: `footprint_cells` -- whole-grid at the root, never empty for a
    /// tile narrower than a cell, clamped at the far edge.
    #[test]
    fn footprint_cells_is_never_empty_and_is_clamped() {
        let root = pyramid_tile_bounds(100, 50, 0, 0, 0);
        assert_eq!(footprint_cells(&root, 100, 50), (0, 98, 0, 48));
        let deep = pyramid_tile_bounds(100, 50, 10, 5, 5);
        let (x0, x1, y0, y1) = footprint_cells(&deep, 100, 50);
        assert_eq!((x0, x1, y0, y1), (0, 0, 0, 0), "a sub-cell tile sees exactly the cell it sits in");
        let last = pyramid_tile_bounds(100, 50, 10, 1023, 1023);
        let (x0, x1, _, y1) = footprint_cells(&last, 100, 50);
        assert!(x0 <= x1 && x1 <= 99 && y1 <= 49, "clamped to the grid: {x0}..{x1}, {y1}");
    }

    /// Protects: `resample_parent` -- the quadrant map `(col & 1) * (w-1)/2 +
    /// ox/2` -- on a linear ramp, where bilinear is exact: the left child's
    /// texels span the parent's left half, the right child's its right half,
    /// and an unrefined (linear) child therefore measures zero G_scr.
    #[test]
    fn resample_parent_maps_the_quadrant_exactly() {
        let (w, h) = (5usize, 5usize);
        let parent: Vec<f32> = (0..h).flat_map(|_| (0..w).map(|x| x as f32)).collect();
        let left = resample_parent(&parent, w, h, 0, 0);
        let right = resample_parent(&parent, w, h, 1, 0);
        assert_eq!((left[0], left[w - 1]), (0.0, 2.0));
        assert_eq!((right[0], right[w - 1]), (2.0, 4.0));
        assert_eq!(left[1], 0.5, "texel 1 sits half a parent texel in");
        let child_truth: Vec<f32> = (0..h).flat_map(|_| (0..w).map(|x| 2.0 + x as f32 * 0.5)).collect();
        assert_eq!(rms_diff(&child_truth, &right), 0.0);
        assert_eq!(gradient_rms_diff(&child_truth, &right, w, h), 0.0);
        // the row axis maps the same way: a vertical ramp, top child vs bottom child
        let vparent: Vec<f32> = (0..h).flat_map(|y| (0..w).map(move |_| y as f32)).collect();
        let (top, bottom) = (resample_parent(&vparent, w, h, 0, 0), resample_parent(&vparent, w, h, 0, 1));
        assert_eq!((top[0], top[(h - 1) * w]), (0.0, 2.0));
        assert_eq!((bottom[0], bottom[(h - 1) * w]), (2.0, 4.0));
        assert_eq!(top[w], 0.5, "row 1 sits half a parent texel in");
    }

    /// Protects: `tile_gain`'s plumbing -- the parent is the tile at
    /// `(col >> 1, row >> 1)` one level up (both axes), the baseline is that
    /// parent resampled by `resample_parent`, and G_curv is the child's
    /// curvature energy over the baseline's (not the reverse). The controls'
    /// field is constant down each column, so they cannot see a wrong row;
    /// this uses an odd `(col, row)` on a field that varies in both axes and
    /// recomputes the expectation from independently built parent ids.
    #[test]
    fn tile_gain_uses_the_right_parent_and_baseline() {
        let n = 33;
        let coarse: Vec<f32> = (0..n * n)
            .map(|i| {
                let (x, y) = ((i % n) as f32, (i / n) as f32);
                0.55 + 0.25 * (x * 0.31).sin() * (y * 0.47).cos() + 0.004 * x * y / n as f32
            })
            .collect();
        let opts = AmplifyOpts { seed: 7, sea: 0.42, z_base: 2, ..AmplifyOpts::default() };
        let id = ChunkId { z: 4, col: 5, row: 3 };
        let g = tile_gain(&coarse, n, n, &opts, 32, id);
        let tile = pyramid_tile(&coarse, n, n, id, 32, &opts);
        let parent = pyramid_tile(&coarse, n, n, ChunkId { z: 3, col: 2, row: 1 }, 32, &opts);
        let base = resample_parent(&parent.data, tile.w, tile.h, 5, 3);
        assert!(g.g_scr > 0.0);
        assert!((g.g_scr - rms_diff(&tile.data, &base)).abs() < 1e-12, "{} vs {}", g.g_scr, rms_diff(&tile.data, &base));
        let ratio = curvature_energy(&tile.data, tile.w, tile.h) / curvature_energy(&base, tile.w, tile.h);
        let gc = g.g_curv.expect("the baseline has curvature");
        assert!((gc - ratio).abs() < 1e-9 * ratio.abs().max(1.0), "{gc} vs {ratio}");
        assert!((ratio - 1.0).abs() > 1e-3, "the ratio must differ from its inverse for this to bite: {ratio}");
    }

    /// Protects: `gradient_rms_diff` and `rms_diff` on values computable by
    /// hand: ramps of slope 1 vs 3 differ by exactly 2 in gradient.
    #[test]
    fn gradient_and_rms_differences_are_exact() {
        let (w, h) = (6usize, 6usize);
        let ramp = |s: f32| -> Vec<f32> { (0..h).flat_map(|_| (0..w).map(move |x| s * x as f32)).collect() };
        assert!((gradient_rms_diff(&ramp(1.0), &ramp(3.0), w, h) - 2.0).abs() < 1e-9);
        assert_eq!(gradient_rms_diff(&ramp(1.0), &ramp(1.0), w, h), 0.0);
        assert!((rms_diff(&[1.0, 1.0], &[0.0, 2.0]) - 1.0).abs() < 1e-12);
    }

    /// Protects: `quantile` / `median_opt` on hand values: interpolation
    /// between order statistics, `None` for nothing, and that `None`/`NaN`
    /// entries are skipped rather than counted.
    #[test]
    fn quantile_and_median_are_exact() {
        assert_eq!(quantile(&[4.0, 1.0, 3.0, 2.0], 0.5), Some(2.5));
        assert!((quantile(&[1.0, 2.0, 3.0, 4.0], 0.9).unwrap() - 3.7).abs() < 1e-12);
        assert_eq!((quantile(&[1.0, 2.0], 0.0), quantile(&[1.0, 2.0], 1.0)), (Some(1.0), Some(2.0)));
        assert_eq!(quantile(&[], 0.5), None);
        assert_eq!(quantile(&[f64::NAN], 0.5), None);
        assert_eq!(median_opt(&[Some(1.0), None, Some(3.0)]), Some(2.0));
        assert_eq!(median_opt(&[None, None]), None);
    }

    /// Builds a 4x4 window of rows whose G_scr is `gain(col, row)` and whose
    /// two inputs are given by `f0` and `f1` (`NaN` = absent).
    fn fake_window(gain: impl Fn(u32, u32) -> f64, f0: impl Fn(u32, u32) -> f64, f1: impl Fn(u32, u32) -> f64) -> Vec<Row> {
        let mut rows = Vec::new();
        for r in 0..4u32 {
            for c in 0..4u32 {
                let mut feat = [f64::NAN; INPUTS.len()];
                feat[0] = f0(c, r);
                feat[1] = f1(c, r);
                let g = Gains { g_pt_rms: 0.0, g_pt_max: 0.0, g_scr: gain(c, r), g_grad: 0.0, g_curv: None };
                rows.push(Row { col: c, row: r, gains: g, feat });
            }
        }
        rows
    }

    /// Protects: `capture_window` end to end on a hand-built window whose gain
    /// sits on the four corner tiles (the farthest from the view centre), so
    /// today's order must do worse than random and the oracle must take them
    /// first: 4 corners of 16 tiles, 25 % budget = 4 tiles. An input equal to
    /// the gain must tie the oracle; an all-absent input is `None`, not 0.
    #[test]
    fn capture_window_scores_the_three_orders() {
        let corner = |c: u32, r: u32| if (c == 0 || c == 3) && (r == 0 || r == 3) { 5.0 } else { 0.0 };
        let rows = fake_window(corner, corner, |_, _| f64::NAN);
        let cap = capture_window(&rows, 4, (0, 0), 3);
        assert_eq!(cap.b, [Some(0.5), Some(1.0), Some(1.0)], "oracle: 10 % -> ceil(1.6) = 2 tiles = 2 of 4 corners; 25 % -> all 4");
        assert_eq!(cap.a, [Some(0.0), Some(0.0), Some(0.0)], "centre-first order reaches no corner within 50 % (the 8 nearest tiles)");
        assert_eq!(cap.c[0], cap.b, "an input identical to the gain captures what the oracle does");
        assert_eq!(cap.c[1], [None; 3], "an all-absent input has no curve");
        assert_eq!(cap.need80_b, Some(4.0 / 16.0), "4 corners hold 100 %: 3 of 4 reach 75 %, 4 are needed for 80 %");
        // a window with no gain anywhere has no capture at all
        let flat = fake_window(|_, _| 0.0, |_, _| 1.0, |_, _| 1.0);
        let c0 = capture_window(&flat, 4, (0, 0), 3);
        assert_eq!((c0.a, c0.b), ([None; 3], [None; 3]));
    }

    /// Protects: `window_origins` -- whole level when it fits the window,
    /// otherwise `k x k` even-snapped, in-range, distinct windows.
    #[test]
    fn window_origins_cover_in_range_and_snap_even() {
        assert_eq!(window_origins(3, 16, 3), (8, vec![(0, 0)]));
        let (w, o) = window_origins(10, 16, 3);
        assert_eq!(w, 16);
        assert_eq!(o.len(), 9);
        assert!(o.iter().all(|&(c, r)| c % 2 == 0 && r % 2 == 0 && c + w <= 1024 && r + w <= 1024));
        // z = 6, w = 13: span 51, so the raw centres are 8.5, 25.5, 42.5 and the
        // middle one is odd -> snaps to 24 (a window must start on an even tile
        // so it holds whole parent/child quadrants).
        let (w, o) = window_origins(6, 13, 3);
        assert_eq!(w, 13);
        assert_eq!(o.iter().take(3).map(|&(c, _)| c).collect::<Vec<_>>(), vec![8, 24, 42]);
    }

    /// Builds the controls' world: a `n x n` coarse field, a flat plain at
    /// `plain`, with a narrow ridge of height `ridge` along column `rx`.
    fn ridge_world(n: usize, plain: f32, ridge: f32, rx: usize) -> Vec<f32> {
        let mut f = vec![plain; n * n];
        for y in 0..n {
            for x in 0..n {
                let d = (x as f32 - rx as f32).abs();
                if d <= 2.0 {
                    f[y * n + x] = plain + (ridge - plain) * (1.0 - d / 3.0);
                }
            }
        }
        f
    }

    /// Measures every tile of level `z` over a small control world at a 32 px
    /// tile (so 16x16 tiles at z = 4 stay cheap), returning `(rows, side)`.
    fn measure_control(coarse: &[f32], n: usize, opts: &AmplifyOpts, z: u32) -> (Vec<Row>, u32) {
        let inp = WorldInputs::build(coarse, n, n, opts.sea, false, 100.0, None, &[], &[], Vec::new(), &[]);
        let side = 1u32 << z;
        (measure_window(coarse, &inp, opts, 32, z, (0, 0), side), side)
    }

    /// Protects: the positive control (§8.3) -- one ridge on a flat plain.
    /// The oracle order puts the ridge's tiles first, `slope_max` alone ranks
    /// them first too, and tiles far from the ridge measure exactly zero
    /// G_scr (a flat plain gains nothing). Without this the capture curves
    /// could be reporting noise.
    #[test]
    fn positive_control_ranks_the_ridge_first() {
        let n = 33;
        let coarse = ridge_world(n, 0.60, 0.95, 16);
        let opts = AmplifyOpts { seed: 7, sea: 0.42, z_base: 2, ..AmplifyOpts::default() };
        let (rows, side) = measure_control(&coarse, n, &opts, 4);
        let ridge_cols = |c: u32| (6..=9).contains(&c);
        let gain: Vec<f64> = rows.iter().map(|r| r.gains.g_scr).collect();
        let k = rows.iter().filter(|r| ridge_cols(r.col)).count();
        assert_eq!(k as u32, 4 * side);
        let top_b = order_desc(&gain, 1);
        let hits_b = top_b.iter().take(k).filter(|&&i| ridge_cols(rows[i].col)).count();
        assert_eq!(hits_b, k, "oracle top-{k} must be exactly the ridge corridor");
        let slope: Vec<f64> = rows.iter().map(|r| r.feat[1]).collect();
        let top_s = order_desc(&slope, 1);
        let hits_s = top_s.iter().take(k).filter(|&&i| ridge_cols(rows[i].col)).count();
        assert_eq!(hits_s, k, "slope_max alone must rank the ridge corridor first");
        let far_max = rows.iter().filter(|r| r.col <= 2 || r.col >= 13).map(|r| r.gains.g_scr).fold(0.0, f64::max);
        let near_max = rows.iter().filter(|r| ridge_cols(r.col)).map(|r| r.gains.g_scr).fold(0.0, f64::max);
        assert!(near_max > 0.0 && far_max < near_max * 1e-3, "plain {far_max} vs ridge {near_max}");
    }

    /// Protects: the negative control (§8.3) -- the same tiles with
    /// `detail_amp = 0` must measure G_pt exactly 0 (every texel difference,
    /// not an approximation), and the same world with detail on must not
    /// (so the zero is the control working, not G_pt being dead code).
    #[test]
    fn negative_control_detail_off_is_exactly_zero_g_pt() {
        let n = 33;
        let coarse = ridge_world(n, 0.60, 0.95, 16);
        let on = AmplifyOpts { seed: 7, sea: 0.42, z_base: 2, ..AmplifyOpts::default() };
        let off = AmplifyOpts { detail_amp: 0.0, ..on };
        let (rows_off, _) = measure_control(&coarse, n, &off, 4);
        assert!(rows_off.iter().all(|r| r.gains.g_pt_rms == 0.0 && r.gains.g_pt_max == 0.0), "detail_amp = 0 must give G_pt == 0 exactly");
        let (rows_on, _) = measure_control(&coarse, n, &on, 4);
        assert!(rows_on.iter().any(|r| r.gains.g_pt_max > 0.0), "with detail on, G_pt must be live");
    }

    /// Protects: absence handling -- a world with no `stream_order`, no
    /// `boundary_type` and no `volcanic_field` reports those inputs as `NaN`
    /// (absent), while present inputs stay finite; absent is never 0.
    #[test]
    fn absent_inputs_are_nan_not_zero() {
        let n = 33;
        let coarse = ridge_world(n, 0.60, 0.95, 16);
        let inp = WorldInputs::build(&coarse, n, n, 0.42, false, 100.0, None, &[], &[], vec![(16, 16)], &[]);
        let f = inp.features(&pyramid_tile_bounds(n, n, 2, 1, 1));
        assert!(f[4].is_nan() && f[6].is_nan() && f[7].is_nan(), "order/boundary/volcanic absent: {f:?}");
        assert!(f[0].is_finite() && f[5].is_finite() && f[8].is_finite() && f[9].is_finite());
        assert_eq!(f[5], 1.0, "a plain at 0.60 over sea 0.42 is all land");
        assert_eq!(f[8], 0.0, "no settlement in tile (1,1)'s cells");
        let order = vec![3i16; n * n];
        let bt = vec![1u8; n * n];
        let vf = vec![0.5f32; n * n];
        let inp = WorldInputs::build(&coarse, n, n, 0.42, false, 100.0, Some(&order), &bt, &vf, vec![], &[]);
        let f = inp.features(&pyramid_tile_bounds(n, n, 2, 1, 1));
        assert_eq!((f[4], f[6], f[7]), (3.0, 1.0, 0.5));
    }

    /// Protects: the settlement and way-length inputs against a hand-built
    /// fixture: one settlement inside the footprint and one outside, and one
    /// way crossing a known box (bins must not change the exact length).
    #[test]
    fn settlement_and_way_inputs_are_exact() {
        let n = 33;
        let coarse = vec![0.6f32; n * n];
        // z = 2 -> 4x4 tiles over 32 coarse cells: tile (0,0) covers cells 0..=7.
        let ways = vec![vec![(0.0, 4.0), (20.0, 4.0)], vec![(2.0, 2.0), (2.0, 2.0)], vec![(20.0, 10.0), (30.0, 10.0)]];
        let inp = WorldInputs::build(&coarse, n, n, 0.42, false, 100.0, None, &[], &[], vec![(3, 3), (20, 20)], &ways);
        let f = inp.features(&pyramid_tile_bounds(n, n, 2, 0, 0));
        assert_eq!(f[8], 1.0, "only the (3,3) settlement is in cells 0..=7");
        assert!((f[9] - 8.0).abs() < 1e-12, "the way's 0..8 run inside the box [0,8]: {}", f[9]);
        // tile (2,0) covers cells 16..=23, a later 16-cell bin than the way's
        // start: the 0..20 way must be found there too, clipped to 16..20.
        let f2 = inp.features(&pyramid_tile_bounds(n, n, 2, 2, 0));
        assert!((f2[9] - 4.0).abs() < 1e-12, "a segment spanning bins registers in each: {}", f2[9]);
        let f3 = inp.features(&pyramid_tile_bounds(n, n, 2, 3, 0));
        assert_eq!(f3[9], 0.0, "no way reaches cells 24..=31 at y 0..8 (a measured zero, not absent)");
        // the whole-world tile's query box spans both 16-cell bins; the third way
        // lives only in the second bin (x 20..30), so a query that stopped at the
        // first bin would report 20 instead of 20 + 10.
        let f0 = inp.features(&pyramid_tile_bounds(n, n, 0, 0, 0));
        assert!((f0[9] - 30.0).abs() < 1e-12, "a box spanning bins sums every bin's segments once: {}", f0[9]);
    }
}
