//! Golden-parity tests for settlement population + naming --
//! `PHASE2_SCOPE.md` milestone 9: `_civBasePopForKind` (reference HTML
//! line ~23433) and `_civSettleName` (line ~20717), the rest of
//! `_civIterativeAutoWorld`'s `places.map(...)` closure that milestone 8's
//! `place_settlements` stopped short of (reference lines ~25409-25444).
//! Generated from a Node `vm` extraction run against
//! `reference/Cartalith Gen1 v2.10.html` (harness itself is transient,
//! not checked in) that calls the reference's own `_civRng`/
//! `_civSettleName`/`_civBasePopForKind` directly against the already-
//! verified (x, y, faction, kind) tuples `golden_parity_settlement_placement.rs`
//! (milestone 8) already confirmed correct -- not a hand-composed
//! reimplementation, and not re-running the full DOM-coupled
//! `_civIterativeAutoWorld` wrapper (unnecessary: naming/population read
//! nothing DOM-related, only `rng`, `faction`, `kind`, and the already-
//! verified `suit` value at each settlement's position).
//!
//! **A real harness pitfall, worth recording**: the reference file has
//! FOUR `<script>` blocks, not the one/two assumed by earlier milestones'
//! own doc comments. `_civRng`/`_civSettleName`/`_civAssignLandmassFactions`
//! all live in block #2 (lines 14562-26721), not block #1 (2083-14557,
//! the terrain engine other milestones needed). Concatenating blocks #1+#2
//! is required to get both. **Do not re-derive block boundaries by
//! scanning for the literal text `<script>`** -- block #2 itself contains
//! a comment discussing "this file's three sequential `<script>` tags" in
//! prose, and a naive regex scan counts that occurrence too, miscounting
//! every subsequent block. Use the real line numbers from a direct
//! `grep -n '<script>'`/`grep -n '</script>'` on the file instead (2083/
//! 14562/26722/28166 opening, 14557/26721/28162/31104 closing at time of
//! writing -- re-verify if the reference is ever re-frozen to a newer
//! version, these are content-dependent, not structural guarantees).
//!
//! **The "same name in both fixtures" result is not a bug or a
//! coincidence -- it is a fully mechanical, provable consequence of one
//! genuine, verified quirk in the reference, confirmed at runtime (not
//! just by static grep)**: `_civIterativeAutoWorld` seeds its naming RNG
//! from `_civRng((state.seed||12345)*31337+999)` (reference line 25339)
//! -- but `state.seed` (the bare top-level field, distinct from
//! `state.tect.seed`, the real per-world terrain seed) is never assigned
//! anywhere in the reference file. Every `.seed=` write site is unrelated
//! (`_sculptCtx.seed`, `opts.seed` for erosion droplets, an export-
//! metadata field that itself reads `state.tect.seed`). So
//! `state.seed||12345` always evaluates to the literal `12345`, and this
//! Node harness's own extraction confirms it live: `state.seed` reads as
//! `undefined` immediately after a real `generate()` run, for both
//! fixture configs. Consequence: the civ-naming RNG stream is seeded
//! IDENTICALLY -- same starting state, same full sequence of `rng()`
//! outputs at every position -- for every world ever generated by the
//! reference, regardless of that world's actual terrain seed. Since
//! `_civAssignLandmassFactions` (milestone 8, consumes no RNG) assigns
//! faction ids by cycling from `1` in ascending landmass-id order, the
//! first landmass processed in any world earns faction `1` -- true for
//! both fixtures here. A rank-1 settlement in any two worlds therefore
//! draws from the identical RNG position into the identical culture pool
//! (faction 1 -> `CIV_CULTURES[1 % 7]` = "imperial"), producing the exact
//! same name. This chains forward: naming a settlement consumes a
//! variable RNG-drawn call count, but the population-variance term after
//! it always consumes exactly one more call regardless of its numeric
//! inputs -- so if settlement N's name matches, the RNG stream position
//! entering settlement N+1 also matches, and if settlement N+1 shares the
//! same faction too (both fixtures assign 1,2,3,... in rank order here),
//! its name matches as well. Verified directly in the extraction: case0's
//! three settlements (factions 1,2,3) and case1's first three (factions
//! 1,2,3) produced byte-identical names pairwise; case1's settlements 4
//! and 5 (factions 4,5, no counterpart in case0) are unique, exactly as
//! this mechanism predicts.
//!
//! `field[0..5]` cross-checked against a direct `generate_terrain` call
//! with identical params before trusting the extraction -- matched
//! exactly for both cases. `suit` at each settlement's position also
//! cross-checked against `golden_parity_settlement_suitability.rs`'s own
//! already-verified fixture (e.g. case0's (9,3) reads `0.7972438931465149`
//! in both files) -- not re-derived, read directly from the same already-
//! trusted field.
//!
//! **A real bug caught in this test's OWN first harness attempt, not in
//! `place_settlements`**: `SettlementPlacement.suit` (milestone 8, already
//! correctly implemented) carries the settlement's ORIGINAL SEED score
//! (`s.score` from `findSettlementSeeds`, sampled BEFORE land/coast
//! snapping) straight through -- reference line 25398:
//! `candidates.push({x:fx,y:fy,suit:s.score,contId:...})`, note `s.score`,
//! not a fresh `suit[fy*GW+fx]` lookup at the snapped position `(fx,fy)`.
//! Milestone 8's own golden test (`golden_parity_settlement_placement.rs`)
//! never checked `.suit` itself (only x/y/faction/capital/kind/coastal),
//! so this went unverified until this milestone's population formula
//! (which reads `.suit` directly) exposed it: the first harness attempt
//! here re-sampled `suit[]` at the snapped position instead, producing
//! wrong pop values with CORRECT names (naming doesn't touch `.suit` at
//! all) -- a real, useful signal that narrowed the bug to the harness's
//! `suit` extraction, not the RNG/naming logic, before any Rust code was
//! touched. Fixed by mirroring the reference's real candidate-building
//! loop (`_civSnapLand`/`_civSnapCoast`/land-component DFS, lines
//! ~25366-25401) directly in the harness rather than hand-deriving
//! seed-to-candidate suit mappings.
//!
//! **A second harness bug, same root-cause category (wrong parameter,
//! not wrong algorithm)**: the harness's first replacement attempt used
//! `_civIterativeAutoWorld`'s own `suppR=Math.max(6,(GW/22)|0)` for
//! `findSettlementSeeds`, dropping 1-3 real settlements per fixture
//! (over-aggressive suppression). This crate's established convention
//! (`golden_parity_settlement_suitability.rs`'s own resolved finding) is
//! the export path's bare default (`Math.max(4,W/20)`, matching
//! `find_settlement_seeds`'s existing Rust call sites) -- `_civSettleName`/
//! pop are the ONLY things unique to `_civIterativeAutoWorld` this
//! milestone ports; its own `suppR` tuning is a separate, not-yet-ported
//! concern (that whole interactive-auto-populate call shape isn't this
//! port's production path, per milestone 7's own established reasoning).
//!
//! Names are RNG-driven strings -- checked by exact string equality (no
//! rounding involved once the RNG stream is confirmed in sync, unlike
//! continuous float fields). Population is a `round()` of a continuous
//! formula -- checked as an exact `u32`, since `round()` removes
//! sub-integer ambiguity and this crate's `f32`/`f64` pipeline should
//! reproduce the same rounded integer, not merely a close one.

fn assert_named_settlements_match(
    actual: &[cartalith_civ::NamedSettlement],
    expected: &[(usize, usize, i32, &str, u32)],
    label: &str,
) {
    assert_eq!(actual.len(), expected.len(), "{label}: settlement count mismatch");
    for (i, (a, &(ex, ey, efaction, ename, epop))) in actual.iter().zip(expected.iter()).enumerate() {
        assert_eq!(a.placement.x, ex, "{label} settlement {i}: x mismatch");
        assert_eq!(a.placement.y, ey, "{label} settlement {i}: y mismatch");
        assert_eq!(a.placement.faction, efaction, "{label} settlement {i}: faction mismatch");
        assert_eq!(a.name, ename, "{label} settlement {i}: name mismatch");
        assert_eq!(a.pop, epop, "{label} settlement {i}: pop mismatch");
    }
}

#[test]
fn settlement_naming_case_0_region() {
    // case0_region: gw=14 gh=11 seed=24601 world=false
    // Same (x,y,faction) triples as golden_parity_settlement_placement.rs's
    // case0 (all capital, all coastal) -- naming/pop continues that exact
    // output, same rank order.
    let expected = vec![
        (7usize, 2usize, 1i32, "Sevjuniana", 19465u32),
        (9, 3, 2, "Hurngarngarnhaskcairn", 20094),
        (6, 2, 3, "Ghalbahrghaltazdune", 22094),
    ];

    let mut p = cartalith_engine::WorldParams::defaults(14, 11, 24601);
    p.world = false;
    p.climate.w_iters = 12;
    let ws = cartalith_engine::generate_terrain(&p);
    assert!((ws.sea_level - 0.42f64).abs() < 1e-9, "sea_level mismatch, harness assumption broken");

    let named = compute_named_settlements(&ws, 14, 11, false, p.map_width_km, p.river_density);
    assert_named_settlements_match(&named, &expected, "case0_region");
}

#[test]
fn settlement_naming_case_1_world_wrap() {
    // case1_world_wrap: gw=16 gh=12 seed=314159 world=true
    // Same 5 (x,y,faction) triples as golden_parity_settlement_placement.rs's
    // case1 (all capital, all coastal). Settlements 1-3 (factions 1-3)
    // produce the SAME names as case0's -- see this file's module doc
    // comment for the full mechanical explanation (fixed civ-naming RNG
    // seed, independent of terrain seed). Settlements 4-5 (factions 4-5)
    // have no counterpart in case0 and are unique.
    let expected = vec![
        (9usize, 3usize, 1i32, "Sevjuniana", 20354u32),
        (5, 8, 2, "Hurngarngarnhaskcairn", 20697),
        (8, 9, 3, "Ghalbahrghaltazdune", 22698),
        (10, 5, 4, "Orenelywash", 15972),
        (4, 7, 5, "Taela'elorashade", 22508),
    ];

    let mut p = cartalith_engine::WorldParams::defaults(16, 12, 314159);
    p.world = true;
    p.climate.w_iters = 12;
    let ws = cartalith_engine::generate_terrain(&p);
    assert!((ws.sea_level - 0.42f64).abs() < 1e-9, "sea_level mismatch, harness assumption broken");

    let named = compute_named_settlements(&ws, 16, 12, true, p.map_width_km, p.river_density);
    assert_named_settlements_match(&named, &expected, "case1_world_wrap");
}

/// Cross-check: the same fixed civ-naming seed input this port's own
/// `civ_name_rng()` uses. `12345` is not a placeholder -- it is the
/// literal fallback value the reference's own `(state.seed||12345)`
/// evaluates to, always, per this file's module doc comment.
#[test]
fn civ_name_rng_seed_input_matches_reference_literal() {
    assert_eq!(cartalith_civ::CIV_NAME_RNG_SEED_INPUT, 12345);
}

/// Assembles every affordance field milestones 1-8 provide and runs
/// `name_and_populate_settlements` -- the exact composition
/// `_civIterativeAutoWorld`'s `places.map(...)` closure performs for the
/// naming/population half (reference lines ~25409-25444), matching
/// `golden_parity_settlement_placement.rs`'s own `compute_placements` for
/// the shared upstream fields.
fn compute_named_settlements(
    ws: &cartalith_engine::WorldState,
    gw: usize,
    gh: usize,
    world: bool,
    map_width_km: f64,
    river_density: f64,
) -> Vec<cartalith_civ::NamedSettlement> {
    let wb = cartalith_civ::build_water_bodies(&ws.field, gw, gh, ws.sea_level, world, Some(&ws.rainfall));
    let biome = cartalith_civ::build_biome_raster(&wb.classification, &ws.temperature, &ws.rainfall);

    let soil_slope = cartalith_civ::build_slope_field(&ws.field, gw, gh, world);
    let lithology = cartalith_civ::build_lithology(
        &ws.field, &ws.age_field, &ws.volcanic_field, &ws.crust_field, &ws.resistance_field, &ws.rainfall, ws.sea_level,
    );
    let soil = cartalith_civ::build_soil_fertility(&lithology, &ws.temperature, &ws.rainfall, &soil_slope, &ws.age_field);

    let flow_thresh = cartalith_hydrology::river_flow_thresh(gw, gh, gw, map_width_km);
    let water_access = cartalith_civ::build_water_access(&ws.flow_discharge, &ws.field, gw, gh, ws.sea_level, flow_thresh);
    let carrying_cap = cartalith_civ::build_carrying_capacity(
        &soil, &water_access, Some(&biome), &ws.temperature, &ws.field, ws.sea_level, 0.0, None,
    );

    let resources = cartalith_civ::build_resource_potentials(
        &lithology,
        Some(&ws.boundary_type),
        Some(&ws.shear_field),
        Some(&ws.flow_discharge),
        Some(&biome),
        &ws.field,
        &ws.rainfall,
        &ws.age_field,
        gw,
        gh,
        ws.sea_level,
        Some(&ws.volcanic_field),
        true,
        false,
    );

    let raw_slope = cartalith_civ::build_raw_slope_field(&ws.field, gw, gh, world);
    let corridors = cartalith_civ::build_route_corridors(&ws.field, &raw_slope, Some(&ws.flow_discharge), gw, gh, ws.sea_level, world, flow_thresh);
    let landmass = cartalith_civ::build_landmass_quality(&ws.field, Some(&carrying_cap), gw, gh, ws.sea_level, world);
    let coast_sdf = cartalith_civ::build_coast_sdf(&ws.field, gw, gh, ws.sea_level);
    let flood = cartalith_civ::build_flood_field(&ws.field, &ws.flow_discharge, &raw_slope, gw, gh, ws.sea_level);

    let river_order = cartalith_civ::fresh_river_order(&ws.field, &ws.flow_discharge, gw, gh, ws.sea_level, world, river_density, map_width_km);

    let ctx = cartalith_civ::SuitabilityCtx {
        water_bodies: Some(&wb.classification),
        corridor: Some(&corridors),
        landmass: Some(&landmass.quality),
        flow: Some(&ws.flow_discharge),
        river_order: Some(&river_order),
        coast_sdf: Some(&coast_sdf),
        resources: Some(&resources),
        rain: Some(&ws.rainfall),
        flood: Some(&flood),
        slope_raw: Some(&raw_slope),
        flow_thresh,
    };

    let slope_n = cartalith_civ::build_slope_field(&ws.field, gw, gh, world);
    let suit = cartalith_civ::build_settlement_suitability(&soil, &water_access, &carrying_cap, &ws.field, &slope_n, gw, gh, ws.sea_level, Some(&ctx));
    let seeds = cartalith_civ::find_settlement_seeds(&suit, gw, gh, 0.65, (gw as f64 / 20.0).max(4.0));

    // factionCount = CIV_FACTIONS.length-1 = 7-1 = 6 (reference line 14568).
    let placements = cartalith_civ::place_settlements(&seeds, &suit, &ws.field, &wb.classification, &wb.fill_level, gw, gh, ws.sea_level, world, 6);

    cartalith_civ::name_and_populate_settlements(&placements)
}
