//! GENERATED by `tools/civ_want_counts_capture.js` -- do not edit by hand.
//! The reference's own `wantCounts` tier classifier (v2.11 25925-25931), run
//! under Node over synthetic (capitalOf, counts) pairs, against
//! `cartalith_civ::civ_quota_tier` called once per rank in the same order.

use cartalith_civ::{civ_quota_tier, SettlementKind::{self, *}};

#[rustfmt::skip]
const CASES: &[(&[bool], [usize; 5], &[SettlementKind])] = &[
    (&[true, false, true, false, false, true], [2, 1, 1, 1, 1], &[Capital, Capital, City, Town, Village, Hamlet]),
    (&[false, false, true, false], [3, 0, 0, 0, 1], &[Capital, Capital, Capital, Hamlet]),
    (&[true, true, true], [0, 1, 0, 0, 5], &[City, Hamlet, Hamlet]),
    (&[true, false, false, false, false, false, false], [1, 1, 1, 0, 0], &[Capital, City, Town, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, true, false, true, false], [0, 0, 2, 0, 1], &[Town, Town, Hamlet, Hamlet, Hamlet]),
    (&[true], [1, 0, 0, 0, 0], &[Capital]),
    (&[false, false, true, false, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, true, false, false, true, false, false, false, true, false], [0, 3, 7, 7, 5], &[City, City, City, Town, Town, Town, Town, Town, Town, Town, Village, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, false, false, false, false, false, false, false, true, false, true], [8, 2, 6, 2, 4], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, City, Town, Town]),
    (&[true, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, true, false], [6, 8, 2, 2, 7], &[Capital, Capital, Capital, Capital, Capital, Capital, City, City, City, City, City, City, City, City, Town, Town, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, true, true, false, false, true, false, false, false], [8, 1, 1, 3, 0], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, Town, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, false, false, false, false, false, false, false, false, false, false, true], [1, 2, 8, 8, 7], &[Capital, City, City, Town, Town, Town, Town, Town, Town, Town, Town, Village, Village]),
    (&[false, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false], [1, 8, 0, 6, 7], &[Capital, City, City, City, City, City, City, City, City, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true], [4, 7, 4, 2, 5], &[Capital, Capital, Capital, Capital, City, City, City, City, City, City, City, Town, Town, Town, Town, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, false, false, false, true, true, false, false, true, true, false, false], [6, 6, 1, 2, 6], &[Capital, Capital, Capital, Capital, Capital, Capital, City, City, City, City, City, City, Town]),
    (&[false, true, false, true, false, false, false, true, false, true, true, false, false, true, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false], [7, 7, 8, 8, 6], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, City, City, City, City, City, City, Town, Town, Town, Town, Town, Town, Town, Town, Village, Village, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, true, true, false, false, false, false, false, true, false, false, false], [8, 4, 6, 5, 5], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, City, City, City, Town]),
    (&[false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, true, false, false, false, false, true, true, false, false, false, false], [7, 0, 0, 8, 1], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Village, Village, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false], [2, 5, 3, 7, 2], &[Capital, Capital, City, City, City, City, City, Town, Town, Town, Village, Village, Village, Village, Village, Village, Village, Hamlet]),
    (&[false], [1, 6, 6, 2, 0], &[Capital]),
    (&[false, false, true, true, false, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true], [3, 6, 4, 7, 2], &[Capital, Capital, Capital, City, City, City, City, City, City, Town, Town, Town, Town, Village, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
    (&[false, false], [0, 4, 3, 1, 6], &[City, City]),
    (&[false, true, true, false, false, false, true, false, true, false, false], [0, 7, 7, 7, 7], &[City, City, City, City, City, City, City, Town, Town, Town, Town]),
    (&[true, true, false, false, false, true, true, false, false, true, false], [2, 8, 3, 7, 5], &[Capital, Capital, City, City, City, City, City, City, City, City, Town]),
    (&[false, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false], [8, 8, 7, 8, 3], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, City, City, City, City, City, City, City, Town]),
    (&[false, false, false, false, false, false, false, false, false, false, false, false, false, true], [2, 3, 3, 3, 2], &[Capital, Capital, City, City, City, Town, Town, Town, Village, Village, Village, Hamlet, Hamlet, Hamlet]),
    (&[false, true, false, false, true, false, true, false, true, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true, false, false, false], [8, 1, 8, 6, 1], &[Capital, Capital, Capital, Capital, Capital, Capital, Capital, Capital, City, Town, Town, Town, Town, Town, Town, Town, Town, Village, Village, Village, Village, Village, Village, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet, Hamlet]),
];

#[test]
fn quota_classifier_matches_the_reference_text() {
    assert!(CASES.len() >= 20, "fixture empty");
    for (i, (capital_of, want, expect)) in CASES.iter().enumerate() {
        let mut q = *want;
        let got: Vec<SettlementKind> = capital_of.iter().map(|&c| civ_quota_tier(&mut q, c)).collect();
        assert_eq!(got.as_slice(), *expect, "case {i}: capital_of {capital_of:?} want {want:?}");
    }
}
