//! GENERATED by `tools/civ_tier_feedback_capture.js` -- do not hand-edit.
//!
//! Golden parity for `_civIterativeAutoWorld`'s centrality -> tier feedback
//! (reference v2.11 lines 26109-26121) and the `_civNetworkMetrics`
//! betweenness it reads (22421-22486): the reference's own source text, sliced
//! from the frozen snapshot and run under Node over 20 synthetic graphs
//! (a star, a path, a single place, a pair, K5, a multi-component graph with a
//! duplicate, a self pair, an out-of-range pair, an isolated metropolis, and
//! 14 seeded random graphs of 8-30 places). Betweenness is compared bit for
//! bit, tiers exactly. The harness refuses to emit unless the fixtures reach a
//! promotion, a demotion, a capital demoted, a metropolis left alone, and a
//! ratio within 0.05 of each threshold.

use cartalith_civ::SettlementKind as K;

fn place(kind: K) -> cartalith_civ::SettlementPlacement {
    cartalith_civ::SettlementPlacement { x: 0, y: 0, suit: 0.0, faction: 1, capital: false, kind, coastal: false }
}

fn check(name: &str, before: &[K], pairs: &[(usize, usize)], btw_bits: &[u64], after: &[K]) {
    let btw = cartalith_civ::civ_network_betweenness(before.len(), pairs);
    let got: Vec<u64> = btw.iter().map(|b| b.to_bits()).collect();
    assert_eq!(got, btw_bits, "{name}: betweenness");
    let mut places: Vec<_> = before.iter().map(|&k| place(k)).collect();
    cartalith_civ::civ_centrality_tier_feedback(&mut places, &btw);
    let kinds: Vec<K> = places.iter().map(|p| p.kind).collect();
    assert_eq!(kinds, after, "{name}: tiers");
}

#[test]
fn star() {
    check(
        "star",
        &[K::Hamlet, K::Capital, K::City, K::Town, K::Village, K::Hamlet],
        &[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5)],
        &[0x3ff0000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::Village, K::City, K::Town, K::Village, K::Hamlet, K::Hamlet],
    );
}

#[test]
fn path() {
    check(
        "path",
        &[K::Town, K::Town, K::Town, K::Town, K::Town, K::Town],
        &[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)],
        &[0x0000000000000000, 0x3fd999999999999a, 0x3fe3333333333333, 0x3fe3333333333333, 0x3fd999999999999a, 0x0000000000000000],
        &[K::Village, K::City, K::City, K::City, K::City, K::Village],
    );
}

#[test]
fn single() {
    check(
        "single",
        &[K::Capital],
        &[],
        &[0x0000000000000000],
        &[K::City],
    );
}

#[test]
fn pair() {
    check(
        "pair",
        &[K::City, K::Village],
        &[(0, 1)],
        &[0x0000000000000000, 0x0000000000000000],
        &[K::Town, K::Hamlet],
    );
}

#[test]
fn complete5() {
    check(
        "complete5",
        &[K::Capital, K::Capital, K::Capital, K::Capital, K::Capital],
        &[(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)],
        &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::City, K::City, K::City, K::City, K::City],
    );
}

#[test]
fn components() {
    check(
        "components",
        &[K::City, K::Town, K::Village, K::Hamlet, K::Capital, K::Town, K::Metropolis],
        &[(0, 1), (1, 2), (2, 0), (2, 3), (4, 5), (5, 4), (3, 3), (1, 9)],
        &[0x0000000000000000, 0x0000000000000000, 0x3fc1111111111111, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::Town, K::Village, K::Town, K::Hamlet, K::City, K::Village, K::Metropolis],
    );
}

#[test]
fn random0() {
    check(
        "random0",
        &[K::Town, K::Village, K::Capital, K::Village, K::City, K::Town, K::Village, K::Village, K::Hamlet, K::City, K::Village, K::Hamlet, K::Town, K::City, K::Hamlet, K::Hamlet, K::Hamlet, K::City, K::Hamlet, K::Metropolis, K::City, K::Village, K::Town, K::Town, K::Capital, K::Village],
        &[(8, 15), (23, 9), (2, 2), (9, 2), (2, 1), (3, 22), (1, 0), (24, 0), (2, 14), (14, 0), (14, 13), (6, 1), (24, 25), (16, 4), (20, 4), (13, 11), (3, 0), (17, 12), (10, 1), (5, 2), (18, 7), (19, 13), (7, 5), (18, 19), (9, 2), (15, 15), (15, 16), (15, 12), (18, 8), (22, 9), (4, 1), (22, 2), (24, 6), (13, 7), (8, 1), (12, 8), (11, 3), (2, 25), (21, 3), (25, 6)],
        &[0x3fc5cba987654320, 0x3fdd70a3d70a3d72, 0x3fd31c71c71c71c8, 0x3fc159e26af37c05, 0x3fc0da740da740da, 0x3fa1eb851eb851eb, 0x3fa0c83fb72ea61e, 0x3fa8091a2b3c4d5e, 0x3fd11a2b3c4d5e70, 0x3fb47ae147ae147b, 0x0000000000000000, 0x3f9c71c71c71c71b, 0x3fb47ae147ae147b, 0x3fb6789abcdf0124, 0x3fb3333333333333, 0x3f9d0369d0369d03, 0x3f8b4e81b4e81b4f, 0x0000000000000000, 0x3fb7777777777777, 0x3f93a06d3a06d3a0, 0x0000000000000000, 0x0000000000000000, 0x3fa5555555555554, 0x0000000000000000, 0x3f907f6e5d4c3b2a, 0x3f9c71c71c71c71b],
        &[K::Town, K::Town, K::Capital, K::Village, K::City, K::Village, K::Hamlet, K::Village, K::Hamlet, K::City, K::Hamlet, K::Hamlet, K::Town, K::City, K::Hamlet, K::Hamlet, K::Hamlet, K::Town, K::Hamlet, K::Metropolis, K::Town, K::Hamlet, K::Town, K::Village, K::City, K::Hamlet],
    );
}

#[test]
fn random1() {
    check(
        "random1",
        &[K::Capital, K::Village, K::Village, K::Capital, K::City, K::Village, K::City, K::Village, K::Town, K::Capital, K::City, K::Hamlet, K::Hamlet, K::City, K::Capital, K::Capital, K::Village, K::City, K::Capital, K::Capital],
        &[(14, 5), (4, 2), (13, 8), (8, 1), (16, 7), (1, 9), (12, 7), (11, 5), (18, 12), (15, 8), (5, 14), (1, 0), (15, 2), (9, 5), (5, 13), (2, 1), (17, 1), (5, 0), (19, 14), (3, 1), (7, 5), (10, 2), (6, 1)],
        &[0x3fc4f5853d614f58, 0x3fe08fb823ee08fc, 0x3fcc71c71c71c71c, 0x0000000000000000, 0x0000000000000000, 0x3fe2ce98b3a62cea, 0x0000000000000000, 0x3fd2b6a4ada92b6a, 0x3fbc71c71c71c71c, 0x3fc4f5853d614f58, 0x0000000000000000, 0x0000000000000000, 0x3fbaf286bca1af28, 0x3fb7f405fd017f40, 0x3fbaf286bca1af28, 0x3f91f7047dc11f70, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::Capital, K::Town, K::Village, K::City, K::Town, K::Town, K::Town, K::Village, K::Town, K::Capital, K::Town, K::Hamlet, K::Hamlet, K::City, K::Capital, K::City, K::Hamlet, K::Town, K::City, K::City],
    );
}

#[test]
fn random2() {
    check(
        "random2",
        &[K::Village, K::Village, K::City, K::Town, K::Town, K::City, K::City, K::Hamlet, K::City, K::Town],
        &[(4, 1), (6, 5), (9, 3), (2, 0), (2, 7), (6, 7), (8, 7), (5, 2), (9, 9), (4, 1), (3, 2), (1, 0), (7, 1)],
        &[0x3fba12f684bda12f, 0x3fd097b425ed097b, 0x3fe0e38e38e38e39, 0x3fcc71c71c71c71c, 0x0000000000000000, 0x3faa12f684bda12f, 0x3fa7b425ed097b42, 0x3fdd555555555555, 0x0000000000000000, 0x0000000000000000],
        &[K::Village, K::Village, K::Capital, K::Town, K::Village, K::City, K::City, K::Village, K::Town, K::Village],
    );
}

#[test]
fn random3() {
    check(
        "random3",
        &[K::Town, K::Village, K::City, K::Capital, K::City, K::City, K::Town, K::Town, K::Hamlet, K::Village, K::City, K::Hamlet, K::Hamlet, K::City, K::Hamlet],
        &[(13, 8), (13, 13), (10, 4), (11, 6), (5, 3), (11, 4), (0, 5), (7, 4), (8, 0), (3, 2), (6, 0), (11, 0), (0, 10), (1, 0), (10, 1), (3, 1), (12, 2), (8, 8), (14, 0), (1, 2), (2, 1), (4, 1), (10, 9), (9, 8)],
        &[0x3fe04b04b04b04b0, 0x3fd5735735735735, 0x3fc2492492492492, 0x3fa0e10e10e10e11, 0x3fc6096096096095, 0x3f9fe1fe1fe1fe1f, 0x0000000000000000, 0x0000000000000000, 0x3fc5915915915915, 0x3f96816816816817, 0x3fc1951951951952, 0x3fab31b31b31b31b, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::City, K::Town, K::City, K::City, K::City, K::Town, K::Village, K::Village, K::Hamlet, K::Hamlet, K::City, K::Hamlet, K::Hamlet, K::Town, K::Hamlet],
    );
}

#[test]
fn random4() {
    check(
        "random4",
        &[K::Metropolis, K::Village, K::Village, K::Village, K::City, K::Capital, K::Capital, K::City, K::Village, K::Hamlet, K::City, K::Town, K::Town, K::Hamlet, K::City, K::City, K::City, K::Hamlet, K::Hamlet, K::Village, K::City, K::Town, K::City, K::Town, K::Village, K::Town, K::Town, K::Town],
        &[(22, 19), (11, 27), (13, 15), (12, 14), (6, 4), (8, 6), (7, 6), (14, 26), (0, 0), (9, 8), (19, 8), (26, 18), (25, 2), (12, 2), (5, 1), (19, 22), (6, 14), (17, 15), (2, 1), (23, 11), (18, 24), (16, 18), (24, 14), (4, 26), (22, 0), (27, 23), (14, 13), (5, 20), (18, 2), (3, 0), (12, 8), (22, 19), (21, 3), (6, 9), (17, 8), (27, 12), (23, 26), (19, 18), (20, 13), (16, 9), (19, 17), (10, 7), (16, 4), (9, 4), (15, 13), (1, 0), (2, 9), (4, 8), (4, 0), (18, 6), (13, 10), (12, 10), (11, 5)],
        &[0x3fc7d7a3673fef42, 0x3fbc963b2acf1eb9, 0x3fc3417ff21217a6, 0x3fb2f684bda12f68, 0x3fc40695beb14069, 0x3fb22c3f35ba781a, 0x3fb9103bae659104, 0x3f85f3264ed6b488, 0x3fbd39d39d39d39e, 0x3fa27a570dbcb5dd, 0x3fa1d839f56672d9, 0x3f9756cac201756d, 0x3fc321dcc877321d, 0x3fb78ece423978ee, 0x3fbac8c8fe5701e3, 0x3f9564e4872c00f9, 0x3f7908acfc96e5e0, 0x3fa7250088ec1cfb, 0x3fbe8c6d847976fe, 0x3fb2152152152152, 0x3fa123bce679123c, 0x0000000000000000, 0x3f98018018018017, 0x3f9eec997441eec9, 0x3f73e26d8f24cc60, 0x0000000000000000, 0x3fb7f216d593463d, 0x3fa30f69da2bdba0],
        &[K::Metropolis, K::Village, K::Town, K::Village, K::Capital, K::Capital, K::Capital, K::Town, K::Village, K::Hamlet, K::City, K::Town, K::City, K::Hamlet, K::City, K::City, K::Town, K::Hamlet, K::Hamlet, K::Village, K::City, K::Village, K::City, K::Town, K::Hamlet, K::Village, K::Town, K::Town],
    );
}

#[test]
fn random5() {
    check(
        "random5",
        &[K::Town, K::Capital, K::Town, K::City, K::Hamlet, K::Capital, K::Capital, K::Capital, K::Town, K::Metropolis, K::Village, K::Hamlet, K::Town, K::Hamlet, K::Capital, K::Capital, K::Metropolis, K::Capital, K::Hamlet, K::City, K::Capital, K::City, K::Town, K::Hamlet, K::Capital, K::Village, K::Town, K::City],
        &[(20, 12), (18, 10), (8, 6), (14, 0), (22, 8), (23, 0), (25, 11), (26, 22), (21, 7), (17, 0), (4, 0), (19, 3), (3, 1), (11, 8), (13, 5), (1, 0), (2, 1), (15, 4), (9, 3), (27, 6), (10, 2), (16, 12), (6, 1), (5, 0), (17, 14), (8, 25), (7, 4), (24, 1), (12, 2)],
        &[0x3fe1526a7bfd1527, 0x3fe8578578578578, 0x3fd526a7bfd1526a, 0x3fc2992992992993, 0x3fcafc5a7051afc6, 0x3fb2f684bda12f68, 0x3fd7e2d3828d7e2d, 0x3fb2f684bda12f68, 0x3fd1811811811812, 0x0000000000000000, 0x3fb2f684bda12f68, 0x0000000000000000, 0x3fc2992992992993, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3fb2f684bda12f68, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::City, K::Capital, K::Town, K::City, K::Hamlet, K::Capital, K::Capital, K::Capital, K::Town, K::Metropolis, K::Village, K::Hamlet, K::Town, K::Hamlet, K::City, K::City, K::Metropolis, K::City, K::Hamlet, K::Town, K::City, K::Town, K::Town, K::Hamlet, K::City, K::Hamlet, K::Village, K::Town],
    );
}

#[test]
fn random6() {
    check(
        "random6",
        &[K::Hamlet, K::Metropolis, K::City, K::Town, K::Hamlet, K::Capital, K::Village, K::Town, K::Hamlet],
        &[(1, 0), (6, 4), (8, 7), (0, 3), (5, 1), (4, 0), (7, 1), (7, 4), (3, 1), (2, 0)],
        &[0x3fd9249249249249, 0x3fd9249249249249, 0x0000000000000000, 0x0000000000000000, 0x3fd4924924924925, 0x0000000000000000, 0x0000000000000000, 0x3fd4924924924925, 0x0000000000000000],
        &[K::Village, K::Metropolis, K::Town, K::Village, K::Village, K::City, K::Hamlet, K::City, K::Hamlet],
    );
}

#[test]
fn random7() {
    check(
        "random7",
        &[K::Capital, K::Hamlet, K::Town, K::Hamlet, K::City, K::Town, K::Town, K::Town, K::City],
        &[(8, 0), (1, 0), (5, 1), (1, 8), (1, 4), (6, 3), (2, 0), (7, 6), (8, 0), (4, 2), (3, 2), (2, 1), (0, 1), (3, 0)],
        &[0x3fcdb6db6db6db6e, 0x3fd4924924924925, 0x3fcdb6db6db6db6e, 0x3fdb6db6db6db6db, 0x0000000000000000, 0x0000000000000000, 0x3fd0000000000000, 0x0000000000000000, 0x0000000000000000],
        &[K::Capital, K::Village, K::Town, K::Village, K::Town, K::Village, K::Town, K::Village, K::Town],
    );
}

#[test]
fn random8() {
    check(
        "random8",
        &[K::Town, K::Capital, K::Village, K::Hamlet, K::Hamlet, K::Capital, K::Capital, K::Town, K::Metropolis, K::Hamlet, K::Hamlet, K::Metropolis, K::Hamlet, K::Town, K::Village, K::Hamlet],
        &[(12, 1), (14, 7), (5, 3), (8, 5), (12, 6), (13, 13), (8, 5), (13, 2), (15, 2), (8, 3), (10, 1), (8, 12), (3, 4), (1, 0), (5, 2), (2, 1), (14, 2), (6, 3), (11, 10), (4, 0), (5, 11), (9, 7), (6, 15), (10, 3), (3, 0), (7, 0)],
        &[0x3fc9659659659659, 0x3fc4ed4ed4ed4ed4, 0x3fd3193193193192, 0x3fceadeadeadeade, 0x0000000000000000, 0x3fc27d27d27d27d2, 0x3faad1ad1ad1ad1b, 0x3fc41d41d41d41d4, 0x3f96c16c16c16c16, 0x0000000000000000, 0x3fa9319319319318, 0x3f73813813813814, 0x3f9ba1ba1ba1ba1b, 0x0000000000000000, 0x3fb2492492492492, 0x3f9d41d41d41d41d],
        &[K::City, K::Capital, K::Town, K::Village, K::Hamlet, K::Capital, K::Capital, K::Town, K::Metropolis, K::Hamlet, K::Hamlet, K::Metropolis, K::Hamlet, K::Village, K::Village, K::Hamlet],
    );
}

#[test]
fn random9() {
    check(
        "random9",
        &[K::Hamlet, K::Hamlet, K::City, K::Capital, K::Town, K::Town, K::City, K::City, K::Village, K::Capital, K::Town, K::Town, K::Hamlet, K::Capital, K::Capital, K::Town, K::Town, K::City, K::Village, K::Town, K::City, K::Capital, K::City, K::Town, K::City, K::Capital, K::Village],
        &[(13, 6), (11, 4), (4, 3), (26, 16), (11, 16), (8, 5), (1, 0), (2, 1), (15, 7), (17, 8), (20, 0), (24, 0), (21, 20), (5, 2), (3, 1), (18, 9), (9, 2), (10, 7), (14, 12), (7, 1), (6, 26), (22, 12), (23, 2), (21, 7), (25, 6), (12, 8), (6, 5), (19, 11), (16, 14)],
        &[0x3fc1b91b91b91b92, 0x3fe025cf29bf68c3, 0x3fdeb851eb851eb8, 0x3fc3b13b13b13b14, 0x3fc08aa243bdd577, 0x3fd967300c9a6340, 0x3fcbf68c359025cf, 0x3fcb2ce601934c68, 0x3fca633fcd967301, 0x3fb3b13b13b13b14, 0x0000000000000000, 0x3fc3b13b13b13b14, 0x3fc0ef755dbc422b, 0x0000000000000000, 0x3fac5b5f4f8e9283, 0x0000000000000000, 0x3fc025cf29bf68c3, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3f7934c67f9b2ce6, 0x3f82e794dfb461ad, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3fb1544877baaede],
        &[K::Hamlet, K::Village, K::Capital, K::Capital, K::Town, K::City, K::City, K::City, K::Village, K::Capital, K::Village, K::Town, K::Hamlet, K::City, K::Capital, K::Village, K::Town, K::Town, K::Hamlet, K::Village, K::Town, K::City, K::Town, K::Village, K::Town, K::City, K::Village],
    );
}

#[test]
fn random10() {
    check(
        "random10",
        &[K::City, K::Village, K::City, K::Capital, K::Hamlet, K::Hamlet, K::Hamlet, K::Village, K::Capital, K::Capital, K::Capital, K::Hamlet, K::Hamlet, K::Capital, K::Capital, K::Town, K::Town, K::City, K::Hamlet, K::Metropolis, K::City, K::City, K::Hamlet, K::City, K::Hamlet, K::City, K::Hamlet, K::Capital],
        &[(3, 3), (24, 27), (16, 19), (7, 5), (27, 9), (11, 8), (23, 3), (3, 0), (4, 0), (20, 12), (6, 4), (20, 1), (13, 1), (24, 14), (10, 8), (8, 18), (5, 1), (3, 10), (10, 26), (12, 21), (9, 3), (12, 9), (22, 12), (6, 7), (26, 15), (23, 23), (10, 5), (1, 0), (8, 4), (18, 15), (9, 8), (22, 5), (23, 7), (19, 10), (17, 12), (2, 1), (14, 0), (15, 8), (23, 22), (25, 21), (16, 0), (21, 19)],
        &[0x3fca87a87a87a879, 0x3fc9315a3214e86a, 0x0000000000000000, 0x3fba4e16a886fa36, 0x3fb90a74357c3b54, 0x3fc1222e94b06778, 0x3f8e25708fec8d04, 0x3fa1049e82cbbaf4, 0x3fcf78a234cdf78b, 0x3fc8818818818817, 0x3fc860db630b860f, 0x0000000000000000, 0x3fca58fae503a590, 0x0000000000000000, 0x3fa42db4a2669831, 0x3f8836d8c2e1836e, 0x3f9e25708fec8d01, 0x0000000000000000, 0x0000000000000000, 0x3fb42a97fed542a8, 0x3fa79507895c23fa, 0x3fb84ca13bdada1f, 0x3fa7ec296d417ec2, 0x3fa049e82cbbaf49, 0x3f884fbddf6c2fa6, 0x0000000000000000, 0x3f8c338a5517188f, 0x3fa4e86af876a3dc],
        &[K::Capital, K::Town, K::Town, K::Capital, K::Hamlet, K::Hamlet, K::Hamlet, K::Village, K::Capital, K::Capital, K::Capital, K::Hamlet, K::Village, K::City, K::Capital, K::Village, K::Town, K::Town, K::Hamlet, K::Metropolis, K::City, K::City, K::Hamlet, K::City, K::Hamlet, K::Town, K::Hamlet, K::Capital],
    );
}

#[test]
fn random11() {
    check(
        "random11",
        &[K::Town, K::Village, K::Town, K::Hamlet, K::Hamlet, K::Hamlet, K::Hamlet, K::Village, K::City],
        &[(2, 8), (5, 7), (2, 0), (5, 2), (1, 0), (0, 7), (4, 1), (0, 6), (6, 0), (0, 6), (7, 0), (0, 1), (3, 0), (8, 4), (6, 5), (2, 2)],
        &[0x3fe1b6db6db6db6e, 0x3fc2492492492492, 0x3fd0000000000000, 0x0000000000000000, 0x3fa2492492492492, 0x3fb6db6db6db6db7, 0x3fa2492492492492, 0x3fa2492492492492, 0x3fb2492492492492],
        &[K::City, K::Village, K::Town, K::Hamlet, K::Hamlet, K::Hamlet, K::Hamlet, K::Hamlet, K::City],
    );
}

#[test]
fn random12() {
    check(
        "random12",
        &[K::Hamlet, K::Hamlet, K::Town, K::Town, K::Hamlet, K::Village, K::Capital, K::Capital, K::City, K::Village, K::Hamlet, K::Town, K::Capital, K::Hamlet, K::Village, K::Capital, K::Town, K::Metropolis, K::Capital, K::Village, K::Capital, K::Village, K::City, K::City, K::City, K::Town, K::City, K::Capital, K::Village],
        &[(15, 21), (21, 7), (28, 16), (1, 0), (16, 1), (27, 21), (11, 3), (12, 10), (24, 1), (11, 1), (10, 8), (3, 1), (17, 7), (17, 15), (26, 12), (8, 0), (19, 5), (19, 25), (21, 11), (28, 10), (21, 23), (9, 24), (4, 1), (6, 16), (20, 4), (6, 4), (1, 4), (13, 8), (18, 3), (27, 2), (22, 17), (9, 8), (13, 13), (12, 9), (16, 6), (26, 22), (28, 10), (13, 11), (15, 12), (12, 13), (24, 22), (11, 27), (5, 3), (25, 1), (8, 14), (19, 4), (14, 3), (2, 0), (7, 5), (28, 0), (23, 22), (17, 9), (5, 21), (28, 7), (27, 20), (6, 2)],
        &[0x3fb32da090e47bff, 0x3fcf12acc3db23f8, 0x3fa0cd17a77d2d53, 0x3fbfc63546e2a70c, 0x3faffd1c438b5525, 0x3fb3d220b043e7cd, 0x3f8ef90c028744e6, 0x3fb2df206683054f, 0x3fb3ed0747a69836, 0x3fa9afc0e9180cc3, 0x3fa0319acdd2ca36, 0x3fbe28a6f1602fbf, 0x3fb2ea68e4dcdd62, 0x3fa686878fc0c5dd, 0x3f91282ef4b667d8, 0x3fa0a6fa2e9ed9ad, 0x3fa43a2730abee4d, 0x3fa546bf6d519570, 0x0000000000000000, 0x3f9a69a69a69a69a, 0x3f7a2fdbe14c4da9, 0x3fc335ad4272a112, 0x3fad3c0ca4587e6b, 0x3f9195fcee07c40b, 0x3fb5a38f0c3df8b3, 0x3f82b12b12b12b12, 0x3f84c4da868bf6f8, 0x3fb32de7045d4f50, 0x3fb18bdfda6f6e13],
        &[K::Hamlet, K::Village, K::Town, K::Town, K::Hamlet, K::Village, K::City, K::Capital, K::City, K::Village, K::Hamlet, K::Town, K::Capital, K::Hamlet, K::Hamlet, K::Capital, K::Town, K::Metropolis, K::City, K::Village, K::City, K::Village, K::City, K::Town, K::City, K::Village, K::Town, K::Capital, K::Village],
    );
}

#[test]
fn random13() {
    check(
        "random13",
        &[K::Town, K::City, K::Town, K::Village, K::Hamlet, K::Village, K::Town, K::Capital],
        &[(3, 6), (7, 3), (4, 3), (7, 3), (5, 4), (5, 4), (7, 4), (1, 0), (3, 5), (2, 1), (3, 0), (6, 1)],
        &[0x3fc8618618618618, 0x3fd3cf3cf3cf3cf4, 0x0000000000000000, 0x3fe3cf3cf3cf3cf4, 0x3f98618618618618, 0x0000000000000000, 0x3fc8618618618618, 0x0000000000000000],
        &[K::Town, K::City, K::Village, K::Town, K::Hamlet, K::Hamlet, K::Town, K::City],
    );
}
