//! GENERATED by the milestone-4 golden capture -- do not hand-edit.
//!
//! Every value below is the reference engine's own output. All eight of
//! milestone 4's items are on `UME`'s **public** export (not just `_test`), so
//! this milestone needs no indirection at all: `CULTURE_PROFILES`,
//! `resolveProfile`, `DEFAULT_RULES`, `resolveRules`, `cloneRules`,
//! `applyWildness` and `applyPlotChaos` are called directly, and `clamp` is
//! observed through the two that use it.
//!
//! Rule sets are flattened into one canonical field order, mirrored exactly by
//! `Rules::flatten` on the Rust side. The capture asserts the reference's own
//! objects carry exactly that key set in exactly that order, so a rule added
//! upstream cannot silently drop out of the comparison.

/// The canonical flattening order, as the capture asserted it off the
/// reference's own `DEFAULT_RULES`.
pub static FIELDS: &[&str] = &[
    "branchAngleJitter",
    "continuationJitter",
    "explorationStart",
    "explorationDecay",
    "explorationMinimum",
    "segmentLengthMedian",
    "segmentLengthVariance",
    "pierceChance",
    "junctionAngleLimit",
    "marketGradientDecay",
    "parallelStreetSpacing",
    "deadEndBias",
    "bridgeheadDistance",
    "bridgeheadProbability",
    "frontageWidthVariance",
    "plotDepthVariance",
    "subdivisionCap",
    "wallGenerationThreshold",
    "wallGenerationMinAgeGap",
    "wallGenerationExtramuralShare",
    "maxWallGenerations",
    "carryingCapacityWeight",
    "wildness",
    "plotChaos",
];

pub struct RuleCase {
    pub name: &'static str,
    pub values: &'static [f64],
}

pub static RULES: &[RuleCase] = &[
    RuleCase { name: "defaults", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "cloned", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveNull", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveUndefined", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveEmpty", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveOneField", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.5, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveWholeStreetGroupPartial", values: &[1.5, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.4, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveTwoGroups", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 4.0, 0.8, 120.0, 0.15, 1.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveMeta", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.3, 1.9] },
    RuleCase { name: "resolveUnknownGroup", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.02, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveFalsyGroups", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "resolveAllGroups", values: &[0.01, 0.02, 0.03, 0.04, 0.05, 6.0, 0.07, 0.08, 0.09, 10.0, 11.0, 0.12, 13.0, 0.14, 0.15, 0.16, 17.0, 0.18, 19.0, 0.2, 21.0, 0.22, 0.23, 0.24] },
    RuleCase { name: "defaultsAfterMerges", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "wild_0", values: &[0.15, 0.1, 0.2, 0.05, 0.05, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.1, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.0, 1.0] },
    RuleCase { name: "wild_0p25", values: &[0.15, 0.1, 0.2, 0.05, 0.05, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.1, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.25, 1.0] },
    RuleCase { name: "wild_0p5", values: &[0.15, 0.11, 0.275, 0.05, 0.06, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.175, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.5, 1.0] },
    RuleCase { name: "wild_0p75", values: &[0.195, 0.165, 0.41250000000000003, 0.05, 0.09, 56.0, 0.375, 0.125, 0.52, 200.0, 30.0, 0.0, 190.0, 0.26249999999999996, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.75, 1.0] },
    RuleCase { name: "wild_1", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "wild_1p25", values: &[0.325, 0.275, 0.6875, 0.05, 0.15, 56.0, 0.625, 0.07500000000000001, 0.33, 200.0, 18.0, 0.0375, 190.0, 0.4375, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.25, 1.0] },
    RuleCase { name: "wild_1p5", values: &[0.39, 0.33, 0.8250000000000001, 0.05, 0.18, 56.0, 0.75, 0.05, 0.22, 200.0, 12.0, 0.075, 190.0, 0.5249999999999999, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.5, 1.0] },
    RuleCase { name: "wild_1p75", values: &[0.455, 0.385, 0.9, 0.05, 0.21, 56.0, 0.875, 0.025, 0.14, 200.0, 10.0, 0.11249999999999999, 190.0, 0.6124999999999999, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.75, 1.0] },
    RuleCase { name: "wild_2", values: &[0.52, 0.44, 0.9, 0.05, 0.24, 56.0, 1.0, 0.0, 0.14, 200.0, 10.0, 0.15, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 2.0, 1.0] },
    RuleCase { name: "wild_2p5", values: &[0.65, 0.5, 0.9, 0.05, 0.3, 56.0, 1.1, 0.0, 0.14, 200.0, 10.0, 0.22499999999999998, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 2.5, 1.0] },
    RuleCase { name: "wild_3", values: &[0.7, 0.5, 0.9, 0.05, 0.3, 56.0, 1.1, 0.0, 0.14, 200.0, 10.0, 0.3, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 3.0, 1.0] },
    RuleCase { name: "wild_neg1", values: &[0.15, 0.1, 0.2, 0.05, 0.05, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.1, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, -1.0, 1.0] },
    RuleCase { name: "wild_NaN", values: &[f64::NAN, f64::NAN, f64::NAN, 0.05, f64::NAN, 56.0, f64::NAN, f64::NAN, f64::NAN, 200.0, f64::NAN, f64::NAN, 190.0, f64::NAN, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, f64::NAN, 1.0] },
    RuleCase { name: "wild_Infinity", values: &[0.7, 0.5, 0.9, 0.05, 0.3, 56.0, 1.1, 0.0, 0.14, 200.0, 10.0, 0.4, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, f64::INFINITY, 1.0] },
    RuleCase { name: "wild_negInfinity", values: &[0.15, 0.1, 0.2, 0.05, 0.05, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.1, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, f64::NEG_INFINITY, 1.0] },
    RuleCase { name: "wildTwice1p5", values: &[0.39, 0.33, 0.8250000000000001, 0.05, 0.18, 56.0, 0.75, 0.05, 0.22, 200.0, 12.0, 0.15, 190.0, 0.5249999999999999, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.5, 1.0] },
    RuleCase { name: "wildThrice2", values: &[0.52, 0.44, 0.9, 0.05, 0.24, 56.0, 1.0, 0.0, 0.14, 200.0, 10.0, 0.4, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 2.0, 1.0] },
    RuleCase { name: "wildFive2", values: &[0.52, 0.44, 0.9, 0.05, 0.24, 56.0, 1.0, 0.0, 0.14, 200.0, 10.0, 0.4, 190.0, 0.7, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 2.0, 1.0] },
    RuleCase { name: "wildOverCustom", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 999.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.3, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "chaos_0", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.1, 0.1, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 0.0] },
    RuleCase { name: "chaos_0p4", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.1, 0.11200000000000002, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 0.4] },
    RuleCase { name: "chaos_0p5", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.11, 0.14, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 0.5] },
    RuleCase { name: "chaos_0p7475", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.16445, 0.20930000000000004, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 0.7475] },
    RuleCase { name: "chaos_0p75", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.165, 0.21000000000000002, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 0.75] },
    RuleCase { name: "chaos_1", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.22, 0.28, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.0] },
    RuleCase { name: "chaos_1p2475", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.27445, 0.34930000000000005, 2.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.2475] },
    RuleCase { name: "chaos_1p25", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.275, 0.35000000000000003, 3.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.25] },
    RuleCase { name: "chaos_1p5", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.33, 0.42000000000000004, 3.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.5] },
    RuleCase { name: "chaos_1p7475", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.38445, 0.48930000000000007, 3.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.7475] },
    RuleCase { name: "chaos_1p75", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.385, 0.49000000000000005, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.75] },
    RuleCase { name: "chaos_2", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.44, 0.56, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 2.0] },
    RuleCase { name: "chaos_2p2", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.48400000000000004, 0.6, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 2.2] },
    RuleCase { name: "chaos_3", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.5, 0.6, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 3.0] },
    RuleCase { name: "chaos_neg1", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.1, 0.1, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, -1.0] },
    RuleCase { name: "chaos_NaN", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, f64::NAN, f64::NAN, f64::NAN, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, f64::NAN] },
    RuleCase { name: "chaos_Infinity", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.5, 0.6, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, f64::INFINITY] },
    RuleCase { name: "chaosTwice1p25", values: &[0.26, 0.22, 0.55, 0.05, 0.12, 56.0, 0.5, 0.1, 0.44, 200.0, 24.0, 0.0, 190.0, 0.35, 0.275, 0.35000000000000003, 3.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.0, 1.25] },
    RuleCase { name: "wildThenChaos", values: &[0.41600000000000004, 0.35200000000000004, 0.8800000000000001, 0.05, 0.192, 56.0, 0.8, 0.039999999999999994, 0.17599999999999996, 200.0, 10.0, 0.09000000000000001, 190.0, 0.5599999999999999, 0.132, 0.168, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.6, 0.6] },
    RuleCase { name: "chaosThenWild", values: &[0.41600000000000004, 0.35200000000000004, 0.8800000000000001, 0.05, 0.192, 56.0, 0.8, 0.039999999999999994, 0.17599999999999996, 200.0, 10.0, 0.09000000000000001, 190.0, 0.5599999999999999, 0.132, 0.168, 1.0, 0.8, 120.0, 0.15, 3.0, 1.0, 1.6, 0.6] },
    RuleCase { name: "mergeThenBoth", values: &[0.15, 0.11, 0.275, 0.05, 0.06, 56.0, 0.25, 0.15, 0.52, 200.0, 30.0, 0.0, 190.0, 0.175, 0.396, 0.5040000000000001, 4.0, 0.8, 120.0, 0.15, 3.0, 1.0, 0.5, 1.8] },
];

pub struct ProfileCase {
    pub key: &'static str,
    pub id: &'static str,
    pub name: &'static str,
    pub planning: &'static str,
    pub parcel_pattern: &'static str,
    pub building_grammar: &'static str,
    pub default_faith: &'static str,
    pub default_civic: &'static str,
    pub markets: bool,
    pub wall_gates_scheme: &'static str,
    pub orientation: &'static str,
    pub civic_anchor_label: &'static str,
    /// `None` where the reference leaves the key off the object entirely.
    pub default_walls: Option<bool>,
    /// Absent on `medieval`, so `profile.waterway` is `undefined` there and the
    /// engine's truthiness test reads it as `false`.
    pub waterway: bool,
    pub prov: &'static str,
    /// The reference object's own key list, in its own order.
    pub keys: &'static [&'static str],
}

pub static PROFILES: &[ProfileCase] = &[
    ProfileCase {
        key: "medieval",
        id: "medieval",
        name: "Organic Growth (Medieval Western European)",
        planning: "organic",
        parcel_pattern: "strip",
        building_grammar: "burgage",
        default_faith: "church",
        default_civic: "auto",
        markets: true,
        wall_gates_scheme: "organic",
        orientation: "terrain",
        civic_anchor_label: "market",
        default_walls: None,
        waterway: false,
        prov: "Accretive growth over centuries: epoch-looped organic streets, series-platted burgage strip parcels, a parish church per few thousand souls, market squares that specialise with rank (docs/01 §1.1; docs/03 M-* register). Presented as the general \"Organic Growth\" pattern rather than one culture among many: a post-launch review across this register's original 19 profiles found every other organic-planning culture (Islamic, Byzantine, Chinese, Aztec, Viking, Celtic, Greek, Egyptian, Mesopotamian, Mayan, Inca, Japanese, Colonial, Frontier, Industrial, Palimpsest) rendering near-indistinguishably from this one at the level this tool actually draws — a rendering/visual-distinctiveness problem, not a defect in their underlying research, which remains valid and citable but is no longer separately modelled here (docs/07 §3.10). Kept as this pattern's concrete, best-attested reference point, alongside the radial Venus Project as the one structurally distinct alternative.",
        keys: &["id", "name", "planning", "parcelPattern", "buildingGrammar", "defaultFaith", "defaultCivic", "markets", "wallGates", "orientation", "civicAnchorLabel", "prov"],
    },
    ProfileCase {
        key: "venus",
        id: "venus",
        name: "The Venus Project (resource-based circular city)",
        planning: "radial",
        parcel_pattern: "strip",
        building_grammar: "venus-mixed",
        default_faith: "none",
        default_civic: "dome",
        markets: true,
        wall_gates_scheme: "organic",
        orientation: "radial",
        civic_anchor_label: "Center for Resource Management",
        default_walls: Some(false),
        waterway: true,
        prov: "Jacque Fresco's Venus Project circular city (thevenusproject.com/resource-based-economy/environment/circular-city), taken here as a deliberate design fusion rather than a literal reconstruction: several concentric ring streets at regular intervals connected by radial spokes (with extra cross-spokes in the wider outer band) to a domed central hub, the Center for Resource Management (M-VEN-2) — a genuinely new radial planning mode (M-VEN-1), not a re-skin of the grid or organic models, using the shape-aware bisector parcel method rather than the bounding-box-based insula method since the wedge-shaped ring blocks need lot boundaries that respect the true (curved) block outline. Per the brief, the clean circular geometry is mixed with the lived-in amenity richness of medieval-European and Asian/Japanese towns (M-VEN-5): circular pavilions cluster at the hub and inner rings, the residential rings blend the standardized modular apartment with Asian courtyard houses and Japanese machiya rowhouses, market/amenity squares scale with rank, and the outermost ring carries the logistics warehouses. Fortification is optional and off by default (defaultWalls:false — the UI unchecks the wall box on selecting this profile), but the medieval curtain wall and the bastioned star fort are both available on request (wallGates.scheme:'organic', so the anachronism guard permits the trace). A circular irrigation waterway (M-VEN-3) encircles the built city: when the star fort is built the canal supplies its wet moat around the bastions even on a landlocked site, otherwise it is the irrigation ring outside the (optional) curtain wall — drawn as a fully-closed circle capped to the map so it never terminates in a straight clipped edge. The concentric rings and spokes carry a seeded low-frequency wobble (post-review organic softening, M-VEN-1) so the radial skeleton reads as hand-drawn rather than compass-drawn, consistent with this tool's own hand-drawn-cadastral aesthetic.",
        keys: &["id", "name", "planning", "parcelPattern", "buildingGrammar", "defaultFaith", "defaultCivic", "markets", "wallGates", "orientation", "civicAnchorLabel", "defaultWalls", "waterway", "prov"],
    },
];

pub struct ResolveCase {
    pub id: &'static str,
    /// Whether the reference returned something that is actually a profile.
    pub is_profile: bool,
    pub got: Option<&'static str>,
    pub type_of: &'static str,
}

pub static RESOLVE_PROFILE: &[ResolveCase] = &[
    ResolveCase { id: "medieval", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "venus", is_profile: true, got: Some("venus"), type_of: "object" },
    ResolveCase { id: "", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "roman", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "MEDIEVAL", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "Venus", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "grid", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "palimpsest", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "toString", is_profile: false, got: None, type_of: "function" },
    ResolveCase { id: "constructor", is_profile: false, got: None, type_of: "function" },
    ResolveCase { id: "__proto__", is_profile: false, got: None, type_of: "object" },
    ResolveCase { id: "valueOf", is_profile: false, got: None, type_of: "function" },
    ResolveCase { id: "hasOwnProperty", is_profile: false, got: None, type_of: "function" },
    ResolveCase { id: "null", is_profile: true, got: Some("medieval"), type_of: "object" },
    ResolveCase { id: "undefined", is_profile: true, got: Some("medieval"), type_of: "object" },
];

/// `cloneRules` is `JSON.parse(JSON.stringify(r))`, so a NaN-poisoned rule set
/// comes back with `null` where the NaN was. Captured as a number-or-null:
/// `None` means the reference produced JSON `null`.
pub static CLONE_NAN_BECOMES: Option<f64> = None;
