//! **EF-9.1** -- per-tile *importance*: how much a pyramid tile would gain
//! from being drawn one level deeper
//! (`ELEVATION_FIELD_ARCHITECTURE_RESEARCH.md` §8.3, milestone EF-9.1).
//!
//! This module decides **nothing about what is drawn**. It reads a world's
//! already-computed rasters, aggregates them over one tile's footprint, and
//! scores the tile with weights that were **fitted by measurement** against
//! the refinement gain EF-9.0 measured (`G_scr`, the on-screen RMS difference
//! between a tile and its parent's bilinear resample). EF-9.2 will turn a
//! score into a subdivision choice; EF-9.1 only supplies the score.
//!
//! # The four invariants this module is written against (§8.2)
//!
//! * **I1** -- importance changes *which level* and *when*, never the content
//!   of a tile at a given `(z, col, row)`. Nothing here synthesises a texel.
//! * **I2** -- importance never moves a river threshold. No hydrology
//!   constant is read or written here.
//! * It is a **pure addition**: no generation code calls it, no golden covers
//!   it, and no generated byte depends on it.
//!
//! # What is fitted, and what is deliberately not
//!
//! The *geometric* terms ([`FEATURE_NAMES`]) predict how much new structure a
//! deeper level adds; the harness `crates/cartalith-civ/tests/ef9_refinement_gain.rs`
//! fits them (see [`FITTED_WEIGHTS`] for the exact command, seeds and the
//! held-out score). **Settlement and road terms are not fitted**: EF-9.0
//! measured Spearman rho 0.015 (settlements) and 0.11 (way length) against
//! `G_scr`, i.e. they do not predict geometric gain, they express what the
//! owner cares about. They enter only as a [`PolicyInputs`] bias that raises
//! synthesis *order* (Q2's default) and is structurally unable to touch
//! [`Importance::score`]: it is a different type, returned by a different
//! function, and never added to anything.
//!
//! # Absent is not zero
//!
//! Every input is an `Option` (`MISTAKES.md`: *never encode "no value" as a
//! plausible value*). A world without `stream_order` (carve-rivers off) or
//! with an empty `boundary_type` / `volcanic_field` (a `Loaded` save lacks the
//! tectonic-substrate grids, `cartalith-godot`'s `CivData` doc) yields `None`
//! for those terms, [`importance`] reports them [`TermState::Missing`], and
//! the score is summed over the terms that *are* present. A missing term is
//! skipped; it is never scored as order 0 or as "no boundary here".
//! **Consequence the caller must respect:** scores from two worlds that use
//! different term sets are not comparable with each other; within one world
//! every tile sees the same term set, so ranking tiles of one world is sound.

use cartalith_spatial::FloatRegion;
use cartalith_terrain::analysis;

/// Number of fitted geometric inputs.
pub const N_FEATURES: usize = 8;

/// Names of the fitted inputs, in the order every array in this module uses
/// ([`TileImportanceInputs::as_array`], [`ImportanceWeights::terms`],
/// [`Importance::terms_used`]) and in the order of the first eight entries of
/// EF-9.0's harness `INPUTS` table. Settlement and way length are not here:
/// they are [`PolicyInputs`], not fitted terms.
pub const FEATURE_NAMES: [&str; N_FEATURES] = [
    "slope_mean",
    "slope_max",
    "abs_curv_mean",
    "abs_tpi_mean",
    "stream_order_max",
    "land_fraction",
    "boundary_fraction",
    "volcanic_max",
];

/// Landmark fine scale in km: `cartalith-civ`'s `landmark.rs::SCALE_FINE_KM`
/// (3.0), the radius EF-9.0 §8.3 names for the `|tpi|` input. Restated
/// because that constant is private there and `cartalith-engine` cannot
/// depend on `cartalith-civ`; EF-9.0's harness asserts nothing against it, so
/// a change over there would not be caught here -- it is a copied constant,
/// labelled as one.
const TPI_FINE_KM: f64 = 3.0;
/// `landmark.rs::SCALE_MIN_CELLS` / `SCALE_MAX_CELLS`: the cell-radius clamp it
/// applies to [`TPI_FINE_KM`]. Copied for the same reason.
const TPI_MIN_CELLS: i64 = 2;
/// See [`TPI_MIN_CELLS`].
const TPI_MAX_CELLS: i64 = 40;
/// Curvature smoothing passed to `analysis::curvature_at`: EF-9.0 §8.3's
/// `|curvature_at(smooth = 2)|`. The raw one-cell Laplacian "should not be
/// thresholded directly on a noisy field" (that function's own doc).
const CURVATURE_SMOOTH: i64 = 2;

// ------------------------------------------------------------------ inputs

/// One tile's inputs, every one an `Option`: `None` means **the world does not
/// carry that field**, never "the value is zero".
///
/// Field order is [`FEATURE_NAMES`]. Produced by [`tile_features`]; consumed by
/// [`importance`]. Must never be filled with a default of `0.0` for a field
/// the world lacks -- that is the exact defect `Option` is here to prevent.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct TileImportanceInputs {
    /// Mean of `analysis::slope` over the footprint's coarse cells.
    pub slope_mean: Option<f64>,
    /// Max of the same.
    pub slope_max: Option<f64>,
    /// Mean of `|analysis::curvature_at(.., smooth = 2)|`.
    pub abs_curv_mean: Option<f64>,
    /// Mean of `|analysis::tpi|` at the landmark fine radius.
    pub abs_tpi_mean: Option<f64>,
    /// Max `stream_order` over the footprint; `None` when the world has no
    /// stream order (never order 0).
    pub stream_order_max: Option<f64>,
    /// Fraction of footprint cells strictly above sea level.
    pub land_fraction: Option<f64>,
    /// Fraction of footprint cells whose `boundary_type != 0`; `None` when the
    /// world has no `boundary_type` (a `Loaded` save), never "no boundary".
    pub boundary_fraction: Option<f64>,
    /// Max `volcanic_field` over the footprint; `None` when absent.
    pub volcanic_max: Option<f64>,
}

impl TileImportanceInputs {
    /// The inputs as an array in [`FEATURE_NAMES`] order.
    #[must_use]
    pub fn as_array(&self) -> [Option<f64>; N_FEATURES] {
        [
            self.slope_mean,
            self.slope_max,
            self.abs_curv_mean,
            self.abs_tpi_mean,
            self.stream_order_max,
            self.land_fraction,
            self.boundary_fraction,
            self.volcanic_max,
        ]
    }

    /// Inverse of [`Self::as_array`].
    #[must_use]
    pub fn from_array(a: [Option<f64>; N_FEATURES]) -> Self {
        Self {
            slope_mean: a[0],
            slope_max: a[1],
            abs_curv_mean: a[2],
            abs_tpi_mean: a[3],
            stream_order_max: a[4],
            land_fraction: a[5],
            boundary_fraction: a[6],
            volcanic_max: a[7],
        }
    }
}

/// A world's rasters, prepared once so any number of tiles can be aggregated
/// cheaply. EF-9.4 will cache one of these per world.
///
/// Holds the coarse-grid derivatives (slope, `|curvature|`, `|tpi|`) and a land
/// mask computed from the field at construction, plus the three optional
/// world grids. It owns copies, so it does not borrow the world and a sculpt
/// does not mutate it behind the caller's back (EF-9.5 rebuilds it).
///
/// Must never be built from a grid whose length is not `gw * gh` and then used
/// as if that field were present: [`Self::build`] maps a wrong-length
/// optional grid to `None` instead.
pub struct WorldImportanceField {
    gw: usize,
    gh: usize,
    /// `1` where `field > sea`, else `0`.
    land: Vec<u8>,
    slope: Vec<f32>,
    abs_curv: Vec<f32>,
    abs_tpi: Vec<f32>,
    stream_order: Option<Vec<i16>>,
    boundary: Option<Vec<u8>>,
    volcanic: Option<Vec<f32>>,
}

impl WorldImportanceField {
    /// Builds the aggregation source from a world's rasters.
    ///
    /// * `field` is the `gw * gh` heightmap, `sea` its sea level, `world` and
    ///   `map_km` the wrap flag and map width (`WorldParams::world`,
    ///   `map_width_km`) that fix the TPI radius.
    /// * `stream_order`: `None` when the world has none, and also `None` when
    ///   its length is not `gw * gh`.
    /// * `boundary` / `volcanic`: an **empty slice or any slice not `gw * gh`
    ///   long maps to `None`** -- a `Loaded` save's empty `boundary_type` is
    ///   "not carried", not "no boundaries" (`MISTAKES.md`: never encode "no
    ///   value" as a plausible value).
    ///
    /// # Panics
    /// If `field.len() != gw * gh` (the derivative functions assert it).
    #[must_use]
    #[allow(clippy::too_many_arguments)]
    pub fn build(
        field: &[f32],
        gw: usize,
        gh: usize,
        sea: f64,
        world: bool,
        map_km: f64,
        stream_order: Option<&[i16]>,
        boundary: &[u8],
        volcanic: &[f32],
    ) -> Self {
        let n = gw * gh;
        assert_eq!(field.len(), n, "field must be gw * gh");
        let cell_km = map_km / gw as f64;
        let r_fine = ((TPI_FINE_KM / cell_km).round() as i64).clamp(TPI_MIN_CELLS, TPI_MAX_CELLS);
        let abs = |v: Vec<f32>| v.into_iter().map(f32::abs).collect::<Vec<_>>();
        Self {
            gw,
            gh,
            land: field.iter().map(|&v| u8::from(v as f64 > sea)).collect(),
            slope: analysis::slope(field, gw, gh),
            abs_curv: abs(analysis::curvature_at(field, gw, gh, CURVATURE_SMOOTH, world)),
            abs_tpi: abs(analysis::tpi(field, gw, gh, r_fine, world)),
            stream_order: stream_order.filter(|o| o.len() == n).map(<[i16]>::to_vec),
            boundary: (boundary.len() == n).then(|| boundary.to_vec()),
            volcanic: (volcanic.len() == n).then(|| volcanic.to_vec()),
        }
    }

    /// Builds from a [`crate::WorldState`] and the parameters it was generated
    /// with: the one place the three optional grids are read off a world, so
    /// "empty `Vec` from a `Loaded` save" is mapped to absent exactly once.
    ///
    /// Returns `None` if `state.field` is shorter than `p.gw * p.gh` (the
    /// derivative functions would otherwise assert), or the grid is smaller
    /// than 2 in an axis.
    #[must_use]
    pub fn from_world(state: &crate::WorldState, p: &crate::WorldParams) -> Option<Self> {
        let n = p.gw.checked_mul(p.gh)?;
        if p.gw < 2 || p.gh < 2 || state.field.len() != n {
            return None;
        }
        Some(Self::build(
            &state.field,
            p.gw,
            p.gh,
            state.sea_level,
            p.world,
            p.map_width_km,
            state.stream_order.as_deref(),
            &state.boundary_type,
            &state.volcanic_field,
        ))
    }

    /// Coarse grid width.
    #[must_use]
    pub fn gw(&self) -> usize {
        self.gw
    }

    /// Coarse grid height.
    #[must_use]
    pub fn gh(&self) -> usize {
        self.gh
    }

    /// Whether the world carries a stream order. `false` means the term is
    /// absent for **every** tile.
    #[must_use]
    pub fn has_stream_order(&self) -> bool {
        self.stream_order.is_some()
    }

    /// Whether the world carries a `boundary_type` grid.
    #[must_use]
    pub fn has_boundary(&self) -> bool {
        self.boundary.is_some()
    }

    /// Whether the world carries a `volcanic_field` grid.
    #[must_use]
    pub fn has_volcanic(&self) -> bool {
        self.volcanic.is_some()
    }
}

/// Inclusive coarse-cell footprint `(x0, x1, y0, y1)` of a tile's bounds.
///
/// Cell `i` is the lattice square `[i, i + 1]` of the coarse sample space, so
/// the footprint is `floor(b.x) ..= ceil(b.x + b.w) - 1`: never empty (a tile
/// narrower than a cell still sees the cell it sits in) and clamped to the
/// grid. **Labelled judgement** (EF-9.0): the plan says "aggregated over the
/// footprint" without fixing the cell convention.
///
/// Moved here verbatim from EF-9.0's harness so importance and the harness
/// share one definition (EF-9.1 §8.3: "reusing EF-9.0's definitions").
/// `gw` and `gh` must be at least 1.
#[must_use]
pub fn footprint_cells(b: &FloatRegion, gw: usize, gh: usize) -> (usize, usize, usize, usize) {
    let axis = |lo: f64, len: f64, n: usize| {
        let a = (lo.floor().max(0.0) as usize).min(n - 1);
        let hi = ((lo + len).ceil() as i64 - 1).max(a as i64) as usize;
        (a, hi.min(n - 1))
    };
    let (x0, x1) = axis(b.x, b.w, gw);
    let (y0, y1) = axis(b.y, b.h, gh);
    (x0, x1, y0, y1)
}

/// **One tile's footprint aggregates** over `src` for a tile whose bounds in
/// coarse sample space are `bounds` (`cartalith_spatial::pyramid::pyramid_tile_bounds`).
///
/// The arithmetic is EF-9.0's, moved rather than restated: sums run
/// row-major over [`footprint_cells`], means divide by the cell count, the
/// stream-order and volcanic aggregates are maxima. An optional grid the world
/// does not carry gives `None` for its term; a present grid that happens to be
/// zero over the footprint gives `Some(0.0)` -- the two are different answers
/// and callers must keep them different.
#[must_use]
pub fn tile_features(src: &WorldImportanceField, bounds: &FloatRegion) -> TileImportanceInputs {
    let (x0, x1, y0, y1) = footprint_cells(bounds, src.gw, src.gh);
    let (mut sum_s, mut max_s, mut sum_c, mut sum_t) = (0.0f64, 0.0f64, 0.0f64, 0.0f64);
    let (mut land, mut bnd, mut max_o, mut max_v) = (0usize, 0usize, i16::MIN, f32::MIN);
    let mut cnt = 0usize;
    for y in y0..=y1 {
        for x in x0..=x1 {
            let i = y * src.gw + x;
            cnt += 1;
            sum_s += f64::from(src.slope[i]);
            max_s = max_s.max(f64::from(src.slope[i]));
            sum_c += f64::from(src.abs_curv[i]);
            sum_t += f64::from(src.abs_tpi[i]);
            land += usize::from(src.land[i]);
            if let Some(bt) = &src.boundary {
                bnd += usize::from(bt[i] != 0);
            }
            if let Some(o) = &src.stream_order {
                max_o = max_o.max(o[i]);
            }
            if let Some(v) = &src.volcanic {
                max_v = max_v.max(v[i]);
            }
        }
    }
    let c = cnt as f64;
    TileImportanceInputs {
        slope_mean: Some(sum_s / c),
        slope_max: Some(max_s),
        abs_curv_mean: Some(sum_c / c),
        abs_tpi_mean: Some(sum_t / c),
        stream_order_max: src.stream_order.is_some().then(|| f64::from(max_o)),
        land_fraction: Some(land as f64 / c),
        boundary_fraction: src.boundary.is_some().then(|| bnd as f64 / c),
        volcanic_max: src.volcanic.is_some().then(|| f64::from(max_v)),
    }
}

// ----------------------------------------------------------------- weights

/// One term of the fitted model: the standardisation constants and the weight.
///
/// `score += weight * (x - mean) / scale`. `mean` and `scale` are the training
/// tiles' mean and (population) standard deviation of the raw feature, so the
/// weights are comparable across terms. `weight = None` means the term was
/// **dropped** because its bootstrap 95 % interval included 0 (see
/// [`FITTED_WEIGHTS`]); a dropped term is not used and is not "missing" either
/// ([`TermState::Dropped`] vs [`TermState::Missing`]).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FittedTerm {
    /// Training mean of the raw feature.
    pub mean: f64,
    /// Training standard deviation of the raw feature; must be `> 0`.
    pub scale: f64,
    /// Non-negative least-squares weight on the standardised feature, or
    /// `None` if the term was dropped.
    pub weight: Option<f64>,
}

/// A complete weight set: one [`FittedTerm`] per [`FEATURE_NAMES`] entry.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ImportanceWeights {
    /// In [`FEATURE_NAMES`] order.
    pub terms: [FittedTerm; N_FEATURES],
}

/// What happened to one term when a tile was scored.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TermState {
    /// The input was present and the term is in the model: it contributed.
    Used,
    /// The input is **absent** for this world: it did not contribute and was
    /// not scored as 0.
    Missing,
    /// The input was present but the model dropped the term (its fitted
    /// interval included 0): it did not contribute, by decision, not by
    /// absence.
    Dropped,
}

/// A tile's importance and which terms produced it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Importance {
    /// Sum of `weight * z` over the [`TermState::Used`] terms; `None` when no
    /// term was used (every fitted term absent), never `0.0`.
    ///
    /// Higher = more refinement gain expected. Comparable only between tiles
    /// scored with the same `terms_used`.
    pub score: Option<f64>,
    /// Per-term outcome, in [`FEATURE_NAMES`] order.
    pub terms_used: [TermState; N_FEATURES],
}

impl Importance {
    /// Names of the terms reported [`TermState::Missing`].
    #[must_use]
    pub fn missing(&self) -> Vec<&'static str> {
        self.names_in(TermState::Missing)
    }

    /// Names of the terms that contributed.
    #[must_use]
    pub fn used(&self) -> Vec<&'static str> {
        self.names_in(TermState::Used)
    }

    fn names_in(&self, s: TermState) -> Vec<&'static str> {
        FEATURE_NAMES.iter().zip(&self.terms_used).filter(|&(_, &t)| t == s).map(|(&n, _)| n).collect()
    }
}

/// **Scores one tile.** Pure; deterministic.
///
/// For each term in `weights`: an absent input (`None`, or a non-finite
/// number, which is how an upstream `NaN` would arrive) is
/// [`TermState::Missing`] and contributes nothing; a present input with a
/// dropped term is [`TermState::Dropped`]; otherwise it adds
/// `weight * (x - mean) / scale`. Missing terms are *skipped*, not scored as 0
/// -- see the module header for what that means for comparing scores.
///
/// Must never read a settlement or a way: those are [`PolicyInputs`], and
/// importance has no argument through which they could enter.
#[must_use]
pub fn importance(features: &TileImportanceInputs, weights: &ImportanceWeights) -> Importance {
    let xs = features.as_array();
    let mut terms_used = [TermState::Missing; N_FEATURES];
    let mut score = 0.0f64;
    let mut any = false;
    for (k, term) in weights.terms.iter().enumerate() {
        match xs[k] {
            Some(x) if x.is_finite() => match term.weight {
                Some(w) => {
                    score += w * (x - term.mean) / term.scale;
                    terms_used[k] = TermState::Used;
                    any = true;
                }
                None => terms_used[k] = TermState::Dropped,
            },
            _ => {}
        }
    }
    Importance { score: any.then_some(score), terms_used }
}

// ---------------------------------------------------------- policy (Q2)

/// The human-significance inputs, **not fitted** (§8.3): plain numbers, because
/// settlements and ways are `cartalith-civ` types that `cartalith-engine`
/// cannot name. `None` = the world has no civ layer (or no ways), never a
/// count of zero.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct PolicyInputs {
    /// Settlements whose cell lies in the tile's footprint.
    pub settlement_count: Option<f64>,
    /// Way (road) length inside the footprint, in coarse-cell units.
    pub way_length: Option<f64>,
}

/// **Q2's policy bias** (§8.5, default): `Some(1)` if any *present* term is
/// positive, `Some(0)` if terms are present and all zero, `None` if both are
/// absent.
///
/// It is a *sort key prefix*, to be applied **within the level a tile already
/// has**: tiles with rank 1 are synthesised first. It is never added to
/// [`Importance::score`] and must never be compared with, thresholded
/// against, or used to promote a tile past its level -- EF-9.0 measured
/// settlements and ways as non-predictors of geometric gain (rho 0.015,
/// 0.11), so Q2's default is that they raise order only. A `None` rank means
/// "no information" and must be ordered as not-raised, never as 1.
#[must_use]
pub fn policy_rank(p: &PolicyInputs) -> Option<u8> {
    let present = [p.settlement_count, p.way_length];
    let mut any = false;
    for v in present.into_iter().flatten() {
        if !v.is_finite() {
            continue;
        }
        any = true;
        if v > 0.0 {
            return Some(1);
        }
    }
    any.then_some(0)
}

/// **Synthesis order within one level** (Q2): indices sorted by policy rank
/// first (rank 1 before rank 0 or `None`), then by importance score
/// descending (a `None` score last), then by index so the result is total and
/// deterministic.
///
/// This is the *only* place a [`policy_rank`] is consumed. It reorders tiles
/// that are all at the same level; it takes the scores by shared reference and
/// returns a permutation, so it cannot change a score, and nothing here maps a
/// rank to a level -- a policy-raised tile is synthesised *earlier*, never
/// *deeper*. `scores` and `ranks` must be the same length (a mismatch panics:
/// silently truncating would drop tiles from the schedule).
#[must_use]
pub fn synthesis_order(scores: &[Option<f64>], ranks: &[Option<u8>]) -> Vec<usize> {
    assert_eq!(scores.len(), ranks.len(), "one rank per score");
    let key = |i: usize| (ranks[i].unwrap_or(0), scores[i].filter(|v| v.is_finite()));
    let mut idx: Vec<usize> = (0..scores.len()).collect();
    idx.sort_by(|&a, &b| {
        let (ka, kb) = (key(a), key(b));
        kb.0.cmp(&ka.0).then_with(|| match (ka.1, kb.1) {
            (Some(x), Some(y)) => y.partial_cmp(&x).expect("finite"),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => std::cmp::Ordering::Equal,
        })
        .then(a.cmp(&b))
    });
    idx
}

// ------------------------------------------------------- fitted constants

/// **The fitted weights** (EF-9.1). Every number below is *measured*, none is a
/// judgement; the run that produced it is reproducible with
///
/// ```text
/// cargo test --release -p cartalith-civ --test ef9_refinement_gain -- --ignored --nocapture ef9_1_importance_fit
/// ```
///
/// (seeds `483920, 24601, 71077345`; grids `2048x1311` and `512x384`; tile
/// 256 px; 3x3 windows of 16x16 tiles at z5..z10; about 5 minutes in release
/// plus the measurement). The weights that ship are the fit **trained on seeds
/// other than 71077345** (both grids, 55 295 tiles), so seed 71077345 -- the
/// last-listed seed, fixed before any result was seen -- is genuinely out of
/// sample for them.
///
/// * **Method.** Non-negative least squares of the standardised features
///   against `ln(G_scr)`, with a *within-(world, level)* fixed effect (x and y
///   centred per cell, which is also the free intercept) because importance
///   only ever ranks the tiles of one level of one world. `mean` / `scale` are
///   the training mean and population standard deviation each raw feature is
///   standardised with, so `weight` is in standard-deviation units.
///   `G_scr <= 0` tiles have no logarithm: they are excluded from the fit and
///   counted (1 of 55 296 in this training set), never floored to a small
///   number; they remain in held-out capture scoring.
/// * **Dropped terms** (`weight: None`): `abs_curv_mean`, `abs_tpi_mean` and
///   `stream_order_max` -- NNLS gave each an exact-zero point weight (their
///   information is already carried by slope), so they are dropped without a
///   bootstrap. Backward elimination on the 400-replicate tile bootstrap then
///   kept `slope_mean`, `slope_max`, `land_fraction` and `boundary_fraction`
///   (95 % intervals exclude 0) and `volcanic_max` (its interval's lower end is
///   0.0008, zero-share 0.022 < 0.025 -- **marginal**: the 1000-replicate
///   window-cluster bootstrap, a sensitivity check, would drop it).
/// * **What it buys, held out** (25 % budget, median over the (world, level)
///   cells, from the recorded run): leave-one-seed-out `0.579` against
///   `slope_mean` alone `0.576` (oracle `0.653`, centre-first `0.232`);
///   leave-one-grid-out `0.591` against `0.576`. The margin on the seed folds
///   is **0.003** -- the acceptance rule (fit >= `slope_mean` on both fold
///   families) is met, but it is a near tie there, and in 14 of 36 seed-fold
///   cells (12 of 36 grid-fold cells) the fit is below `slope_mean`. On the
///   shipped fold's own held-out seed it is below `slope_mean` at z5-z7
///   (-0.088, -0.024, -0.027) and level with it at z8-z10. Most of the weight
///   is on `land_fraction`, which separates sea tiles (no gain) from land
///   tiles.
/// * **`mean` is rank-neutral**: every tile's score shifts by the same constant
///   when a mean changes (while every term is present), so only `scale` and
///   `weight` order tiles; `mean` is kept so [`Importance::score`] is the
///   fitted centred `ln G_scr` prediction rather than an arbitrary offset.
///
/// Pinned by `fitted_weights_are_the_recorded_literals` here and by the
/// held-out-capture regression test in the harness (fixture
/// `tests/fixtures/ef9_importance_heldout.tsv`).
pub const FITTED_WEIGHTS: ImportanceWeights = ImportanceWeights {
    terms: [
        FittedTerm { mean: 3.1241616491520747, scale: 6.068819932317762, weight: Some(0.4732193684495991) }, // slope_mean
        FittedTerm { mean: 7.792180002618385, scale: 19.076330851465723, weight: Some(0.40139324119044706) }, // slope_max
        FittedTerm { mean: 0.5721100897860526, scale: 1.2977892806325668, weight: None },                  // abs_curv_mean
        FittedTerm { mean: 0.0020162696237814217, scale: 0.0050149607574910835, weight: None },            // abs_tpi_mean
        FittedTerm { mean: 0.27150736956325167, scale: 0.6256543349088215, weight: None },                 // stream_order_max
        FittedTerm { mean: 0.6932247356921488, scale: 0.4507789234469542, weight: Some(1.731660169567006) }, // land_fraction
        FittedTerm { mean: 0.01556016047784156, scale: 0.07171359562713578, weight: Some(0.08934428046030551) }, // boundary_fraction
        FittedTerm { mean: 0.007197216866892922, scale: 0.0614248927344147, weight: Some(0.011093330064657769) }, // volcanic_max
    ],
};

#[cfg(test)]
mod tests {
    use super::*;
    use cartalith_spatial::pyramid::pyramid_tile_bounds;

    /// Grid edge of the hand-checkable fixtures below.
    const N: usize = 8;

    /// A flat plain at 0.6 over sea 0.42 with a 2x2 sea block in the top-left
    /// corner (cells `x, y in 0..2`), so a footprint of cells `0..=3` holds
    /// exactly 16 cells of which 4 are water.
    fn field_with_sea_corner() -> Vec<f32> {
        let mut f = vec![0.6f32; N * N];
        for y in 0..2 {
            for x in 0..2 {
                f[y * N + x] = 0.3;
            }
        }
        f
    }

    /// The footprint `[0, 4) x [0, 4)`: coarse cells `0..=3` on both axes.
    fn quad() -> FloatRegion {
        FloatRegion { x: 0.0, y: 0.0, w: 4.0, h: 4.0 }
    }

    /// A `WorldState` carrying only the grids this module reads; the rest are
    /// empty on purpose, so growing a dependency on one fails loudly (same
    /// construction as `elevation.rs`'s tests).
    fn world(field: Vec<f32>, boundary: Vec<u8>, order: Option<Vec<i16>>, volcanic: Vec<f32>) -> crate::WorldState {
        crate::WorldState {
            sea_level: 0.42,
            field: std::sync::Arc::new(field),
            plate_id: Vec::new(),
            boundary_mask: Vec::new(),
            stress_field: Vec::new(),
            age_field: std::sync::Arc::new(Vec::new()),
            resistance_field: std::sync::Arc::new(Vec::new()),
            crust_field: std::sync::Arc::new(Vec::new()),
            boundary_type: boundary,
            shear_field: Vec::new(),
            volcanic_field: std::sync::Arc::new(volcanic),
            impact_field: Vec::new(),
            temperature: std::sync::Arc::new(Vec::new()),
            rainfall: std::sync::Arc::new(Vec::new()),
            flow_discharge: std::sync::Arc::new(Vec::new()),
            integrated_drainage: false,
            channels: None,
            stream_order: order,
            river_mask: None,
            river_floor: None,
            gpu_stages_used: Vec::new(),
            geology: crate::Geology::Absent(crate::GeologyAbsent::ModelOff),
        }
    }

    /// A weight set for hand arithmetic: only `slope_mean`, `land_fraction`
    /// and `boundary_fraction` carry weights; `stream_order_max` is a dropped
    /// term; the rest are weighted too (so absent inputs, not missing weights,
    /// are what leave them out).
    fn local_weights() -> ImportanceWeights {
        let t = |mean, scale, weight| FittedTerm { mean, scale, weight };
        ImportanceWeights {
            terms: [
                t(1.0, 2.0, Some(3.0)),   // slope_mean
                t(0.0, 1.0, Some(5.0)),   // slope_max
                t(0.0, 1.0, Some(5.0)),   // abs_curv_mean
                t(0.0, 1.0, Some(5.0)),   // abs_tpi_mean
                t(0.0, 1.0, None),        // stream_order_max: dropped
                t(0.5, 0.25, Some(1.0)),  // land_fraction
                t(0.1, 0.1, Some(2.0)),   // boundary_fraction
                t(0.0, 1.0, Some(5.0)),   // volcanic_max
            ],
        }
    }

    /// Protects: `tile_features` against hand-counted values on a fixture whose
    /// footprint holds 16 cells, 4 of them sea, 3 boundary cells in and 1 out,
    /// stream orders peaking at 5 inside (9 outside), volcanic peaking at 0.7
    /// inside (0.9 outside). An off-by-one footprint, a mean taken over the
    /// wrong count, or a max taken over cells outside the tile each move one of
    /// these numbers.
    #[test]
    fn tile_features_match_hand_counted_values() {
        let field = field_with_sea_corner();
        let mut order = vec![0i16; N * N];
        order[2 * N + 2] = 5;
        order[3 * N + 1] = 2;
        order[3 * N + 6] = 9; // outside the footprint
        let mut boundary = vec![0u8; N * N];
        for &(x, y) in &[(0usize, 0usize), (2, 1), (3, 3)] {
            boundary[y * N + x] = 2;
        }
        boundary[5 * N + 5] = 1; // outside the footprint
        let mut volc = vec![0.0f32; N * N];
        volc[1 * N + 3] = 0.7;
        volc[6 * N + 6] = 0.9; // outside the footprint
        let src = WorldImportanceField::build(&field, N, N, 0.42, false, 800.0, Some(&order), &boundary, &volc);
        let f = tile_features(&src, &quad());
        assert_eq!(f.land_fraction, Some(12.0 / 16.0), "16 cells, the 2x2 corner is water");
        assert_eq!(f.boundary_fraction, Some(3.0 / 16.0), "three boundary cells inside; the one at (5,5) is outside");
        assert_eq!(f.stream_order_max, Some(5.0), "the 9 at (6,3) lies outside the footprint");
        assert!((f.volcanic_max.unwrap() - 0.7).abs() < 1e-6, "the 0.9 at (6,6) lies outside: {:?}", f.volcanic_max);
        // the step between water and land makes slope and curvature positive.
        assert!(f.slope_mean.unwrap() > 0.0 && f.slope_max.unwrap() >= f.slope_mean.unwrap());
        assert!(f.abs_curv_mean.unwrap() > 0.0);
    }

    /// Protects: a flat world scoring exactly zero on the three derivative
    /// terms and one on land -- the "no terrain structure" baseline every
    /// other test's numbers are relative to.
    #[test]
    fn a_flat_plain_has_no_slope_curvature_or_tpi() {
        let field = vec![0.6f32; N * N];
        let src = WorldImportanceField::build(&field, N, N, 0.42, false, 800.0, None, &[], &[]);
        let f = tile_features(&src, &quad());
        assert_eq!(f.slope_mean, Some(0.0));
        assert_eq!(f.slope_max, Some(0.0));
        assert!(f.abs_curv_mean.unwrap().abs() < 1e-6, "{:?}", f.abs_curv_mean);
        assert!(f.abs_tpi_mean.unwrap().abs() < 1e-6, "{:?}", f.abs_tpi_mean);
        assert_eq!(f.land_fraction, Some(1.0));
    }

    /// Protects: the footprint convention -- inclusive cells from
    /// `floor(x)` to `ceil(x + w) - 1`, never empty, clamped to the grid.
    #[test]
    fn footprint_cells_follow_the_floor_ceil_convention() {
        assert_eq!(footprint_cells(&FloatRegion { x: 4.0, y: 4.0, w: 3.5, h: 2.0 }, N, N), (4, 7, 4, 5));
        assert_eq!(footprint_cells(&FloatRegion { x: 2.25, y: 2.25, w: 0.25, h: 0.25 }, N, N), (2, 2, 2, 2), "narrower than a cell: still the cell it sits in");
        assert_eq!(footprint_cells(&FloatRegion { x: 7.5, y: 7.5, w: 4.0, h: 4.0 }, N, N), (7, 7, 7, 7), "clamped to the grid");
        assert_eq!(footprint_cells(&FloatRegion { x: 0.0, y: 0.0, w: 8.0, h: 8.0 }, N, N), (0, 7, 0, 7), "the whole-world tile");
    }

    /// Protects: the tile -> footprint wiring against `pyramid_tile_bounds`:
    /// level 1 over an 8-cell grid is a 2x2 tiling, so tile (1, 0) must see
    /// cells `4..=7` by `0..=3`.
    #[test]
    fn tile_bounds_from_the_pyramid_pick_the_right_cells() {
        let mut order = vec![0i16; N * N];
        order[1 * N + 6] = 7; // inside tile (1, 0)
        order[1 * N + 1] = 9; // inside tile (0, 0)
        let src = WorldImportanceField::build(&vec![0.6f32; N * N], N, N, 0.42, false, 800.0, Some(&order), &[], &[]);
        let b10 = pyramid_tile_bounds(N, N, 1, 1, 0);
        assert_eq!(tile_features(&src, &b10).stream_order_max, Some(7.0));
        let b00 = pyramid_tile_bounds(N, N, 1, 0, 0);
        assert_eq!(tile_features(&src, &b00).stream_order_max, Some(9.0));
    }

    /// Protects: absent-is-not-zero at the source. A world with **no stream
    /// order** reports `stream_order_max` as `None`, and one whose stream order
    /// is present but all zero reports `Some(0.0)` -- two different answers.
    #[test]
    fn a_world_without_stream_order_reports_that_term_missing() {
        let field = field_with_sea_corner();
        let absent = WorldImportanceField::build(&field, N, N, 0.42, false, 800.0, None, &[], &[]);
        assert!(!absent.has_stream_order());
        let f = tile_features(&absent, &quad());
        assert_eq!(f.stream_order_max, None);
        let zeros = vec![0i16; N * N];
        let present = WorldImportanceField::build(&field, N, N, 0.42, false, 800.0, Some(&zeros), &[], &[]);
        assert!(present.has_stream_order());
        assert_eq!(tile_features(&present, &quad()).stream_order_max, Some(0.0));
        // and importance() carries the difference through: Missing vs Used.
        let w = local_weights();
        let mut w_all = w;
        w_all.terms[4].weight = Some(4.0); // make the term live so Missing vs Used is observable
        let a = importance(&f, &w_all);
        assert_eq!(a.terms_used[4], TermState::Missing);
        assert!(a.missing().contains(&"stream_order_max"));
        let b = importance(&tile_features(&present, &quad()), &w_all);
        assert_eq!(b.terms_used[4], TermState::Used);
        assert!(!b.missing().contains(&"stream_order_max"));
    }

    /// Protects: a `Loaded` save's empty `boundary_type` and `volcanic_field`
    /// reaching `from_world`: both terms must be missing -- not zero boundary,
    /// not zero volcanism -- while a world that carries the grids (even all
    /// zero) has them present. Also a wrong-length grid is absent, not
    /// truncated.
    #[test]
    fn a_loaded_world_with_empty_boundary_type_reports_those_terms_missing() {
        let p = crate::WorldParams::defaults(N, N, 1);
        let loaded = world(field_with_sea_corner(), Vec::new(), None, Vec::new());
        let src = WorldImportanceField::from_world(&loaded, &p).expect("field has gw*gh cells");
        assert!(!src.has_boundary() && !src.has_volcanic() && !src.has_stream_order());
        let f = tile_features(&src, &quad());
        assert_eq!((f.boundary_fraction, f.volcanic_max, f.stream_order_max), (None, None, None));
        assert!(f.slope_mean.is_some() && f.land_fraction.is_some(), "the field-derived terms stay present");
        let mut w = local_weights();
        w.terms[4].weight = Some(1.0);
        let imp = importance(&f, &w);
        assert_eq!(imp.missing(), vec!["stream_order_max", "boundary_fraction", "volcanic_max"]);
        // present-but-zero is a different, scored, answer
        let carried = world(field_with_sea_corner(), vec![0u8; N * N], Some(vec![0i16; N * N]), vec![0.0f32; N * N]);
        let src2 = WorldImportanceField::from_world(&carried, &p).unwrap();
        let f2 = tile_features(&src2, &quad());
        assert_eq!((f2.boundary_fraction, f2.volcanic_max, f2.stream_order_max), (Some(0.0), Some(0.0), Some(0.0)));
        assert!(importance(&f2, &w).missing().is_empty());
        // wrong length: absent
        let short = WorldImportanceField::build(&field_with_sea_corner(), N, N, 0.42, false, 800.0, Some(&[1i16; 3]), &[1u8; 5], &[0.5f32; 7]);
        assert!(!short.has_boundary() && !short.has_volcanic() && !short.has_stream_order());
        // a field that is not gw*gh yields no source at all
        let bad = world(vec![0.5; 10], Vec::new(), None, Vec::new());
        assert!(WorldImportanceField::from_world(&bad, &p).is_none());
    }

    /// Protects: `importance()` against hand arithmetic with the local weights:
    /// slope 5 -> 3*(5-1)/2 = 6, land 0.75 -> 1*(0.75-0.5)/0.25 = 1,
    /// boundary 0.0 (present) -> 2*(0-0.1)/0.1 = -2; stream order is a dropped
    /// term; everything else absent. Total 5.
    #[test]
    fn importance_is_the_standardised_weighted_sum_over_present_terms() {
        let x = TileImportanceInputs {
            slope_mean: Some(5.0),
            land_fraction: Some(0.75),
            boundary_fraction: Some(0.0),
            stream_order_max: Some(4.0),
            ..TileImportanceInputs::default()
        };
        let imp = importance(&x, &local_weights());
        assert!((imp.score.unwrap() - 5.0).abs() < 1e-12, "{:?}", imp.score);
        assert_eq!(imp.used(), vec!["slope_mean", "land_fraction", "boundary_fraction"]);
        assert_eq!(imp.terms_used[4], TermState::Dropped, "present but dropped is not Missing");
        assert_eq!(imp.missing(), vec!["slope_max", "abs_curv_mean", "abs_tpi_mean", "volcanic_max"]);
        // the three weights each matter: perturb one input at a time
        for (name, bump) in [("slope", 0usize), ("land", 5), ("boundary", 6)] {
            let mut a = x.as_array();
            *a[bump].as_mut().unwrap() += 0.5;
            let moved = importance(&TileImportanceInputs::from_array(a), &local_weights()).score.unwrap();
            assert!((moved - 5.0).abs() > 1e-9, "{name} must move the score");
        }
    }

    /// Protects: the never-score-absent-as-zero rule at the scoring step: a
    /// `NaN` or infinite input is `Missing` exactly like `None`; no usable term
    /// gives `score: None`, not `Some(0.0)`; and a missing term changes the
    /// score by *skipping*, not by contributing `weight * (0 - mean) / scale`.
    #[test]
    fn missing_terms_are_skipped_and_an_empty_score_is_none() {
        let w = local_weights();
        let none = importance(&TileImportanceInputs::default(), &w);
        assert_eq!(none.score, None);
        assert!(none.used().is_empty());
        let nan = importance(&TileImportanceInputs { slope_mean: Some(f64::NAN), land_fraction: Some(f64::INFINITY), ..Default::default() }, &w);
        assert_eq!(nan.score, None);
        assert_eq!(nan.terms_used[0], TermState::Missing);
        assert_eq!(nan.terms_used[5], TermState::Missing);
        // skipping: with only land present the score is land's term alone,
        // *not* land's plus what a zero slope would have contributed (-1.5).
        let only_land = importance(&TileImportanceInputs { land_fraction: Some(0.75), ..Default::default() }, &w);
        assert!((only_land.score.unwrap() - 1.0).abs() < 1e-12);
    }

    /// Protects: Q2's policy being a separate type with no path into the
    /// score. `policy_rank` is `Some(1)` for any present positive term,
    /// `Some(0)` for present-and-zero, `None` for absent (and a `NaN` does not
    /// count as present).
    #[test]
    fn policy_rank_distinguishes_positive_zero_and_absent() {
        let p = |s, w| PolicyInputs { settlement_count: s, way_length: w };
        assert_eq!(policy_rank(&p(Some(2.0), None)), Some(1));
        assert_eq!(policy_rank(&p(None, Some(0.5))), Some(1));
        assert_eq!(policy_rank(&p(Some(0.0), Some(0.0))), Some(0));
        assert_eq!(policy_rank(&p(Some(0.0), None)), Some(0));
        assert_eq!(policy_rank(&p(None, None)), None);
        assert_eq!(policy_rank(&p(Some(f64::NAN), None)), None);
        assert_eq!(policy_rank(&p(Some(f64::NAN), Some(0.0))), Some(0));
    }

    /// Protects: the policy raising *order* only. A rank-1 tile with a lower
    /// importance is synthesised before a rank-0 tile with a higher one; ties
    /// within a rank go by score, then by index; a `None` score sorts after
    /// every scored tile of its rank; and the scores slice is untouched (it is
    /// passed by shared reference and compared after).
    #[test]
    fn synthesis_order_raises_policy_tiles_first_and_never_alters_scores() {
        let scores = [Some(0.9), Some(0.1), None, Some(0.5), Some(0.5)];
        let ranks = [Some(0), Some(1), Some(1), None, Some(0)];
        let before = scores;
        let order = synthesis_order(&scores, &ranks);
        assert_eq!(order, vec![1, 2, 0, 3, 4], "rank 1 first (scored before unscored), then rank 0/None by score then index");
        assert_eq!(scores, before);
        // without policy the order is by score alone
        assert_eq!(synthesis_order(&scores, &[None; 5]), vec![0, 3, 4, 1, 2]);
    }

    /// Protects: `FEATURE_NAMES` and `TileImportanceInputs::as_array` agreeing
    /// on order, which every weight array depends on: field k of the struct
    /// is the one named `FEATURE_NAMES[k]`.
    #[test]
    fn feature_order_is_the_documented_order() {
        let a = TileImportanceInputs {
            slope_mean: Some(0.0),
            slope_max: Some(1.0),
            abs_curv_mean: Some(2.0),
            abs_tpi_mean: Some(3.0),
            stream_order_max: Some(4.0),
            land_fraction: Some(5.0),
            boundary_fraction: Some(6.0),
            volcanic_max: Some(7.0),
        };
        assert_eq!(a.as_array().map(|v| v.unwrap()), [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]);
        assert_eq!(TileImportanceInputs::from_array(a.as_array()), a);
        assert_eq!(FEATURE_NAMES[4], "stream_order_max");
        assert_eq!(FEATURE_NAMES[7], "volcanic_max");
    }

    /// Protects: the shipped [`FITTED_WEIGHTS`] against any edit that is not a
    /// re-fit. Every term's `mean`, `scale` and `weight` (and which terms are
    /// dropped) is asserted as a literal, so a mutation of any one number --
    /// including a `mean`, which changes no rank and so is invisible to the
    /// capture test -- goes red here. Changing a literal on purpose means
    /// re-running the fit command in [`FITTED_WEIGHTS`]'s doc and updating this
    /// test and the harness pins in the same change.
    #[test]
    fn fitted_weights_are_the_recorded_literals() {
        let want: [(&str, f64, f64, Option<f64>); N_FEATURES] = [
            ("slope_mean", 3.1241616491520747, 6.068819932317762, Some(0.4732193684495991)),
            ("slope_max", 7.792180002618385, 19.076330851465723, Some(0.40139324119044706)),
            ("abs_curv_mean", 0.5721100897860526, 1.2977892806325668, None),
            ("abs_tpi_mean", 0.0020162696237814217, 0.0050149607574910835, None),
            ("stream_order_max", 0.27150736956325167, 0.6256543349088215, None),
            ("land_fraction", 0.6932247356921488, 0.4507789234469542, Some(1.731660169567006)),
            ("boundary_fraction", 0.01556016047784156, 0.07171359562713578, Some(0.08934428046030551)),
            ("volcanic_max", 0.007197216866892922, 0.0614248927344147, Some(0.011093330064657769)),
        ];
        for (k, (name, mean, scale, weight)) in want.iter().enumerate() {
            let t = FITTED_WEIGHTS.terms[k];
            assert_eq!(FEATURE_NAMES[k], *name);
            assert_eq!(t.mean, *mean, "{name} mean");
            assert_eq!(t.scale, *scale, "{name} scale");
            assert_eq!(t.weight, *weight, "{name} weight");
        }
    }
}
