#!/usr/bin/env node
/* Golden capture for the `wantCounts` tier classifier inside
 * `_civIterativeAutoWorld` (reference v2.11 lines 25925-25931;
 * `OUTSTANDING_WORK.md` §2.3, `PHASE2_SCOPE.md` m8).
 *
 * Runs the reference's OWN text, sliced out of the frozen v2.11 snapshot and
 * never retyped: the block `if(quota){ ... }` that follows
 * `const quota=wantCounts?Object.assign({},wantCounts):null;`, located by that
 * line and closed by brace matching. The block reads `quota`, `capitalOf` and
 * `rank` and writes `kind` -- all four supplied here, nothing else.
 *
 * Fixture: synthetic (capitalOf, wantCounts) pairs, not worlds. The classifier
 * takes those two and nothing else, so they are its whole input. Cases are
 * shaped to reach every clause: capital quota larger, smaller and zero against
 * the number of seats; a non-seat taking leftover capital quota; every quota
 * spent before the list ends (the `kind='hamlet'` default); zeros between
 * non-zeros.
 *
 * Usage:  node tools/civ_want_counts_capture.js \
 *           > crates/cartalith-civ/tests/golden_parity_want_counts.rs
 * The frozen reference is READ ONLY here.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const REF = path.join(__dirname, '..', '..', 'reference', 'Cartalith Gen1 v2.11.html');
const src = fs.readFileSync(REF, 'utf8');
function die(m) { console.error('CAPTURE ABORTED: ' + m); process.exit(1); }
function once(needle) {
  const a = src.indexOf(needle);
  if (a < 0 || src.indexOf(needle, a + 1) >= 0) die(`not exactly one occurrence of: ${needle}`);
  return a;
}
function braceBlock(from) {
  const open = src.indexOf('{', from);
  let d = 0;
  for (let k = open; k < src.length; k++) {
    if (src[k] === '{') d++;
    else if (src[k] === '}' && --d === 0) return src.slice(from, k + 1);
  }
  die('unbalanced braces');
}

const qLine = once('const quota=wantCounts?Object.assign({},wantCounts):null;');
const ifAt = src.indexOf('if(quota){', qLine);
if (ifAt < 0 || ifAt - qLine > 200) die('quota classifier is not where it was');
const block = braceBlock(ifAt);
for (const must of ["quota.capital>0&&capitalOf[rank]", "['capital','city','town','village','hamlet']", "kind='hamlet'"]) {
  if (!block.includes(must)) die(`block does not contain ${must}`);
}
const classify = new Function('quota', 'capitalOf', 'rank', `let kind; ${block}; return kind;`);

// Deterministic generator for the random half of the fixture.
let s = 0x2545F491;
const rnd = () => { s ^= s << 13; s ^= s >>> 17; s ^= s << 5; return (s >>> 0) / 4294967296; };

const cases = [
  // [capitalOf, [cap, city, town, village, hamlet]]
  [[true, false, true, false, false, true], [2, 1, 1, 1, 1]],        // fewer capital quota than seats
  [[false, false, true, false], [3, 0, 0, 0, 1]],                    // non-seats take leftover capital quota
  [[true, true, true], [0, 1, 0, 0, 5]],                             // zero capital quota: seats become cities/hamlets
  [[true, false, false, false, false, false, false], [1, 1, 1, 0, 0]], // quota spent before the list ends
  [[false, true, false, true, false], [0, 0, 2, 0, 1]],              // zeros between non-zeros
  [[true], [1, 0, 0, 0, 0]],
];
for (let c = 0; c < 20; c++) {
  const n = 1 + Math.floor(rnd() * 40);
  const cap = Array.from({ length: n }, () => rnd() < 0.2);
  const want = Array.from({ length: 5 }, () => Math.floor(rnd() * 9));
  cases.push([cap, want]);
}

const KIND = { capital: 'Capital', city: 'City', town: 'Town', village: 'Village', hamlet: 'Hamlet' };
const out = [];
out.push('//! GENERATED by `tools/civ_want_counts_capture.js` -- do not edit by hand.');
out.push('//! The reference\'s own `wantCounts` tier classifier (v2.11 25925-25931), run');
out.push('//! under Node over synthetic (capitalOf, counts) pairs, against');
out.push('//! `cartalith_civ::civ_quota_tier` called once per rank in the same order.');
out.push('');
out.push('use cartalith_civ::{civ_quota_tier, SettlementKind::{self, *}};');
out.push('');
out.push('#[rustfmt::skip]');
out.push('const CASES: &[(&[bool], [usize; 5], &[SettlementKind])] = &[');
for (const [capitalOf, w] of cases) {
  const quota = { capital: w[0], city: w[1], town: w[2], village: w[3], hamlet: w[4] };
  const kinds = capitalOf.map((_, rank) => classify(quota, capitalOf, rank));
  for (const k of kinds) if (!KIND[k]) die(`unexpected kind ${k}`);
  out.push(`    (&[${capitalOf.join(', ')}], [${w.join(', ')}], &[${kinds.map(k => KIND[k]).join(', ')}]),`);
}
out.push('];');
out.push('');
out.push('#[test]');
out.push('fn quota_classifier_matches_the_reference_text() {');
out.push('    assert!(CASES.len() >= 20, "fixture empty");');
out.push('    for (i, (capital_of, want, expect)) in CASES.iter().enumerate() {');
out.push('        let mut q = *want;');
out.push('        let got: Vec<SettlementKind> = capital_of.iter().map(|&c| civ_quota_tier(&mut q, c)).collect();');
out.push('        assert_eq!(got.as_slice(), *expect, "case {i}: capital_of {capital_of:?} want {want:?}");');
out.push('    }');
out.push('}');
console.log(out.join('\n'));
