/* The Rust prelude `um_block2_capture.js` prints ahead of its captured data:
 * the doc header, the fixture rebuilt in Rust (`build_world`), the case
 * structs, and the assertions. Kept beside the capture rather than inside it
 * so the JS harness stays readable as a harness.
 *
 * `build_world` here MUST stay arithmetically identical to `heightMillis` /
 * `buildWorld` / `buildWays` in `um_block2_capture.js`. Both are integers with
 * one final `/1000`, so the two agree bit for bit; a change to either without
 * the other shows up immediately as every profile case failing at once.
 */
'use strict';

module.exports = ({ arms, worlds, nProf, nKind, nOre, nAge, nHarb, nRay }) => `//! GENERATED by \`cartalith-native/tools/um_block2_capture.js\` -- do not hand-edit.
//!
//! Golden parity for \`urban_adapter.rs\`'s **block-2** \`_um*\` adapter --
//! \`URBAN_MORPHOLOGY_SCOPE.md\` milestone 17a, the row \`OUTSTANDING_WORK.md\`
//! §2.1 recorded as blocked on "no harness can run \`_um*\` inside the host's
//! full civ scope".
//!
//! **That blocker was wrong.** All four of the reference's \`<script>\` blocks
//! evaluate in a bare \`vm\` context, in the browser's own order, given one
//! self-similar Proxy standing in for the DOM. The harness's header records
//! the measurement and the three \`um_capture.js\` conventions that could not
//! carry over; the one worth repeating here is the \`let\` trap:
//! \`ctx.GW = 96\` is invisible to block-2 code, because \`GW\` is a global
//! **lexical** binding and not a property of the \`vm\` context. Every such
//! global is assigned by running an assignment *inside* the context, and the
//! harness re-reads each one from inside afterwards before capturing anything.
//!
//! # What is fixture and what is under test
//!
//! Fed in -- these are the Rust functions' own explicit parameters, so feeding
//! them IS the fixture: \`field\`, \`flowField\`, \`tempField\`, \`rainField\`,
//! \`civWays\`, \`_riverNet\`, \`GW\`/\`GH\`, \`state.*\`, and the five memos
//! \`currentWaterBodies\`, \`currentFloodField\`, \`currentCarryingCapacity\`,
//! \`currentResourcePotentials\`, \`buildBiomeRaster\`.
//!
//! Run live in the reference and never stubbed -- the Rust side has its own
//! port of each, so a disagreement in any of them surfaces here:
//! \`chamferDist\` (through \`_civCoastDistField\`), \`slopeAt\`, \`gradAt\`,
//! \`traceRiverPolylines\` (through \`_civRiverPolylines\`),
//! \`_civPlaceConnectedRoads\`, \`_civPlaceResourceContext\`,
//! \`_civPlaceDefensibility\`, \`_umInferWalls\`/\`_umWallSpec\`,
//! \`riverFlowThresh\`, and every \`_um*\` under test.
//!
//! # Two worlds, because every radius here is \`max(floor, GW/k)\`
//!
//! A single small grid reaches only the floors, and three constants would be
//! unobservable:
//!
//! | | Small 96x64 / 800 km | Large 448x288 / 190 km |
//! |---|---|---|
//! | \`_umSiteProfile\` \`defR = max(4, round(GW/70))\` | 4 (floor) | 6 |
//! | \`_umOreBearing\` \`R = max(2, round(GW/64))\` | 2 (floor) | 7 |
//! | \`_civPlaceResourceContext\` \`r = max(3, round(GW/128))\` | 3 (floor) | 4 |
//! | \`_umWaterReachKm\` \`max(nearKm, cellKm*1.5)\` | cell arm | near arm |
//! | \`_umSiteKindFromTerrain\` box \`(2r+1)^2\` | 5x5 = 25 | 11x11 = 121 |
//!
//! **Large is 190 km wide, not a round 400, and that is a measured choice.**
//! \`seaFrac\` is \`seaHits/n\` over that box, so it is quantised; at a 25-cell
//! box the smallest value above \`0.02\` is \`0.04\`, and mutating
//! \`_umSiteKindFromTerrain\`'s \`0.02\` to \`0.03\` is unobservable **by
//! construction** however many probes are swept. At 121 cells the quantum is
//! fine enough for both thresholds to be pinned, and they are: mutating
//! \`0.02\` to \`0.03\` and \`0.15\` to \`0.16\` in
//! [\`um_site_kind_from_terrain\`] each make this file fail (measured
//! 2026-09-02, a 22-mutant sweep over every constant below, all killed).
//!
//! The probe that pins \`0.02\` is \`Large (118, 283)\`, and it is the **only**
//! one in the whole sweep whose \`seaFrac\` lands in \`(0.02, 0.03]\` -- \`3/110\`,
//! not \`3/121\`, because the sample box is clipped at the grid edge. The
//! capture's retention rule keys on the quotient for exactly that reason; see
//! \`seaFracAt\` there.
//!
//! # The fixture is integer arithmetic and one division
//!
//! \`build_world\` below is the same integer expression the harness runs, with
//! one final \`/1000.0\` -- IEEE-exact, so both sides hold bit-identical
//! \`f32\`s. Two metric fixtures were what crushed \`um_capture.js\`'s town, and
//! the lesson is carried rather than relearned.
//!
//! # Shape gates
//!
//! The capture refuses to write unless the matrix reaches: both arms of
//! \`_umWaterReachKm\`'s \`max\`; both \`_umInferAge\` clamps; all three
//! \`_umHarbourScale\` arms (both clamps and the live power); \`coast\`,
//! \`river\` and \`landlocked\` site kinds; an ore bearing found, absent, and
//! underfoot; a profile with a river and one without; a sloped aspect; a site
//! with roads and one without; a non-empty \`resourcesNearby\`; and a finite
//! coast distance. Arms actually reached by the committed capture:
//!
//! \`\`\`text
//! ${arms}
//! \`\`\`
//!
//! \`bay\`, \`riverthrough\` and \`confluence\` are **not** required, and the line
//! above says whether this fixture reached them. Stated rather than faked.

#![allow(clippy::excessive_precision, clippy::unreadable_literal, clippy::approx_constant)]

use cartalith_civ::{
    CIV_RESOURCE_KEYS, ResourcePotentials, SettlementKind, Way, WayType,
    military::{WallPlace, um_infer_walls},
    urban_adapter::{
        SITE_HM, SITE_WM, SiteProfileWorld, UrbanWorld, civ_coast_dist_field, um_harbour_scale,
        um_infer_age, um_ore_bearing, um_ray_box_exit, um_site_box_km,
        um_site_kind_from_terrain, um_site_profile, um_water_near_km, um_water_reach_km,
    },
};
use cartalith_hydrology::trace_river_polylines;

// =============================== the fixture ===============================

pub struct World {
    pub id: &'static str,
    pub gw: usize,
    pub gh: usize,
    pub map_width_km: f64,
    pub sea_level: f64,
    /// \`riverFlowThresh(GW,GH)\` as the reference computed it under this
    /// world's \`state.mapWidthKm\` -- captured rather than recomputed, because
    /// \`UrbanWorld::flow_thresh\` is a caller-supplied field on both sides.
    pub flow_thresh: f64,
    pub cell_km: f64,
    pub site_box_km: f64,
    pub water_near_km: f64,
    pub water_reach_km: f64,
}

/// The nominal shore column; the river's outlet is here.
fn q_of(gw: usize) -> usize {
    gw >> 2
}
/// The shoreline is **ragged**, on purpose. A vertical coast puts a whole
/// 5-cell column of sea in \`_umSiteKindFromTerrain\`'s 5x5 box or none at all,
/// so \`seaFrac\` could only be 0, 0.2, 0.4 ... and the \`coast\` arm
/// (\`0.02 < seaFrac <= 0.15\`) would be unreachable by construction.
fn shore_col(j: usize, gw: usize) -> i64 {
    q_of(gw) as i64 + ((j * 5) % 7) as i64 - 3
}
/// The trunk's centre row at column \`i\` -- a staircase, so it is not axis-aligned.
fn river_row(i: usize, gh: usize) -> usize {
    ((gh >> 1) + i / 8) % gh
}
/// The tributary's centre row; it meets the trunk near \`i == gw*5/8\`.
fn trib_row(i: usize, gh: usize) -> usize {
    ((gh >> 3) + ((i * 3) >> 3)) % gh
}
/// A triangle wave, so land stays inside \`[0,1]\` at either grid width.
fn tri(x: i64) -> i64 {
    let t = x % 1040;
    if t < 520 { t } else { 1040 - t }
}

fn height_millis(i: usize, j: usize, gw: usize, gh: usize) -> i64 {
    let s = shore_col(j, gw);
    if (i as i64) < s {
        return 200 + ((i * 7) % 100) as i64;
    }
    let mut v = 460 + tri((i as i64 - s) * 3) + ((j * 7) % 13) as i64;
    if (j as i64 - river_row(i, gh) as i64).abs() <= 1 {
        v -= 15;
    }
    if (j as i64 - trib_row(i, gh) as i64).abs() <= 1 {
        v -= 9;
    }
    v
}

const FLOW_HIGH: f32 = 5000.0;

/// Every raster the capture installed, rebuilt from the same integers.
pub struct Fixture {
    pub field: Vec<f32>,
    pub flow: Vec<f32>,
    pub temp: Vec<f32>,
    pub rain: Vec<f32>,
    pub carry: Vec<f32>,
    pub flood: Vec<f32>,
    pub wb: Vec<u8>,
    pub biome: Vec<u8>,
    pub order: Vec<i16>,
    pub recv: Vec<i32>,
    pub pots: ResourcePotentials,
    pub ways: Vec<Way>,
    pub coast_dt: Vec<f32>,
    pub polys: Vec<Vec<(f64, f64)>>,
}

fn pots_field<'a>(pots: &'a mut ResourcePotentials, key: &str) -> &'a mut Vec<f32> {
    match key {
        "copper" => &mut pots.copper,
        "tin" => &mut pots.tin,
        "iron" => &mut pots.iron,
        "gold" => &mut pots.gold,
        "salt" => &mut pots.salt,
        "timber" => &mut pots.timber,
        "lead" => &mut pots.lead,
        "silver" => &mut pots.silver,
        "clay" => &mut pots.clay,
        "buildstone" => &mut pots.buildstone,
        "flint" => &mut pots.flint,
        "obsidian" => &mut pots.obsidian,
        "gems" => &mut pots.gems,
        "sulfur" => &mut pots.sulfur,
        "alum" => &mut pots.alum,
        other => panic!("unknown resource key {other}"),
    }
}

fn zero_pots(n: usize) -> ResourcePotentials {
    let z = || vec![0.0f32; n];
    ResourcePotentials {
        copper: z(), tin: z(), iron: z(), gold: z(), salt: z(), timber: z(), lead: z(),
        silver: z(), clay: z(), buildstone: z(), flint: z(), obsidian: z(), gems: z(),
        sulfur: z(), alum: z(),
    }
}

/// The potentials the harness leaves installed while capturing profiles: a
/// \`timber\`/\`clay\` background -- the reason \`resources_nearby\` is non-empty --
/// plus **one** \`iron\` cell, so at least one profile's \`resources\` mean is
/// carried by a real deposit rather than by the background alone.
///
/// The iron cell is planted last, exactly as the harness does after zeroing
/// every key at the end of its ore sweep; dropping it made \`resources[iron]\`
/// \`0.0\` against a reference \`0.0275862073\` on the very first profile that
/// reaches it.
fn background_pots(w: &World) -> ResourcePotentials {
    let (gw, gh) = (w.gw, w.gh);
    let mut p = zero_pots(gw * gh);
    for j in 0..gh {
        for i in 0..gw {
            p.timber[j * gw + i] = ((i * 7 + j * 5) % 91) as f32 / 100.0;
            p.clay[j * gw + i] = ((i + j * 3) % 51) as f32 / 100.0;
        }
    }
    let (oi, oj) = (q_of(gw) + 14, river_row(q_of(gw) + 14, gh) + 2);
    if oi < gw && oj < gh {
        p.iron[oj * gw + oi] = 0.8;
    }
    p
}

pub fn build_world(w: &World) -> Fixture {
    let (gw, gh) = (w.gw, w.gh);
    let n = gw * gh;
    let mut f = Fixture {
        field: vec![0.0; n], flow: vec![0.0; n], temp: vec![0.0; n], rain: vec![0.0; n],
        carry: vec![0.0; n], flood: vec![0.0; n], wb: vec![0; n], biome: vec![0; n],
        order: vec![0; n], recv: vec![-1; n], pots: background_pots(w), ways: build_ways(w),
        coast_dt: Vec::new(), polys: Vec::new(),
    };
    let q = q_of(gw);
    for j in 0..gh {
        for i in 0..gw {
            let k = j * gw + i;
            f.field[k] = height_millis(i, j, gw, gh) as f32 / 1000.0;
            if (j == river_row(i, gh) || j == trib_row(i, gh)) && i >= q {
                f.flow[k] = FLOW_HIGH;
            }
            f.temp[k] = ((i * 5 + j * 3) % 41) as f32 - 6.0;
            f.rain[k] = ((i * 3 + j * 11) % 101) as f32 / 100.0;
            f.carry[k] = ((i * 13 + j * 5) % 61) as f32 / 100.0;
            f.flood[k] = ((i + j) % 17) as f32 / 100.0;
            f.wb[k] = if (f.field[k] as f64) < w.sea_level { 1 } else { 0 };
            f.biome[k] = if f.wb[k] == 1 { 0 } else { 1 + ((i * 2 + j) % 12) as u8 };
        }
    }
    // The river network: a trunk running west to the shore, plus a tributary.
    let put = |order: &mut [i16], recv: &mut [i32], i: usize, j: usize, ni: usize, nj: usize, ord: i16| {
        let k = j * gw + i;
        order[k] = ord;
        recv[k] = if ni < q { -1 } else { (nj * gw + ni) as i32 };
    };
    for i in (q..gw).rev() {
        put(&mut f.order, &mut f.recv, i, river_row(i, gh), i - 1, river_row(i - 1, gh), 3);
    }
    let join = (gw * 5) >> 3;
    for i in ((join + 1)..gw).rev() {
        let j = trib_row(i, gh);
        let nj = if i - 1 == join { river_row(i - 1, gh) } else { trib_row(i - 1, gh) };
        if f.order[j * gw + i] != 0 {
            continue;
        }
        put(&mut f.order, &mut f.recv, i, j, i - 1, nj, 1);
    }
    // The two derived fields the reference caches; each is the Rust port of
    // exactly the call \`_umSiteProfile\` makes, and a disagreement in either
    // shows up as a profile mismatch rather than hiding.
    f.coast_dt = civ_coast_dist_field(&f.field, gw, gh, w.sea_level);
    f.polys = trace_river_polylines(&f.order, &f.recv, gw, gh, 1);
    f
}

/// \`civWays\` as the reference stores it. The hidden way and the one-point way
/// are both skipped by \`_civPlaceConnectedRoads\`, which is why they are here.
fn build_ways(w: &World) -> Vec<Way> {
    let (gw, gh) = (w.gw, w.gh);
    let q = q_of(gw) as f64;
    let (gwf, ghf) = (gw as f64, gh as f64);
    let half = (gh >> 1) as f64;
    let mk = |pts: Vec<(f64, f64)>, t: WayType, km: f64, hidden: bool| Way {
        tid: 0, pts, brks: Vec::new(), km, name: String::new(), way_type: t,
        a_idx: 0, b_idx: 0, hidden,
    };
    vec![
        mk(vec![(q + 6.0, half), (q + 20.0, half), (gwf - 4.0, half + 6.0)], WayType::Highway, 120.0, false),
        mk(vec![(q + 6.0, half), (q + 6.0, 4.0)], WayType::Regional, 60.0, false),
        mk(vec![(q + 6.0, half), (2.0, ghf - 3.0)], WayType::Track, 40.0, false),
        mk(vec![(q + 6.0, half), (gwf - 2.0, 2.0)], WayType::Road, 90.0, true),
        mk(vec![(q + 30.0, 8.0)], WayType::Road, 5.0, false),
        mk(vec![(gwf - 6.0, ghf - 6.0), (q + 2.0, ghf - 6.0)], WayType::Regional, 70.0, false),
    ]
}

fn urban_world<'a>(w: &World, f: &'a Fixture) -> UrbanWorld<'a> {
    UrbanWorld {
        field: &f.field, flow: &f.flow, water_bodies: &f.wb, order: Some(&f.order),
        river_polys: &f.polys, gw: w.gw, gh: w.gh, sea_level: w.sea_level,
        map_width_km: w.map_width_km, flow_thresh: w.flow_thresh, world_seed: 12345,
    }
}

fn find_world(id: &str) -> &'static World {
    WORLDS.iter().find(|w| w.id == id).unwrap_or_else(|| panic!("no world {id}"))
}

/// The reference's \`p.kind\` string as this port's enum. \`_umWallSpec\`'s
/// \`fortress\` rung has no [\`SettlementKind\`] variant -- \`military.rs\` says so
/// -- so the capture never emits one, and this panics rather than silently
/// picking a neighbouring rank if that ever changes.
fn settlement_kind(kind: &str) -> SettlementKind {
    match kind {
        "metropolis" => SettlementKind::Metropolis,
        "capital" => SettlementKind::Capital,
        "city" => SettlementKind::City,
        "town" => SettlementKind::Town,
        "village" => SettlementKind::Village,
        "hamlet" => SettlementKind::Hamlet,
        other => panic!("captured kind {other:?} has no SettlementKind variant"),
    }
}

// ================================ case types ===============================

pub struct HarbourCase {
    pub name: &'static str,
    pub site: &'static str,
    pub pop: f64,
    pub scale: f64,
}

pub struct RayCase {
    pub name: &'static str,
    pub dx: f64,
    pub dy: f64,
    pub x: f64,
    pub y: f64,
}

pub struct KindCase {
    pub world: &'static str,
    pub px: f64,
    pub py: f64,
    pub kind: &'static str,
}

pub struct OreCase {
    pub world: &'static str,
    pub name: &'static str,
    pub px: f64,
    pub py: f64,
    pub orient: f64,
    /// The one resource key seeded for this case; \`None\` means every
    /// potential is zero.
    pub key: Option<&'static str>,
    /// Where the deposit sits, relative to \`(px,py)\`.
    pub dx: i64,
    pub dy: i64,
    pub v: f64,
    /// \`max(2, round(GW/64))\` for this world -- carried so the fixture's
    /// \`dx\`/\`dy\` stay legible against the radius they were chosen for.
    pub r: i64,
    pub bearing: Option<f64>,
}

pub struct ProfileCase {
    pub world: &'static str,
    pub name: &'static str,
    pub px: f64,
    pub py: f64,
    pub kind: &'static str,
    pub pop: f64,
    /// \`_umInferWalls(p)\` as the reference answered it -- the one
    /// caller-resolved input \`SiteProfileWorld::walled\` takes.
    pub walled: bool,
    pub site_kind: &'static str,
    pub elevation: f64,
    pub elev_n: f64,
    pub slope_n: f64,
    pub aspect: Option<f64>,
    pub local_relief: f64,
    pub visibility: f64,
    pub coast_dist_km: f64,
    pub river_dist_km: f64,
    pub river_order: f64,
    pub river_width_m: f64,
    pub confluence: bool,
    pub floodplain: f64,
    pub road_count: usize,
    pub road_types: &'static [&'static str],
    /// \`_civPlaceResourceContext\`'s \`mean\`, every key, in the reference's
    /// own insertion order.
    pub resources: &'static [(&'static str, f64)],
    pub resources_nearby: &'static [&'static str],
    pub biome: Option<&'static str>,
    pub temp_c: f64,
    pub rain: f64,
    pub carry_k: f64,
    pub defensibility: f64,
    pub buildable_frac: f64,
}

// ================================ the tests ================================

/// Bit-exact: these are captured \`f64\` bit patterns, not tolerances. The one
/// place a tolerance would be right is a value this port deliberately computes
/// differently, and there is none here.
#[track_caller]
fn eq(what: &str, got: f64, want: f64) {
    assert!(
        got.to_bits() == want.to_bits() || (got.is_nan() && want.is_nan()),
        "{what}: got {got:?} (0x{:016x}), reference {want:?} (0x{:016x})",
        got.to_bits(),
        want.to_bits()
    );
}

#[test]
fn the_fixture_is_not_degenerate() {
    // The silently-empty-golden gate, re-run on this side: four subsystems in
    // this port have been bitten by a golden that passed over nothing.
    assert_eq!(WORLDS.len(), 2, "both grid sizes must be present");
    assert_eq!(AGES.len(), ${nAge});
    assert_eq!(HARBOURS.len(), ${nHarb});
    assert_eq!(RAYS.len(), ${nRay});
    assert_eq!(KINDS.len(), ${nKind});
    assert_eq!(ORES.len(), ${nOre});
    assert_eq!(PROFILES.len(), ${nProf});
    for w in WORLDS {
        let f = build_world(w);
        let n = w.gw * w.gh;
        assert_eq!(f.field.len(), n);
        assert!(f.field.iter().any(|&h| (h as f64) < w.sea_level), "{}: no sea", w.id);
        assert!(f.field.iter().any(|&h| (h as f64) >= w.sea_level), "{}: no land", w.id);
        assert!(f.flow.iter().any(|&v| v > 0.0), "{}: no river flow", w.id);
        assert!(f.polys.len() >= 2, "{}: expected >=2 traced stems, got {}", w.id, f.polys.len());
        assert!(f.coast_dt.iter().any(|&d| d == 0.0), "{}: coast DT never reaches the shore", w.id);
        assert!(f.coast_dt.iter().any(|&d| d > 0.0), "{}: coast DT is all zero", w.id);
        assert!(f.biome.iter().any(|&b| b == 0) && f.biome.iter().any(|&b| b != 0), "{}: biome raster is uniform", w.id);
    }
    // Both arms of \`_umWaterReachKm\`'s max, from the captured values alone.
    assert!(WORLDS.iter().any(|w| eqf(w.water_reach_km, w.water_near_km)), "no world reached the near-km arm");
    assert!(WORLDS.iter().any(|w| !eqf(w.water_reach_km, w.water_near_km)), "no world reached the cell arm");
    // And the three site kinds the capture gate requires.
    for k in ["coast", "river", "landlocked"] {
        assert!(KINDS.iter().any(|c| c.kind == k), "no captured site kind is '{k}'");
    }
    assert!(ORES.iter().any(|c| c.bearing.is_some()), "no ore bearing was found");
    assert!(ORES.iter().any(|c| c.bearing.is_none()), "no ore bearing was absent");
    assert!(PROFILES.iter().any(|c| c.river_order > 0.0), "no profile has a river");
    assert!(PROFILES.iter().any(|c| c.river_order == 0.0), "no profile is riverless");
    assert!(PROFILES.iter().any(|c| c.road_count > 0), "no profile has roads");
    assert!(PROFILES.iter().any(|c| c.road_count == 0), "no profile is roadless");
    assert!(PROFILES.iter().any(|c| !c.resources_nearby.is_empty()), "no profile has nearby resources");
    assert!(PROFILES.iter().any(|c| c.coast_dist_km.is_finite()), "no profile has a finite coast distance");
}

fn eqf(a: f64, b: f64) -> bool {
    a.to_bits() == b.to_bits()
}

#[test]
fn site_box_ladder_matches_reference() {
    for w in WORLDS {
        eq(&format!("{}: _umSiteBoxKm", w.id), um_site_box_km(), w.site_box_km);
        eq(&format!("{}: _umWaterNearKm", w.id), um_water_near_km(), w.water_near_km);
        eq(
            &format!("{}: _umWaterReachKm", w.id),
            um_water_reach_km(w.gw, w.map_width_km),
            w.water_reach_km,
        );
    }
}

#[test]
fn infer_age_matches_reference() {
    for &(pop, age) in AGES {
        eq(&format!("_umInferAge({pop})"), um_infer_age(pop), age);
    }
}

#[test]
fn harbour_scale_matches_reference() {
    for c in HARBOURS {
        eq(c.name, um_harbour_scale(c.pop, c.site), c.scale);
    }
}

/// The capture calls \`_umRayBoxExit(dx,dy,UME.SITE_WM,UME.SITE_HM)\`, so the
/// box passed here is [\`SITE_WM\`]/[\`SITE_HM\`] and **not** the literals \`1700\`
/// / \`1250\`. That is the difference between a live and a dead assertion:
/// mutating \`SITE_HM\` to \`1251.0\` survived the whole matrix while these were
/// literals -- nothing else in the golden can see it, because
/// \`_umSiteBoxKm\` is \`max(SITE_WM,SITE_HM)/1000\` and the buildable-area
/// lattice moves by \<0.0002 cells for a one-metre change in box height.
#[test]
fn ray_box_exit_matches_reference() {
    assert_eq!((SITE_WM, SITE_HM), (1700.0, 1250.0), "UME.SITE_WM/SITE_HM as the capture read them");
    for c in RAYS {
        let p = um_ray_box_exit(c.dx, c.dy, SITE_WM, SITE_HM);
        eq(&format!("{}.x", c.name), p.x, c.x);
        eq(&format!("{}.y", c.name), p.y, c.y);
    }
}

#[test]
fn site_kind_matches_reference() {
    for c in KINDS {
        let w = find_world(c.world);
        let f = build_world(w);
        let uw = urban_world(w, &f);
        assert_eq!(
            um_site_kind_from_terrain(&uw, c.px, c.py),
            c.kind,
            "{} ({}, {})",
            c.world,
            c.px,
            c.py
        );
    }
}

#[test]
fn ore_bearing_matches_reference() {
    for c in ORES {
        let w = find_world(c.world);
        let mut pots = zero_pots(w.gw * w.gh);
        if let Some(key) = c.key {
            let (x, y) = (c.px as i64 + c.dx, c.py as i64 + c.dy);
            if x >= 0 && y >= 0 && x < w.gw as i64 && y < w.gh as i64 {
                pots_field(&mut pots, key)[y as usize * w.gw + x as usize] = c.v as f32;
            }
        }
        let got = um_ore_bearing(&pots, w.gw, w.gh, c.px, c.py, c.orient);
        match (got, c.bearing) {
            (Some(g), Some(want)) => eq(c.name, g, want),
            (None, None) => {}
            (g, want) => panic!("{}/{}: got {g:?}, reference {want:?}", c.world, c.name),
        }
    }
}

#[test]
fn site_profile_matches_reference() {
    for c in PROFILES {
        let w = find_world(c.world);
        let f = build_world(w);
        let uw = urban_world(w, &f);
        // The one input the reference resolves for itself and this port takes
        // from its caller -- captured from \`_umInferWalls\` and re-derived here,
        // so a drift in \`um_wall_spec\` fails as loudly as a drift in the profile.
        let place = WallPlace {
            kind: settlement_kind(c.kind),
            pop: c.pop,
            // \`p.umWalls\` / \`p.umAge\` are both absent on every settlement the
            // reference builds until something sets one, which is the value
            // the capture ran under.
            walls_override: None,
            age_override: None,
            specialisation: None,
            fortified_trait: false,
            relative_elevation: cartalith_civ::military::civ_relative_elevation(
                &f.field, w.gw, w.gh, w.sea_level, c.px, c.py,
            ),
        };
        assert_eq!(um_infer_walls(&place), c.walled, "{}/{}: walled", c.world, c.name);
        let e = SiteProfileWorld {
            coast_dt: &f.coast_dt,
            flood: &f.flood,
            biome: &f.biome,
            temp: &f.temp,
            rain: &f.rain,
            carry_k: &f.carry,
            res: &f.pots,
            ways: &f.ways,
            world_wrap: false,
            walled: c.walled,
        };
        let sp = um_site_profile(&uw, &e, c.px, c.py)
            .unwrap_or_else(|| panic!("{}/{}: um_site_profile returned None", c.world, c.name));
        let at = |field: &str| format!("{}/{}: {field}", c.world, c.name);
        assert_eq!(sp.site_kind, c.site_kind, "{}", at("site_kind"));
        eq(&at("elevation"), sp.elevation, c.elevation);
        eq(&at("elev_n"), sp.elev_n, c.elev_n);
        eq(&at("slope_n"), sp.slope_n, c.slope_n);
        match (sp.aspect, c.aspect) {
            (Some(g), Some(want)) => eq(&at("aspect"), g, want),
            (None, None) => {}
            (g, want) => panic!("{}: got {g:?}, reference {want:?}", at("aspect")),
        }
        eq(&at("local_relief"), sp.local_relief, c.local_relief);
        eq(&at("visibility"), sp.visibility, c.visibility);
        eq(&at("coast_dist_km"), sp.coast_dist_km, c.coast_dist_km);
        eq(&at("river_dist_km"), sp.river_dist_km, c.river_dist_km);
        eq(&at("river_order"), sp.river_order, c.river_order);
        eq(&at("river_width_m"), sp.river_width_m, c.river_width_m);
        assert_eq!(sp.confluence, c.confluence, "{}", at("confluence"));
        eq(&at("floodplain"), sp.floodplain, c.floodplain);
        assert_eq!(sp.road_count, c.road_count, "{}", at("road_count"));
        assert_eq!(sp.road_types, c.road_types, "{}", at("road_types"));
        match &sp.resources {
            Some(m) => {
                assert_eq!(m.len(), c.resources.len(), "{}", at("resources.len"));
                for &(k, want) in c.resources {
                    eq(&at(&format!("resources[{k}]")), *m.get(k).unwrap_or_else(|| panic!("{}", at(k))), want);
                }
            }
            None => assert!(c.resources.is_empty(), "{}", at("resources")),
        }
        assert_eq!(sp.resources_nearby, c.resources_nearby, "{}", at("resources_nearby"));
        assert_eq!(sp.biome, c.biome, "{}", at("biome"));
        eq(&at("temp_c"), sp.temp_c, c.temp_c);
        eq(&at("rain"), sp.rain, c.rain);
        eq(&at("carry_k"), sp.carry_k, c.carry_k);
        eq(&at("defensibility"), sp.defensibility, c.defensibility);
        eq(&at("buildable_frac"), sp.buildable_frac, c.buildable_frac);
    }
}

/// The 15 keys \`_civPlaceResourceContext\` sums over -- pinned here because
/// the captured \`resources\` maps are keyed by them and a reorder or a rename
/// would otherwise pass silently.
#[test]
fn resource_keys_match_the_captured_maps() {
    let first = PROFILES
        .iter()
        .find(|c| !c.resources.is_empty())
        .expect("no profile captured a resource map");
    assert_eq!(first.resources.len(), CIV_RESOURCE_KEYS.len());
    for &(k, _) in first.resources {
        assert!(CIV_RESOURCE_KEYS.contains(&k), "captured key {k} is not in CIV_RESOURCE_KEYS");
    }
}

`;
