extends AcceptDialog
class_name PlaceEditorWindow

## `placeEditPopup` / `_civPopulatePlaceEditor` (reference 16694) --
## `PARITY_AUDIT.md` §5 item 3, `GUI_GAP_REGISTER.md` ED-03.
##
## The audit's own words: `civ_drop_settlement` created a settlement and
## nothing edited, moved or deleted one, so "a user can add a settlement they
## can never fix or undo." This is the missing editor: name (with the
## reference's own culture-aware re-roll), class, polity, population,
## economy, traits, age and walls overrides, history, focus-camera, and
## Delete.
##
## ## A window, not a right-dock context
##
## `right_dock.gd`'s Settlement context renders every field as a read-only
## `Label` and is a *summary* surface -- `civilization_workspace.gd`'s own
## `_settlement_click` already notes it has "no name field to focus". Rather
## than convert a read-only dock into an editor (and inherit its
## rebuild-on-every-selection lifecycle for a form that must not lose
## half-typed text), this follows the reference, which puts the place editor
## in its own floating popup anchored at the place. `AcceptDialog` is this
## shell's established free-floating-window vocabulary
## (`world_data_window.gd`, `travel_library_window.gd`).
##
## ## What is deliberately absent
##
## - **Category (settlement ↔ POI).** POI is not a ported concept
##   (`civ_tools_bridge.rs`'s module doc, `GUI_GAP_REGISTER.md` CV-01) -- the
##   selector would have exactly one option.
## - **`peCityPreview`** (the town-layout *thumbnail* inline in the popup,
##   register UM-03): needs a rendered layout at icon size. Its launcher
##   `peCityOpen` IS wired -- the Actions section opens `CityViewerWindow`.
## - **`_civPeConnect` ("Connect to road network")**: no
##   `civ_connect_place_to_network` binding exists; roads are produced inside
##   `generate()` and never mutated afterwards.
## - **Econ. importance / Trade volume**: `NamedSettlement` carries neither,
##   and `FactionPlace` reads both as zero. Editing a number nothing stores
##   would be a fake control.
##
## Each of those is stated in the window's own footer rather than only here,
## so a user of the product sees the same list a reader of this file does.
##
## ## Nothing draws this window; here is what it derives from instead
##
## `design/dcc-environment-2026-08-31/README.md`, verbatim: the two DCC files
## specify the shell frame and its information architecture and *"do not specify
## the dedicated windows: Faction roster, Place editor, City viewer, Data
## manager, Vault, Travel library, Asset library."* So each choice below names
## the canvas vocabulary it was derived from:
##
## - **`§`-headed sections, noun-phrase titles** — `DccTheme.header()`'s `§
##   TITLE`, the L3 sigil the DCC Environment markup uses for its own panels
##   (`§ TOOLS`, `§ LAYERS`, `§ RESULTS`, `§ PARTY FORM`, `§ BRUSH · GLOBAL`).
##   All section titles here are already that shape.
## - **The re-roll button beside the name field** — `06-phone.md` §6.7's New
##   World modal, whose dice button is the same control in the same slot: `44 ×
##   42`, radius 12. See `_build_identity`.
## - **The phone header's title/subtitle voice** — §6.6's `_moreTitle()` table.
##
## **Open, and deliberately not resolved here.** On a phone, is this a window or
## a `moreStack` sub-screen? §6.6's `_moreTitle()` answers that for **three** of
## those seven windows and no more: the Data manager, the Travel library and the
## Asset library each get a sub-screen (`data`, `travel`, `assets`, plus their
## own leaves), reached by a `nav` row on the `root` screen. There is no row for
## the Vault, and none for the place editor, the faction roster or the city
## viewer — and §6.6's own `civ` screen, which is where a settlement surface
## would sit, lists the three place tools, Landmark generation and the Journey
## Planner and nothing else. The stack exists and these three are not in it.
## That silence is not authority to rebuild them as sheets, so the window shape
## is unchanged.
##
## ## The sibling surface, and a measured disagreement
##
## `right_dock.gd`'s Settlement context draws the same entity as this window --
## Name, Class, Population, Faction -- read-only, from a **snapshot** pushed by
## `on_settlement_selected(data, index)`. This window edits the engine live.
## Nothing re-pushes that snapshot when an edit lands, so the two disagree.
##
## Measured 2026-09-05, `_pesibling_probe.gd`, seed as generated by
## `app._run_pipeline()`, 40 settlements:
##
##     PES ok    A1 (control): the engine took the edit -- engine='PROBE_RENAME_A'
##     PES FAIL  A2: the dock no longer shows the OLD name -- old='Sevjuniana' still drawn
##     PES FAIL  A3: the dock shows the NEW name -- 'PROBE_RENAME_A' absent
##     PES ok    B1: after a re-select the dock shows the new name
##     PES FAIL  C2: the dock does not still draw the deleted settlement
##
## B1 passing is what makes this a refresh gap rather than a dock that cannot
## read the field. **The fix is not in this file.** `place_changed` /
## `place_deleted` are emitted correctly; `civilization_workspace.gd` owns both
## connections (its own comment says why: it "is the one that knows how to put
## the map back in sync"), and its `_on_civ_edited` refreshes the map overlay
## and its own categories and never re-pushes the dock's snapshot. C2 is the
## worse half: after a delete the dock keeps drawing a settlement that no longer
## exists, and every action row in it is keyed to a `_settlement_index` the
## delete has just renumbered.
##
## ## Tab-strip restructuring (`lazy-riding-piglet.md` Batch A, 2026-09-21)
##
## This window was a single `§`-sectioned scrolling form until this batch. The
## owner-supplied design canvas (`design/settlement-editor-2026-09-21/Cartalith
## Settlement Editor.dc.html`, artboards 1a/1b/1e) draws a five/six-tab strip
## instead; this batch reshapes the window to match, reusing every existing
## `_build_*` function's logic **verbatim** -- only their signatures gained an
## explicit `parent: Control` so the same section-building code can be handed
## either the Overview or the Economy & notables tab's content container. No
## engine call changed. Timeline and Political history (canvas 1c/1d) are
## placeholder tabs here -- filled in Batches B and C of the same plan.
##
## **Tab placement, and the one deviation from the plan's own suggested
## default:** `_build_urban()` (age/walls, "Settlement fabric") went to
## **Overview**, not Economy & notables. The canvas's own artboard 1a draws Age
## and Walls inside its persistent "QUICK FACTS" panel beside Population/Kind/
## Faction; artboard 1b's actual content is Connections, Food shed, Trade
## ledger, Leadership (dashed) and Notable landmarks (dashed) -- nothing there
## reads as settlement fabric. This is not the "genuinely ambiguous" case the
## plan allows a default fallback for; the canvas states a placement and this
## follows it.
##
## **Tab switching reuses PE-01's own fix, not a new mechanism.** `_switch_tab()`
## calls `_commit_focused_field()` before moving `_active_tab`, exactly the way
## `open_for()` commits before moving `_index` -- because switching away from
## Overview tears the name/history fields out of the tree, and without an
## explicit pre-move commit, `_rebuilding`'s teardown guard (which exists to
## stop exactly that write) would silently drop the edit instead of losing it
## the OLD way. See `_switch_tab()`'s own comment.
##
## **Actions and the footer disclosure stay outside the tab content**, rebuilt
## on every tab switch same as everything else, because they describe the
## settlement itself rather than one tab's slice of it -- matching the canvas's
## own "Centre on map" button living in the persistent Quick Facts panel rather
## than inside any one tab.
##
## Tab switching is **not** `TabContainer` -- this shell's established avoidance
## of it (`faction_roster_window.gd`, `culture_profiles_window.gd`'s own
## `_build_phone_switcher()`, cited there over `TabContainer` explicitly) --
## and it is **one row for both desktop and phone** rather than a separate
## phone-only switcher: unlike `culture_profiles_window.gd`'s three side-by-side
## panes (which only need to collapse to sequential screens on phone), this
## window is tabbed -- mutually exclusive content -- on every form factor the
## canvas draws, so the same segmented-button row serves both, with `phone_fit`
## already flooring its buttons to the 44 dp touch target on rebuild.

var app                       ## `DccApp`
var bridge: EngineBridge

var _index := -1
var _body: VBoxContainer
var _name_edit: LineEdit
var _footer: Label
## Phone (§13). `DccWidgets.phone_window()`'s header comment carries the whole
## treatment and why; here it only decides whether the in-content header below
## exists and whether each rebuild is re-fitted for touch.
var _phone := false
var _phone_title: Label

## Emitted after any change that moves map data, so the caller can refresh
## the overlay without this file knowing how (`civilization_workspace.gd`
## owns `_refresh_civ_data`).
signal place_changed
signal place_deleted

const KIND_ORDER := ["metropolis", "capital", "city", "town", "village", "hamlet"]

## Tab strip (see this file's own top-of-file doc for the canvas citation and
## the placement rationale). Order is display order; keys are what `_active_tab`
## and `_switch_tab()` carry.
## "Layout" is placed last -- canvas 1g calls itself "THE SIXTH TAB" in its own
## artboard header, after the five Batches A-D already shipped (Overview /
## Economy & notables / Timeline / Political history / Vault notes).
const TAB_ORDER := ["overview", "economy", "timeline", "political", "vault", "layout"]
const TAB_LABELS := {
	"overview": "Overview",
	"economy": "Economy & notables",
	"timeline": "Timeline",
	"political": "Political history",
	"vault": "Vault notes",
	"layout": "Layout",
}
var _active_tab := "overview"

## Timeline tab state (`lazy-riding-piglet.md` Batch B). World-level, not
## settlement-scoped -- `civ_add_year`/`civ_goto_year`/`civ_remove_year`/
## `civ_run_collapse_simulation` all act on `CivData`'s own timeline, the same
## one every settlement's editor sees. Kept as instance state rather than
## re-read from the engine on every rebuild because a SpinBox/slider mid-edit
## must not snap back to a stale default the moment an unrelated field commits
## a rebuild -- the same reasoning `_name_edit` already needs a guard for.
var _tl_target_year := 0
var _sim_mode := "collapse"
var _sim_character := "mixed"
var _sim_severity := 0.5
var _sim_rate := 0.01
var _sim_start_year := 0
var _sim_duration := 100
var _sim_step_years := 10
## The last `civ_run_collapse_simulation` response, `{}` before any run this
## session. Holds either a `needs_confirm` gate (the canvas's own "nothing is
## written until you confirm" banner) or a completed run's report.
var _sim_last_result := {}
## The "Add authored event" form (`_build_authored_events`). Instance state for
## the same reason as `_tl_target_year`: a refused add (a conflict, a missing
## name) rebuilds the tab, and the author's typing must survive it. Text, not
## ints, for the optional fields -- an empty string IS "absent", which a
## SpinBox cannot say without inventing a plausible year. `_ae_hash` is the
## note's hash from the same rebuild that drew the event list, so a write is
## refused if the note changed after the author last saw it.
var _ae_start := 0
var _ae_end := ""
var _ae_name := ""
var _ae_desc := ""
var _ae_color := ""
var _ae_group := ""
var _ae_hash := ""
var _ae_msg := ""
var _ae_conflict := false


func setup(a, b: EngineBridge) -> void:
	app = a
	bridge = b
	title = "Place"
	size = Vector2i(400, 640)
	min_size = Vector2i(340, 420)
	## No `max_size` (2026-09-24, the vault window's `3736fe7` fix repeated). The
	## cap treated `wrap_controls` growing the window to its content, which
	## `phone_window()` below turns off at the cause; all the cap still did was
	## stop a user from making the window bigger.
	## Also turns `wrap_controls` off -- which this window shipped with on,
	## the third instance of that bug class in this shell.
	_phone = DccWidgets.phone_window(self, a)

	## One column rather than the scroll directly, so the phone header has
	## somewhere to sit. An `AcceptDialog` gives its *first* content child the
	## whole rect, so a second sibling would simply overlap this one.
	var root := VBoxContainer.new()
	root.add_theme_constant_override("separation", 0)
	add_child(root)

	var scroll := ScrollContainer.new()
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	root.add_child(scroll)
	if _phone:
		## Subtitle in §6.6 `_moreTitle()`'s voice -- lower case, `·`-separated,
		## naming the screen's contents rather than restating its title. It read
		## "settlement editor", which is the window's own name said twice; the
		## canvas's subtitles are contents lists (`files · autosave · storage`).
		_phone_title = DccWidgets.phone_head(root, "Place",
			"identity · economy · trade · traits · fabric")
	var pad := MarginContainer.new()
	for side in ["left", "top", "right", "bottom"]:
		pad.add_theme_constant_override("margin_" + side, 12)
	pad.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	scroll.add_child(pad)
	_body = VBoxContainer.new()
	_body.add_theme_constant_override("separation", 4)
	_body.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	pad.add_child(_body)

	## `GUI_GAP_REGISTER.md` **RF-02**. This window is built on `open_for()`, not
	## at launch, so §23's sweep did not reach it -- but it is keyed to a
	## settlement **index**, and a generate renumbers every index there is.
	## Left open across one it went on showing the old world's place: measured
	## `Sevjuniana` pop 19 332 at (142, 14) while the engine's settlement 0 was
	## pop 19 774 at (208, 183), the form character-for-character identical.
	## Every field here writes through `civ_edit_settlement(_index, …)`, so a
	## commit from that pane would have written the previous world's name, kind
	## and traits onto whatever now sits at the index -- PE-01's failure with a
	## generate as the trigger.
	##
	## Rebuilt rather than closed, which is the shape two other windows in this
	## shell already use for the same pair of signals (`city_viewer_window`,
	## `world_data_window`, `performance_window` all `if visible: reload`).
	## Closing would also be wrong for the ambiguous half of `world_loaded`:
	## `load_asset_pack` and `as_apply_to_map` emit it without touching a single
	## settlement.
	##
	## `_rebuild()` and not `open_for(_index)`: `open_for` commits the focused
	## field first, and committing this form against the world that has just
	## replaced the one it was typed for is the bug, not the fix. `_clear()`'s
	## `_rebuilding` guard drops it instead.
	bridge.generation_finished.connect(func(ok: bool): if ok and visible: _rebuild())
	bridge.world_loaded.connect(func(): if visible: _rebuild())


## `_civOpenPlacePopup`: opens on the settlement at `index` into
## `get_settlements()`'s own array.
func open_for(index: int) -> void:
	## PE-01: flush whatever the currently-open form has focused, against the
	## settlement it belongs to, before `_index` moves. Without this an editor
	## re-opened on a different place from the map committed the old form's
	## text onto the new one.
	_commit_focused_field()
	_index = index
	## A half-typed event, and the last add's outcome, belong to the place they
	## were typed against -- not to the next one opened.
	_ae_end = ""
	_ae_name = ""
	_ae_desc = ""
	_ae_color = ""
	_ae_group = ""
	_ae_msg = ""
	_ae_conflict = false
	## Every place opens on Overview -- the tab the name field (and §4.5.3's
	## own "focused on the name field" request, just below) lives on. Without
	## this an editor left on, say, Vault notes from the previous place would
	## reopen on Vault notes for the new one instead of the identity fields a
	## fresh open is for.
	_active_tab = "overview"
	_rebuild()
	if _index < 0:
		return
	if not DccWidgets.phone_present(self, app):
		popup_centered()
	## §4.5.3 asks for the editor to open "focused on the name field", and on a
	## pointer that costs nothing. On a phone a focused `LineEdit` raises the
	## IME, which on the device pass covered the form from Traits down before
	## the user had asked to rename anything -- so phone opens on the whole
	## form and the field takes focus when it is tapped, like every other field
	## here. Measured on the handset, not assumed.
	if _phone:
		return
	if _name_edit != null:
		## §4.5.3's own right-dock column asks for "the new settlement's
		## inspector, live, focused on the name field" -- which nothing in
		## this shell could honour until this window existed.
		_name_edit.grab_focus()
		_name_edit.select_all()


## `_rebuilding` guards the name field's `focus_exited` commit against its own
## teardown (`GUI_GAP_REGISTER.md` PE-01).
##
## §4.5.3 has `open_for()` focus the name field, so on desktop the field holds
## focus for the whole session. `_clear()` below removes it from the tree,
## which releases focus and fires `focus_exited` **synchronously** -- and that
## handler writes the field's text back through `civ_edit_settlement`. Any
## rebuild triggered by something that changed the name therefore had the OLD
## name written back over the new name before the rebuilt form ever read it.
##
## Measured, not reasoned: the ⟳ re-roll button left the engine name at
## `Yusnashharwell` across a real press with the field focused, and changed it
## to `Abedomarmarch` on the identical press with `release_focus()` called
## first. Every press after the first worked, because only `open_for()` grabs
## focus -- which is exactly why this survived to be found by a probe rather
## than by the eye.
##
## **This guard now also protects a tab switch**, since `_rebuild()` is the
## same teardown-and-rebuild path a tab switch drives -- `_switch_tab()` calls
## `_commit_focused_field()` first for the same reason `open_for()` does.
var _rebuilding := false

## Commit whatever field is focused **before** `_index` (or `_active_tab`)
## moves, so a half-typed rename lands on the settlement (or tab) it was typed
## for instead of being dropped by the guard. Releasing focus is what makes the
## `focus_exited` commit fire here, against the right index, rather than inside
## `_clear()`.
func _commit_focused_field() -> void:
	if _body == null:
		return
	var vp := _body.get_viewport()
	if vp == null:
		return
	var fo := vp.gui_get_focus_owner()
	if fo != null and _body.is_ancestor_of(fo):
		fo.release_focus()

func _clear() -> void:
	_rebuilding = true
	## Cleared BEFORE the removal as well, so a handler that reads it during
	## teardown sees no field rather than a dying one.
	_name_edit = null
	for c in _body.get_children():
		_body.remove_child(c)
		c.queue_free()
	_rebuilding = false


func _settlement() -> Dictionary:
	var all := bridge.settlements()
	if _index < 0 or _index >= all.size():
		return {}
	return all[_index]


func _rebuild() -> void:
	_clear()
	var s := _settlement()
	if s.is_empty():
		DccWidgets.note(_body, "That settlement no longer exists.")
		_index = -1
		return
	var details := bridge.civ_settlement_details(_index)
	title = "Place — %s" % String(s.get("name", "(unnamed)"))
	if _phone_title != null:
		## The window is borderless on a phone, so the title bar this used to
		## be read from is gone -- the in-content header is where it lives now.
		_phone_title.text = String(s.get("name", "(unnamed)")).to_upper()

	_build_tab_strip(_body)
	var tab_content := VBoxContainer.new()
	tab_content.add_theme_constant_override("separation", 4)
	tab_content.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_body.add_child(tab_content)
	match _active_tab:
		"overview":
			_build_identity(tab_content, s)
			_build_class_and_polity(tab_content, s)
			_build_traits(tab_content, details)
			_build_economy(tab_content, s, details)
			_build_urban(tab_content, details)
			_build_history(tab_content, details)
		"economy":
			_build_trade(tab_content)
		"timeline":
			_build_timeline(tab_content)
		"political":
			_build_political(tab_content, s)
			_build_authored_events(tab_content, s)
			_build_journey_passes(tab_content, s)
			_build_conflicts_here(tab_content, s)
		"vault":
			_build_knowledge(tab_content, s)
		"layout":
			_build_layout(tab_content, s)
		_:
			pass
	## Global to the settlement, not tab-scoped -- see this file's top-of-file
	## doc. Rebuilt every time same as the tab content, matching this window's
	## existing full-rebuild-per-change discipline.
	_build_actions(_body, s)
	_build_footer(_body)
	## Every row above comes from `dcc_widgets.gd`, which is authored in desktop
	## pixels; this floors the tappable ones at §13's 44 dp. Re-run per rebuild
	## because a rebuild makes fresh nodes, and safe to re-run because the walk
	## is idempotent (`DccShell.phone_fit`'s own meta-flag).
	if _phone:
		app.phone_fit(self, 1.0)


# -- Tab strip ----------------------------------------------------------------

## One segmented-button row for both desktop and phone -- see this file's
## top-of-file doc for why this window does not need a separate `if _phone:`
## switcher the way `culture_profiles_window.gd`'s three side-by-side panes do.
## Styling matches that file's own `_show_phone_pane()` active-tab treatment
## (accent wash fill + accent text on the active tab, dim text on the rest) so
## a segmented control looks the same wherever this shell already draws one.
func _build_tab_strip(parent: Control) -> void:
	var wrap := PanelContainer.new()
	wrap.add_theme_stylebox_override("panel", DccTheme.panel("bg", {"bottom": 1}))
	## A WRAPPING row with gaps and padding (2026-09-24). It was an
	## `HBoxContainer` at separation 0 with padless buttons, so at the window's
	## 400 px default the six labels ran together with no space between them.
	## Now a narrow window breaks the strip onto a second line instead.
	var row := HFlowContainer.new()
	row.add_theme_constant_override("h_separation", 2)
	row.add_theme_constant_override("v_separation", 2)
	wrap.add_child(row)
	for key in TAB_ORDER:
		var on: bool = key == _active_tab
		var b := Button.new()
		b.text = String(TAB_LABELS[key])
		b.focus_mode = Control.FOCUS_NONE
		b.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		b.clip_text = false
		b.add_theme_font_size_override("font_size", DccTheme.FS_TINY)
		var fill: StyleBox = DccTheme.flat(DccTheme.c("accent_wash")) if on else DccTheme.empty()
		fill.content_margin_left = 8
		fill.content_margin_right = 8
		fill.content_margin_top = 4
		fill.content_margin_bottom = 4
		for sb_name in ["normal", "hover", "pressed"]:
			b.add_theme_stylebox_override(sb_name, fill)
		b.add_theme_stylebox_override("focus", DccTheme.empty())
		b.add_theme_color_override("font_color",
			DccTheme.c("accent") if on else DccTheme.c("text_dim"))
		b.pressed.connect(func(): _switch_tab(key))
		row.add_child(b)
	parent.add_child(wrap)


## The PE-01 fix, applied to a tab move instead of an index move -- see this
## file's top-of-file doc and `_rebuilding`'s own comment. `_rebuild()`'s
## teardown removes the currently-focused field (if the active tab holds one)
## from the tree, firing `focus_exited` under the `_rebuilding` guard -- which
## exists specifically to make that fire a no-op, not a write. Without this
## call landing FIRST, a half-typed name commit at tab-switch time would be
## silently dropped by the same guard that protects a re-roll or a generate.
func _switch_tab(tab: String) -> void:
	if tab == _active_tab:
		return
	_commit_focused_field()
	_active_tab = tab
	_rebuild()


# -- Timeline / Political history placeholders ---------------------------------

## Canvas `1c` (`design/settlement-editor-2026-09-21/Cartalith Settlement
## Editor.dc.html`): "The mockup drew a hand-authored event log. The engine
## has something better and different: recorded years you can scrub, and a
## collapse/recovery simulator that writes them." World-level, not
## settlement-scoped -- see `_tl_target_year`'s own doc comment above.
##
## **Mode/Character use `DccWidgets.choice()`, not the canvas's own segmented
## row.** Every other enumerated picker in this file (Class, Polity, Economy,
## Walls) already goes through `choice()`; a bespoke segmented-button pair for
## these two alone would be a second, untested pattern for the same job the
## tab strip above already solved. Recorded as a divergence, the same way
## `_build_identity`'s re-roll glyph records its own.
func _build_timeline(parent: Control) -> void:
	var years: PackedInt64Array = bridge.get_civ_timeline_years()
	var cursor := bridge.get_civ_year()

	# -- Recorded years scrubber --------------------------------------------
	var sec := DccWidgets.section(parent, "Recorded years")
	if years.is_empty():
		DccWidgets.note(sec, "No recorded years yet. Add one below to start the timeline.")
	else:
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 4)
		for y in years:
			var on := int(y) == cursor
			DccWidgets.chip(row, "y%d" % int(y), func():
				bridge.civ_goto_year(int(y))
				place_changed.emit()
				_rebuild(), on)
		sec.add_child(row)
	DccWidgets.note(sec, "Cursor: year %d." % cursor)

	DccWidgets.number(sec, "Year", -100000.0, 100000.0, 1.0, float(_tl_target_year),
		func(v: float): _tl_target_year = int(v))
	var btn_row := HBoxContainer.new()
	btn_row.add_theme_constant_override("separation", 6)
	DccWidgets.action(btn_row, "Add year", func():
		bridge.civ_add_year(_tl_target_year)
		place_changed.emit()
		_rebuild())
	DccWidgets.action(btn_row, "Go to year", func():
		bridge.civ_goto_year(_tl_target_year)
		place_changed.emit()
		_rebuild())
	DccWidgets.action(btn_row, "Remove", func():
		bridge.civ_remove_year(_tl_target_year)
		place_changed.emit()
		_rebuild())
	sec.add_child(btn_row)

	## `civ_year_diff` diffs `year` against the chronologically previous
	## recorded year (`timeline_bridge.rs`'s own doc comment) -- there is no
	## "changed" set in the returned dictionary (only tid membership), so this
	## reports what the engine actually returns rather than inventing the
	## canvas's own "N changed" figure it has no data for.
	var diff := bridge.civ_year_diff(cursor)
	var present: PackedInt64Array = diff.get("present", PackedInt64Array())
	var added: PackedInt64Array = diff.get("added", PackedInt64Array())
	var removed: PackedInt64Array = diff.get("removed", PackedInt64Array())
	DccWidgets.note(sec, "Diff vs. the previous recorded year: %d present · %d added · %d removed."
		% [present.size(), added.size(), removed.size()])

	# -- Collapse / recovery simulator --------------------------------------
	var sim := DccWidgets.section(parent, "Collapse / recovery simulation")
	DccWidgets.choice(sim, "Mode", ["Collapse", "Recovery"],
		0 if _sim_mode == "collapse" else 1,
		func(i: int): _sim_mode = "collapse" if i == 0 else "recovery")
	DccWidgets.choice(sim, "Character", ["Mixed", "Trade", "Disease", "Conflict"],
		["mixed", "trade", "disease", "conflict"].find(_sim_character),
		func(i: int): _sim_character = ["mixed", "trade", "disease", "conflict"][i],
		"Collapse mode only -- ignored in Recovery.")
	DccWidgets.slider(sim, "Severity", 0.0, 100.0, 1.0, _sim_severity * 100.0, "%",
		func(v: float): _sim_severity = v / 100.0,
		"Collapse mode only -- fraction of the stress applied per step.")
	DccWidgets.slider(sim, "Rate", 0.0, 10.0, 0.1, _sim_rate * 100.0, "%/yr",
		func(v: float): _sim_rate = v / 100.0,
		"Recovery mode only -- regrowth rate per year.")
	DccWidgets.number(sim, "Start year", -100000.0, 100000.0, 1.0, float(_sim_start_year),
		func(v: float): _sim_start_year = int(v))
	DccWidgets.number(sim, "Duration (yr)", 1.0, 100000.0, 1.0, float(_sim_duration),
		func(v: float): _sim_duration = int(v))
	DccWidgets.number(sim, "Step (yr)", 1.0, 10000.0, 1.0, float(_sim_step_years),
		func(v: float): _sim_step_years = int(v))
	DccWidgets.action(sim, "Run simulation", func(): _run_collapse_sim(false))

	if bool(_sim_last_result.get("needs_confirm", false)):
		var clobber: PackedInt64Array = _sim_last_result.get("clobber_years", PackedInt64Array())
		var years_str: Array = []
		for y in clobber:
			years_str.append("y%d" % int(y))
		var warn := PanelContainer.new()
		warn.add_theme_stylebox_override("panel", DccWidgets.box("accent", "accent_wash", 10, 9))
		var warn_col := VBoxContainer.new()
		warn_col.add_theme_constant_override("separation", 6)
		warn.add_child(warn_col)
		DccWidgets.note(warn_col, "This run would overwrite %d recorded year%s -- %s. Nothing is "
			% [clobber.size(), "" if clobber.size() == 1 else "s", ", ".join(years_str)]
			+ "written until you confirm.")
		DccWidgets.action(warn_col, "Run & overwrite", func(): _run_collapse_sim(true))
		sim.add_child(warn)
	elif bool(_sim_last_result.get("ok", false)):
		var rep := DccWidgets.group(sim, "Run report")
		var grid := HBoxContainer.new()
		grid.add_theme_constant_override("separation", 16)
		_report_stat(grid, "STEPS", str(int(_sim_last_result.get("steps", 0))))
		_report_stat(grid, "END YEAR", str(int(_sim_last_result.get("end_year", 0))))
		_report_stat(grid, "DIED", str(int(_sim_last_result.get("died", 0))))
		_report_stat(grid, "MIGRATED", str(int(_sim_last_result.get("migrated", 0))))
		_report_stat(grid, "UNPLACED", str(int(_sim_last_result.get("unplaced", 0))))
		_report_stat(grid, "FAILED", str(int(_sim_last_result.get("failed", 0))))
		_report_stat(grid, "GREW", str(int(_sim_last_result.get("grew", 0))))
		_report_stat(grid, "SETTLEMENTS", str(int(_sim_last_result.get("final_settlements", 0))))
		rep.add_child(grid)
	elif _sim_last_result.has("error"):
		DccWidgets.note(sim, "Run refused: %s" % String(_sim_last_result.get("error", "")))

	# -- Authored events (canvas's own dashed panel) -------------------------
	## This tab is world-level; an authored event belongs to one settlement, so
	## the events themselves are read on the Political history tab
	## (`_build_authored_events`). The note that stood here argued for a new
	## event store; Ruling AM put them in the settlement's own vault note instead.
	var ev := DccWidgets.section(parent, "Authored events")
	DccWidgets.note(ev, "Per settlement: written as a ```chronos block in the settlement's own "
		+ "vault note and shown on its Political history tab.")


## One `civ_run_collapse_simulation` call, then a rebuild so the confirmation
## banner or the report reads the fresh response. `confirm` re-sends the same
## drafted request with `confirm_overwrite` set, matching the bridge's own
## documented re-send-to-proceed protocol (`timeline_bridge.rs`'s
## `CollapseSimRequest::confirm_overwrite` doc comment).
func _run_collapse_sim(confirm: bool) -> void:
	var request := {
		"mode": _sim_mode,
		"character": _sim_character,
		"severity": _sim_severity,
		"rate": _sim_rate,
		"start_year": _sim_start_year,
		"duration": _sim_duration,
		"step_years": _sim_step_years,
		"confirm_overwrite": confirm,
	}
	_sim_last_result = bridge.civ_run_collapse_simulation(request)
	if bool(_sim_last_result.get("ok", false)):
		place_changed.emit()
	_rebuild()


func _report_stat(parent: Control, key: String, value: String) -> void:
	var col := VBoxContainer.new()
	col.add_theme_constant_override("separation", 2)
	col.add_child(DccTheme.mono_label(key, "text_faint", DccTheme.FS_MICRO, 1))
	col.add_child(DccTheme.mono_label(value, "text", DccTheme.FS_SMALL))
	parent.add_child(col)


## `lazy-riding-piglet.md` Batch C: derived ownership periods over this
## settlement's recorded `TimelineSnapshot`s, via the new
## `civ_settlement_ownership_periods` bridge call -- **read-only**, matching
## artboard 1d (`Cartalith Settlement Editor.dc.html`, `id="1d"`): the canvas
## draws no edit affordance for a derived stacked bar or period table, only
## for the SEPARATE "manual political entries" panel, which stays dashed
## below.
##
## A stacked ownership bar (proportional segments by faction, each in that
## faction's own `get_factions()` colour) plus the period list underneath --
## the canvas's own two 1d elements. Proportions are drawn against the
## timeline's own latest recorded year (not "now" in any real-world sense --
## this settlement's own timeline has no other reference point), so an open
## final span reaches the right edge of the bar exactly as far as its own
## recorded years justify.
##
## Also builds the population/tier trajectory sub-section
## (`OUTSTANDING_WORK.md` §2.3 SP-3, the small/additive/shovel-ready piece):
## a plain per-recorded-year list, not another stacked bar -- see the
## section's own comment below for why it stays flat rather than collapsing
## into tier-change spans the way ownership does.
func _build_political(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Political history")
	var tid := int(s.get("tid", 0))
	var periods: Array = bridge.civ_settlement_ownership_periods(tid)
	if periods.is_empty():
		DccWidgets.note(sec, "No recorded ownership history yet -- derived from the Timeline "
			+ "tab's own recorded years. Add a year (or run a collapse/recovery simulation) to "
			+ "build one.")
	else:
		var colors := {}   ## faction id (int) -> Color, from get_factions()
		var names := {}    ## faction id (int) -> String
		for f in bridge.get_factions():
			var fd: Dictionary = f
			var fid := int(fd.get("id", 0))
			colors[fid] = Color8(int(fd.get("color_r", 150)), int(fd.get("color_g", 150)),
				int(fd.get("color_b", 150)))
			names[fid] = String(fd.get("name", "Faction %d" % fid))

		# -- Stacked bar ------------------------------------------------------
		var earliest := int((periods[0] as Dictionary).get("start_year", 0))
		var latest := earliest
		for p in periods:
			var pd: Dictionary = p
			var end_y := int(pd.get("end_year", latest)) if not bool(pd.get("current", false)) else latest
			latest = maxi(latest, end_y)
		# A still-current final span (or a single-year timeline) has no span
		# of its own to measure -- floor the total width at 1 year so the bar
		# never divides by zero.
		var total_years := maxi(1, latest - earliest)

		var bar := HBoxContainer.new()
		bar.custom_minimum_size.y = 22
		bar.add_theme_constant_override("separation", 1)
		for p in periods:
			var pd: Dictionary = p
			var fid := int(pd.get("faction_id", 0))
			var start_y := int(pd.get("start_year", earliest))
			var current := bool(pd.get("current", false))
			var end_y := latest if current else int(pd.get("end_year", start_y))
			var seg := ColorRect.new()
			seg.color = colors.get(fid, DccTheme.c("sunken"))
			seg.size_flags_horizontal = Control.SIZE_EXPAND_FILL
			seg.size_flags_stretch_ratio = maxf(0.02, float(end_y - start_y) / float(total_years))
			seg.tooltip_text = "%s · %d – %s" % [names.get(fid, "Faction %d" % fid), start_y,
				"present" if current else str(end_y)]
			bar.add_child(seg)
		sec.add_child(bar)

		# -- Period list --------------------------------------------------------
		var list := DccWidgets.group(sec, "Ownership periods", true)
		for p in periods:
			var pd: Dictionary = p
			var fid := int(pd.get("faction_id", 0))
			var current := bool(pd.get("current", false))
			var row := HBoxContainer.new()
			row.add_theme_constant_override("separation", 8)
			var sw := ColorRect.new()
			sw.color = colors.get(fid, DccTheme.c("sunken"))
			sw.custom_minimum_size = Vector2(12, 12)
			row.add_child(sw)
			var range_str := "%d – present" % int(pd.get("start_year", 0)) if current \
				else "%d – %d" % [int(pd.get("start_year", 0)), int(pd.get("end_year", 0))]
			row.add_child(DccTheme.mono_label(range_str, "text", DccTheme.FS_SMALL))
			row.add_child(DccTheme.mono_label(names.get(fid, "Faction %d" % fid), "text_dim",
				DccTheme.FS_SMALL))
			list.add_child(row)

	# -- Population/tier trajectory (SP-3, the additive piece) ----------------
	# `civ_settlement_population_trajectory`'s own doc comment: flat per
	# recorded year the settlement was present in, NOT collapsed into
	# tier-change spans like the ownership bar above -- population moves
	# almost every recorded year, so a reader needs every point, not just
	# the years a tier boundary was crossed. Kept as a plain list (this
	# shell has no chart widget to reuse yet, `MISTAKES.md`'s "don't add a
	# helper because the other one is unreachable" rule applies the same way
	# to charting infrastructure as to formatters).
	var traj_sec := DccWidgets.section(parent, "Population & tier trajectory")
	var traj_points: Array = bridge.civ_settlement_population_trajectory(tid)
	if traj_points.is_empty():
		DccWidgets.note(traj_sec, "No recorded population history yet -- derived from the Timeline "
			+ "tab's own recorded years. Add a year (or run a collapse/recovery simulation) to "
			+ "build one.")
	else:
		var traj_list := DccWidgets.group(traj_sec, "Recorded years", true)
		var prev_kind := ""
		var prev_status := ""
		var any_unrecorded := false
		for pt in traj_points:
			var pd: Dictionary = pt
			var kind := String(pd.get("kind", ""))
			var row := HBoxContainer.new()
			row.add_theme_constant_override("separation", 8)
			row.add_child(DccTheme.mono_label(str(int(pd.get("year", 0))), "text", DccTheme.FS_SMALL))
			row.add_child(DccTheme.mono_label(FactionRosterWindow._thousands(int(pd.get("pop", 0))),
				"text", DccTheme.FS_SMALL))
			# Dimmed when the tier is unchanged from the row above, so a tier
			# CHANGE (the moment a reader actually cares about) stands out
			# without collapsing the underlying per-year data the way the
			# ownership bar collapses same-faction years into one span.
			row.add_child(DccTheme.mono_label(kind.capitalize(),
				"text" if kind != prev_kind else "text_dim", DccTheme.FS_SMALL))
			# Ruins/fortified, fourth column. The keys exist only for a year a
			# collapse/recovery run wrote (`TimelineSnapshot::collapse_flags`);
			# otherwise the column is a dash with its reason, never "standing",
			# because nothing recorded that. Dimmed when unchanged from the row
			# above, the same rule as the tier column.
			var status := "—"
			if pd.has("ruins"):
				var parts: Array[String] = []
				if bool(pd.get("ruins", false)):
					parts.append("ruins")
				if bool(pd.get("fortified", false)):
					parts.append("fortified")
				status = " · ".join(parts) if not parts.is_empty() else "standing"
			else:
				any_unrecorded = true
			var status_l := DccTheme.mono_label(status,
				"text" if status != prev_status and status != "—" else "text_dim", DccTheme.FS_SMALL)
			if status == "—":
				status_l.mouse_filter = Control.MOUSE_FILTER_PASS
				status_l.tooltip_text = "Not recorded: this year was not written by a collapse/recovery run."
			row.add_child(status_l)
			traj_list.add_child(row)
			prev_kind = kind
			prev_status = status
		if any_unrecorded:
			DccWidgets.note(traj_sec, "— in the last column: ruins/fortified not recorded. Only a "
				+ "collapse/recovery run records them, and a project reload does not keep them.")

	# -- Manual political entries (canvas's own dashed panel) -----------------
	var man := DccWidgets.section(parent, "Manual political entries")
	DccWidgets.note(man, "Dashed in the canvas, and left dashed here for the canvas's own stated "
		+ "reason: a hand-authored political period has no precedence rule against the derived "
		+ "ones above -- if the two disagreed over the same years, nothing says which wins. Not "
		+ "built: that rule does not exist yet.")


# -- Journey passes (SP-3's third mark) ---------------------------------------

## `STORY_PLANNING_SCOPE.md` SP-3: "Journeys from SP-2 that pass through the
## settlement appear as a third mark." Read-only rows in the authored-events
## row shape (swatch, date, name), from `civ_settlement_journey_passes` --
## the Journey Planner's own stop test, dated off the same plan the map's
## journey marker moves along. The swatch is the accent colour, one for every
## journey: a saved journey has no colour of its own. A journey with no
## honest date (a blocked plan) still lists, with its reason in place of one.
func _build_journey_passes(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Journeys passing")
	var tid := int(s.get("tid", 0))
	if tid == 0:
		DccWidgets.note(sec, "This settlement has no stable id yet, so no journey can be matched to it.")
		return
	var passes: Array = bridge.civ_settlement_journey_passes(tid)
	var conflicts: Array = bridge.conflicts_touching_settlement(tid)
	if passes.is_empty():
		DccWidgets.note(sec, "No saved journey passes here. Save one from the Journey Planner; it "
			+ "lists here when its route comes within the planner's stop radius of this settlement.")
		return
	for p in passes:
		var pd: Dictionary = p
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 8)
		var sw := ColorRect.new()
		sw.custom_minimum_size = Vector2(12, 12)
		sw.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		sw.color = DccTheme.c("accent")
		row.add_child(sw)
		row.add_child(DccTheme.mono_label(String(pd.get("date", "—")), "text", DccTheme.FS_SMALL))
		var name_l := DccTheme.mono_label(String(pd.get("name", "")), "text_dim", DccTheme.FS_SMALL)
		name_l.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		name_l.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		row.add_child(name_l)
		row.tooltip_text = "Departed %s · %s" % [String(pd.get("departure", "")),
			String(pd.get("party_preset", ""))]
		sec.add_child(row)
		if pd.has("error"):
			DccWidgets.note(sec, "Undated: %s." % String(pd.get("error", "")))
		## SP-5 (a): the pass's year against the conflicts that touched this
		## place (`_build_conflicts_here`'s own set). Undated passes have no
		## year to compare, so say nothing rather than guess.
		elif pd.has("year"):
			var during: Array = []
			for c in conflicts:
				var cd: Dictionary = c
				var y := int(pd.get("year", 0))
				if y >= int(cd.get("start_year", 0)) and (not cd.has("end_year") or y <= int(cd.get("end_year", 0))):
					during.append("%s (%s)" % [_conflict_title(cd), _conflict_years(cd)])
			if not during.is_empty():
				DccWidgets.note(sec, "Passing during: %s." % "; ".join(during))


# -- Conflicts here (SP-5) ------------------------------------------------------

## `STORY_PLANNING_SCOPE.md` SP-5 (b): "a settlement's strip shows the
## conflicts that touched it" -- every conflict attached to this settlement or
## to the province it lies in (`bridge.conflicts_touching_settlement`, keyed on
## `tid`), in the journey-pass row shape: swatch (the map's conflict ink), year
## range, name. Read-only; conflicts are drawn and edited in CIVIL.
const _CONFLICT_INK: Color = preload("res://map_overlay.gd").CONFLICT_COLOR

func _build_conflicts_here(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Conflicts here")
	var tid := int(s.get("tid", 0))
	if tid == 0:
		DccWidgets.note(sec, "This settlement has no stable id yet, so no conflict can be matched to it.")
		return
	var conflicts: Array = bridge.conflicts_touching_settlement(tid)
	if conflicts.is_empty():
		DccWidgets.note(sec, "No conflict is attached here. A conflict drawn in CIVIL lists here when "
			+ "it is attached to this settlement or to its province.")
		return
	for c in conflicts:
		var cd: Dictionary = c
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 8)
		var sw := ColorRect.new()
		sw.custom_minimum_size = Vector2(12, 12)
		sw.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		sw.color = _CONFLICT_INK
		row.add_child(sw)
		row.add_child(DccTheme.mono_label(_conflict_years(cd), "text", DccTheme.FS_SMALL))
		var title := _conflict_title(cd)
		if String(cd.get("via", "")) == "province":
			title += "  (%s)" % String(cd.get("anchor_name", "province"))
		var name_l := DccTheme.mono_label(title, "text_dim", DccTheme.FS_SMALL)
		name_l.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		name_l.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		row.add_child(name_l)
		if not String(cd.get("outcome", "")).is_empty():
			row.tooltip_text = "Outcome: %s" % String(cd.get("outcome", ""))
		sec.add_child(row)


func _conflict_years(cd: Dictionary) -> String:
	var yr := str(int(cd.get("start_year", 0)))
	return yr + (" – %d" % int(cd.get("end_year", 0)) if cd.has("end_year") else " – ongoing")


func _conflict_title(cd: Dictionary) -> String:
	var n := String(cd.get("name", ""))
	return n if not n.is_empty() else "Unnamed %s" % String(cd.get("kind", "conflict"))


# -- Authored events (SP-3, Ruling AM) ----------------------------------------

## `STORY_PLANNING_SCOPE.md` SP-3's "authored events from §3 on the same
## track": dated entries the author wrote in this settlement's own vault note,
## as a ```chronos block in the Chronos Timeline Obsidian plugin's exact
## syntax (Ruling AM), read through `bridge.vault_entity_chronos` and listed by
## start year. The list is read-only; `_build_add_event_form` below it writes a
## NEW event into the note as one Chronos line (`cartalith_vault::chronos::
## to_line`), so the author never types the syntax. Existing lines are edited
## in the vault (Obsidian, or the Vault window's own editor), not here.
##
## A separate function, not a section inside `_build_political`, so it merges
## cleanly beside the population/tier trajectory that SP-3's other piece adds
## to that tab concurrently.
func _build_authored_events(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Authored events")
	var tid := int(s.get("tid", 0))
	if tid == 0:
		DccWidgets.note(sec, "This settlement has no stable id yet, so no vault note can be linked to it.")
		return
	var got := bridge.vault_entity_chronos("settlement", tid)
	if not bool(got.get("ok", false)):
		DccWidgets.note(sec, "Could not read authored events: %s" % String(got.get("error", "")))
		return
	var notes: Array = got.get("notes", [])
	var events: Array = got.get("events", [])
	if notes.is_empty():
		DccWidgets.note(sec, "No vault note linked (Vault notes tab). Authored events are written "
			+ "in the settlement's note as a ```chronos block, one \"- [year] Name | Description\" per line.")
		return
	if events.is_empty():
		DccWidgets.note(sec, "No events: the linked note%s ha%s no ```chronos block with a readable "
			% ["" if notes.size() == 1 else "s", "s" if notes.size() == 1 else "ve"]
			+ "line. Add one below.")
	for e in events:
		var ed: Dictionary = e
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 8)
		var sw := ColorRect.new()
		sw.custom_minimum_size = Vector2(12, 12)
		sw.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		## Chronos' named colours (`red`) and hex (`ff8800`, its `#` already
		## stripped) are both a Godot colour string; no colour, or one Godot
		## does not know, keeps the neutral swatch.
		sw.color = Color.from_string(String(ed.get("color", "")), DccTheme.c("sunken"))
		row.add_child(sw)
		var yr := str(int(ed.get("start", 0)))
		if ed.has("end"):
			yr += " – %d" % int(ed.get("end", 0))
		row.add_child(DccTheme.mono_label(yr, "text", DccTheme.FS_SMALL))
		var title := String(ed.get("name", ""))
		if ed.has("group"):
			title = "%s · %s" % [String(ed.get("group", "")), title]
		var kind := String(ed.get("kind", "event"))
		if kind != "event":
			title += "  (%s)" % kind
		var name_l := DccTheme.mono_label(title, "text_dim", DccTheme.FS_SMALL)
		name_l.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		name_l.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		row.add_child(name_l)
		sec.add_child(row)
		if ed.has("description"):
			DccWidgets.note(sec, String(ed.get("description", "")))
	var skipped := 0
	for n in notes:
		var nd: Dictionary = n
		skipped += (nd.get("skipped", PackedStringArray()) as PackedStringArray).size()
		if not bool(nd.get("live", true)):
			DccWidgets.note(sec, "%s: read from the saved copy -- the vault is not connected."
				% String(nd.get("rel", "")))
	if skipped > 0:
		var warn := DccWidgets.note(sec, "%d line%s in the chronos block%s could not be read and %s skipped."
			% [skipped, "" if skipped == 1 else "s", "" if notes.size() == 1 else "s",
			"was" if skipped == 1 else "were"])
		var lines: Array = []
		for n in notes:
			for l in (n as Dictionary).get("skipped", PackedStringArray()):
				lines.append(String(l))
		warn.tooltip_text = "\n".join(lines)
	_build_add_event_form(sec, notes)


## "Add event": input fields that compose one Chronos line and append it to the
## settlement's note (`vault_add_chronos_event`). The note is the first LIVE
## linked note -- a saved copy cannot be written, and writing to one of several
## notes needs a choice, so the target is named on screen rather than implied.
## The write is guarded by `_ae_hash`, read in this same rebuild: if the note
## changed after the list above was drawn, nothing is written, the author is
## told, and the rebuild shows the note as it now is.
func _build_add_event_form(sec: Control, notes: Array) -> void:
	var rel := ""
	for n in notes:
		if bool((n as Dictionary).get("live", false)):
			rel = String((n as Dictionary).get("rel", ""))
			break
	var g := DccWidgets.group(sec, "Add event", true)
	if rel == "":
		DccWidgets.note(g, "Connect the vault to add events -- the linked note is only readable "
			+ "from its saved copy.")
		return
	var read := bridge.vault_read_file_for_edit(rel)
	if not bool(read.get("ok", false)):
		DccWidgets.note(g, "Cannot add events: %s" % String(read.get("error", "")))
		return
	_ae_hash = String(read.get("hash", ""))
	DccWidgets.number(g, "Year", -100000.0, 100000.0, 1.0, float(_ae_start),
		func(v: float): _ae_start = int(v),
		"Negative years are valid Chronos (e.g. -250).")
	_ae_field(g, "End year", _ae_end, "blank = a single year", func(t: String): _ae_end = t)
	_ae_field(g, "Name", _ae_name, "required", func(t: String): _ae_name = t)
	_ae_field(g, "Description", _ae_desc, "optional", func(t: String): _ae_desc = t)
	_ae_field(g, "Colour", _ae_color, "optional: red, blue, ff8800", func(t: String): _ae_color = t)
	_ae_field(g, "Group", _ae_group, "optional", func(t: String): _ae_group = t)
	if _ae_msg != "":
		var m := DccWidgets.note(g, _ae_msg)
		if _ae_conflict or _ae_msg.begins_with("Not added"):
			m.add_theme_color_override("font_color", DccTheme.c("accent"))
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 6)
	g.add_child(row)
	DccWidgets.action(row, "Add event", func(): _submit_event(rel), true)
	DccWidgets.note(g, "Appended to %s's ```chronos block (one is created if the note has none), "
		% rel + "in the Chronos Timeline plugin's own syntax, so the note still draws in Obsidian.")


func _ae_field(parent: Control, label_text: String, value: String, placeholder: String,
		on_change: Callable) -> LineEdit:
	var row := DccWidgets._row(parent, label_text, "")
	var le := LineEdit.new()
	le.text = value
	le.placeholder_text = placeholder
	le.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	DccWidgets.well(le)
	le.text_changed.connect(on_change)
	row.add_child(le)
	return le


func _submit_event(rel: String) -> void:
	var ev := {"start": _ae_start, "name": _ae_name.strip_edges()}
	var end_t := _ae_end.strip_edges()
	if end_t != "":
		if not end_t.is_valid_int():
			_ae_conflict = false
			_ae_msg = "Not added: the end year must be a whole number, or blank for a single year."
			_rebuild()
			return
		ev["end"] = int(end_t)
	var desc := _ae_desc.strip_edges()
	if desc != "":
		ev["description"] = desc
	## Chronos writes the colour as `#red`; the `#` is the syntax, not the value.
	var col := _ae_color.strip_edges().trim_prefix("#")
	if col != "":
		ev["color"] = col
	var grp := _ae_group.strip_edges()
	if grp != "":
		ev["group"] = grp
	var r := bridge.vault_add_chronos_event(rel, _ae_hash, ev)
	_ae_conflict = bool(r.get("conflict", false))
	if bool(r.get("ok", false)):
		_ae_msg = "Added \"%s\" to %s." % [ev["name"], rel.get_file()]
		_ae_name = ""
		_ae_desc = ""
		_ae_end = ""
	elif _ae_conflict:
		_ae_msg = ("Not added: %s changed outside Cartalith after this list was drawn, so nothing "
			+ "was written. The list above now shows the note as it is -- check it, then press "
			+ "Add event again.") % rel.get_file()
	else:
		_ae_msg = "Not added: %s" % String(r.get("error", ""))
	_rebuild()


# -- Layout (`lazy-riding-piglet.md` Batch E, 2026-09-21) --------------------

## Canvas `1g` (`design/settlement-editor-2026-09-21/Cartalith Settlement
## Editor.dc.html`): a readout over `urban_bridge.rs`'s `bridge.urban_layouts()`
## -- fact chips, a street-class breakdown bar, the stages-that-ran checklist,
## the "not generated -- no key emitted" dashed list, substrate flags, and two
## real inputs (Population/Age) the canvas frames as "the same fields as
## Overview". Access pattern matched to the two existing callers rather than
## invented here: `city_viewer_window.gd::_reload()` and
## `right_dock.gd::_build_settlement_layout()` both call
## `bridge.urban_layouts(PackedInt32Array([_index]))` and take `got[0]`; this
## does the same.
##
## **The canvas's own claim about what the bridge withholds is stale, and this
## does not repeat it.** Its 1g intro says the bridge "emits no key at all for
## buildings, districts, amenities or the wall circuit". Read at the symbol
## (`urban_bridge.rs::layout_dict`, every `d.set(...)` call, 2026-09-21):
## `"buildings"`/`"building_district"`/`"building_courtyard"`/`"building_tone"`,
## `"parcel_district"`, `"markets"`/`"market_centers"`/`"market_names"`
## (the amenities that exist), and `"walls"`/`"wall_ring"`/`"wall_gates"` are
## all present keys -- none of those four is withheld today. What
## `layout_dict` genuinely never sets, per its own module doc comment on
## `urban_layouts()` ("Two things the reference's model carries are still not
## surfaced here"), is **the civic hall and places of worship**
## (`cartalith_urban::Town::civic`, and the games buildings beside it).
## `LAYOUT_ABSENT` below is that verified entry, not the canvas's four. (The
## hinterland clutter was the second entry until 2026-09-23, when it started
## crossing as `"detail_kind"`/`"detail_geom"`/... and being drawn.)
##
## **Population/Age are omitted here, not shown read-only.** The canvas frames
## them as "the same field as Overview" and "also Overview" -- i.e. not a
## second control, a second *view*. This window's own working discipline
## (`_build_actions`'s footer, `_build_political`'s dashed panel) is to state a
## gap rather than half-build it; a read-only duplicate here would be a second
## surface for one piece of state with no refresh link between them, the exact
## defect class `right_dock.gd`'s "sibling surface" doc comment above already
## measured for this window against the dock. A one-line pointer costs nothing
## and cannot drift.
##
## **No "Regenerate layout" button here -- it lives in the City Viewer's Town
## plan (Ruling J, 2026-09-23), where the plan it changes is on screen, as a
## per-settlement `variant` re-seed.** The reasoning below is why a plain
## re-run could not be the button: `urban_layouts()`
## has no cache to invalidate -- it re-runs `cartalith_urban::generate()` from
## the world's current substrate on every call (no `_umModelCache` equivalent
## anywhere in this call path, per its own doc comment), so this tab already
## shows a freshly generated layout every time `_rebuild()` runs it, which
## includes every tab switch onto it. A button that reruns the same call the
## tab just ran would be inert.
##
## **The Rules link opens `GenerationRulesWindow`** (Batch F, landed) --
## world-level, so editing it from here affects every settlement's layout,
## not just this one; the tooltip says so.
##
## **Empty state.** `urban_layouts()`'s own doc comment gives two real,
## distinct reasons for an empty return that this call site cannot tell
## apart: "empty on a loaded save or before the first generate()" (no
## substrate rasters to build streets from) and a settlement whose site is
## open water (`_umModelFor`'s own refusal -- skipped, not errored). Both are
## stated together rather than one guessed; inventing a specific cause the
## bridge does not report would be worse than naming both (MISTAKES.md's
## "dash a field with a reason" entry).
func _build_layout(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Layout")
	var got: Array = bridge.urban_layouts(PackedInt32Array([_index]))
	if got.is_empty():
		DccWidgets.note(sec,
			"No layout for this settlement right now. Two real reasons, and this bridge call "
			+ "cannot tell which applies: the world was opened from a save without its hydrology and tectonic rasters (a legacy .zip, or a project saved before 2026-09-24), which carries "
			+ "no flow rasters to build streets from; or this settlement's site sits in "
			+ "open water, which urban_layouts() skips rather than errors on (_umModelFor's "
			+ "own refusal -- there is no shore to build). Regenerate the world, or open a "
			+ "settlement with dry ground under it.")
		return
	var l: Dictionary = got[0]

	# -- Fact chips -----------------------------------------------------------
	var flow := HFlowContainer.new()
	flow.add_theme_constant_override("h_separation", 6)
	flow.add_theme_constant_override("v_separation", 6)
	var blocks_n := (l.get("blocks", []) as Array).size()
	var parcels_n := (l.get("parcels", []) as Array).size()
	var facts := [
		["site", String(l.get("site_kind", "?"))],
		["box", "%d × %d m" % [int(l.get("wm", 0)), int(l.get("hm", 0))]],
		["orient", "%.2f rad" % float(l.get("orient", 0.0))],
		["edges", str(int(l.get("edge_count", 0)))],
		["blocks", str(blocks_n)],
		["parcels", str(parcels_n)],
	]
	for f in facts:
		flow.add_child(_fact_chip(String(f[0]), String(f[1])))
	sec.add_child(flow)

	# -- Street-class breakdown ------------------------------------------------
	var streets: Dictionary = l.get("streets", {})
	var placed_m := float(l.get("street_len_m", 0.0))
	var target_m := float(l.get("target_len_m", 0.0))
	var net := DccWidgets.group(sec, "Street network", true)
	DccWidgets.note(net, "Placed %s m of %s m target." % [
		FactionRosterWindow._thousands(int(round(placed_m))),
		FactionRosterWindow._thousands(int(round(target_m)))])
	## Per-class length is not a field this dictionary carries -- `street_len_m`
	## is the total off `computeMetrics`, measured once on the whole graph.
	## Summed here from the class's own `PackedVector2Array` (A,B,A,B... segment
	## pairs, already in local box metres per `layout_dict`'s own comment on
	## `"streets"`, so a raw `distance_to` needs no scale conversion).
	var cls_len := {}
	var cls_total := 0.0
	for cls in _STREET_CLASS_ORDER:
		var pts: PackedVector2Array = streets.get(cls, PackedVector2Array())
		var length := 0.0
		var i := 0
		while i + 1 < pts.size():
			length += pts[i].distance_to(pts[i + 1])
			i += 2
		if length > 0.0:
			cls_len[cls] = length
			cls_total += length
	if cls_len.is_empty():
		DccWidgets.note(net, "No street classes present -- a bare site with no grown network.")
	else:
		var bar := HBoxContainer.new()
		bar.custom_minimum_size.y = 14
		bar.add_theme_constant_override("separation", 1)
		for cls in _STREET_CLASS_ORDER:
			if not cls_len.has(cls):
				continue
			var seg := ColorRect.new()
			seg.color = _STREET_CLASS_COLOR.get(cls, DccTheme.c("text_dim"))
			seg.size_flags_horizontal = Control.SIZE_EXPAND_FILL
			seg.size_flags_stretch_ratio = maxf(0.02, float(cls_len[cls]) / maxf(1.0, cls_total))
			seg.tooltip_text = "%s -- %s m" % [cls, FactionRosterWindow._thousands(int(round(cls_len[cls])))]
			bar.add_child(seg)
		net.add_child(bar)
		var legend := HFlowContainer.new()
		legend.add_theme_constant_override("h_separation", 14)
		legend.add_theme_constant_override("v_separation", 4)
		for cls in _STREET_CLASS_ORDER:
			if not cls_len.has(cls):
				continue
			var row := HBoxContainer.new()
			row.add_theme_constant_override("separation", 6)
			var sw := ColorRect.new()
			sw.color = _STREET_CLASS_COLOR.get(cls, DccTheme.c("text_dim"))
			sw.custom_minimum_size = Vector2(8, 8)
			row.add_child(sw)
			row.add_child(DccTheme.mono_label(cls, "text_dim", DccTheme.FS_TINY))
			row.add_child(DccTheme.mono_label(FactionRosterWindow._thousands(int(round(cls_len[cls]))),
				"text", DccTheme.FS_SMALL))
			legend.add_child(row)
		net.add_child(legend)
	DccWidgets.note(net, "The classes come across pre-grouped so a renderer strokes them in draw "
		+ "order without re-sorting a flat list every frame; this breakdown is derived here by "
		+ "summing each class's own segments, since the engine only totals the whole graph.")

	# -- Stages that ran --------------------------------------------------------
	var stages_grp := DccWidgets.group(sec, "Stages that ran", true)
	for stage in (l.get("stages", PackedStringArray()) as PackedStringArray):
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 8)
		row.add_child(DccTheme.mono_label("✓", "accent", DccTheme.FS_SMALL))
		row.add_child(DccTheme.mono_label(String(stage), "text", DccTheme.FS_TINY))
		stages_grp.add_child(row)
	DccWidgets.note(stages_grp, "Kept as data by the bridge so the disclosure cannot drift from "
		+ "the code -- a stage that ran without an input says so in its own row.")

	# -- Not generated -- no key emitted ----------------------------------------
	var absent_grp := DccWidgets.group(sec, "Not generated -- no key emitted", true)
	for a in LAYOUT_ABSENT:
		DccWidgets.note(absent_grp, "%s -- %s" % [String(a[0]), String(a[1])])
	DccWidgets.note(absent_grp, "Deliberately absent rather than empty: a viewer that wants to "
		+ "say \"no wall\" must first be able to tell that apart from \"no wall generator\", "
		+ "and every other key this dictionary carries (buildings, districts, walls, markets, "
		+ "farmland, bridges) IS present today -- this pair is the real gap, not the canvas's "
		+ "wider four (see this function's own doc comment).")

	# -- Substrate flags --------------------------------------------------------
	var sub_grp := DccWidgets.group(sec, "Substrate flags", true)
	for row_data in [
		["uses_real_water", "real" if bool(l.get("uses_real_water", false)) else "synthetic"],
		["uses_real_terrain", "real" if bool(l.get("uses_real_terrain", false)) else "synthetic"],
		["market_prov", String(l.get("market_prov", "?"))],
	]:
		var row := HBoxContainer.new()
		row.add_theme_constant_override("separation", 8)
		row.add_child(DccTheme.mono_label(String(row_data[0]), "text_dim", DccTheme.FS_TINY))
		row.add_child(DccTheme.mono_label(String(row_data[1]), "text", DccTheme.FS_SMALL))
		sub_grp.add_child(row)
	DccWidgets.note(sub_grp, "Whether the generator used this world's real water and terrain, or "
		+ "fell back to a synthetic stand-in. A layout built on a fallback is a different claim.")

	# -- Inputs and Rules link out -----------------------------------------------
	var in_grp := DccWidgets.group(sec, "Inputs -- and where they really live", true)
	DccWidgets.note(in_grp, "Population and Age are the two real inputs this layout reads "
		+ "(pop_target, and the growth-epoch spread) -- both are the same fields Overview "
		+ "already edits, not a second control for one piece of state. Edit them there.")
	var rules := DccWidgets.action(in_grp, "Generation rules… ↗", func(): app.generation_rules_window.open())
	rules.tooltip_text = "World-level (canvas 1h). Opens the Generation rules window -- the active rule set it edits feeds every settlement on World rules. A per-settlement rule set, culture and Regenerate are in the City Viewer's Town plan."


## `layout_dict`'s own class list (`urban_bridge.rs`, the `for cls in ["lane",
## "street", "quay", "ringroad", "primary"]` loop) -- draw order, matched here
## so the breakdown legend reads in the same order `urban_layout_draw.gd`'s own
## `DRAW_ORDER` strokes them.
const _STREET_CLASS_ORDER := ["lane", "street", "quay", "ringroad", "primary"]

## No shared palette exists for street class -- `urban_layout_draw.gd` varies
## only stroke *width* by class (`W_FILL`), not colour. Derived from the accent
## token rather than five hand-picked literals, so a theme flip (`DccTheme`'s
## own light/dark tables) repaints these the same way it repaints everything
## else built from `c("accent")`/`c("text_dim")`.
var _STREET_CLASS_COLOR := {
	"lane": DccTheme.c("text_dim"),
	"street": DccTheme.c("text_dim").lightened(0.35),
	"quay": DccTheme.c("accent").darkened(0.35),
	"ringroad": DccTheme.c("accent").lightened(0.25),
	"primary": DccTheme.c("accent"),
}

## Verified 2026-09-21 against `urban_bridge.rs::layout_dict` itself (see
## `_build_layout`'s own doc comment) -- not copied from the canvas, whose own
## text is stale. `[label, reason]`.
const LAYOUT_ABSENT := [
	["Civic hall & places of worship",
		"Town::civic + the games buildings beside it -- read by the adapter, never set on this dictionary"],
]


func _fact_chip(key: String, value: String) -> PanelContainer:
	var p := PanelContainer.new()
	p.add_theme_stylebox_override("panel", DccTheme.outline("border"))
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 6)
	row.add_theme_constant_override("margin_left", 2)
	row.add_child(DccTheme.mono_label(key, "text_dim", DccTheme.FS_TINY))
	row.add_child(DccTheme.mono_label(value, "text", DccTheme.FS_SMALL))
	p.add_child(row)
	return p


# -- Name + re-roll ---------------------------------------------------------

func _build_identity(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Identity")
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 6)
	_name_edit = LineEdit.new()
	_name_edit.text = String(s.get("name", ""))
	_name_edit.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	## Commit on focus-loss/Enter rather than per keystroke: the engine call
	## is a full `Dictionary` round trip, and a rebuild mid-word would steal
	## focus -- the same reasoning `civilization_workspace.gd`'s own
	## `_settlement_name_field` gives for not rebuilding on `text_changed`.
	_name_edit.text_submitted.connect(func(t: String): _apply({"name": t}))
	## `_rebuilding` / null guard: this fires during `_clear()`'s own teardown
	## too, where the "edit" it would commit is the stale text of a field that
	## is being thrown away. See `_rebuilding`'s doc comment (PE-01).
	_name_edit.focus_exited.connect(func():
		if _rebuilding or _name_edit == null:
			return
		_apply({"name": _name_edit.text}))
	row.add_child(_name_edit)
	var roll := Button.new()
	roll.text = "⟳"
	roll.tooltip_text = "Re-roll a name from this settlement's own faction naming culture (reference v1.07: a rename matches the polity it belongs to, not the global pool)."
	roll.focus_mode = Control.FOCUS_NONE
	## `06-phone.md` §6.7's New World modal draws the only randomise-this-field
	## button the canvases carry, in exactly this slot -- beside the text field
	## it re-rolls -- at **`44 × 42`**, radius 12. Taken verbatim; this button
	## had no size of its own and came out at the stock `Button` height, which
	## on a phone is not a target. `DccShell.phone_fit` raises the 42 to §13's
	## 44 dp floor there and leaves the pointer at the canvas's own figure.
	##
	## **The glyph is where this and the canvas part, and it is not a
	## derivation.** The canvas's is `⚄`, a die, for re-rolling a numeric seed;
	## this re-rolls a *name* out of a culture's pool, and no canvas draws that
	## control. `⟳` is kept and the divergence recorded rather than a die
	## borrowed for an act that involves no number.
	roll.custom_minimum_size = Vector2(44, 42)
	roll.pressed.connect(func():
		var n := bridge.civ_reroll_settlement_name(_index)
		if n != "":
			place_changed.emit()
			_rebuild())
	row.add_child(roll)
	sec.add_child(row)
	DccWidgets.note(sec, "Cell (%d, %d) · tid %d" % [
		int(s.get("x", 0)), int(s.get("y", 0)), int(s.get("tid", 0))])


# -- Class + polity ---------------------------------------------------------

func _build_class_and_polity(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Classification")
	var kind := String(s.get("kind", "town"))
	DccWidgets.choice(sec, "Class", KIND_ORDER.map(func(k): return String(k).capitalize()),
		maxi(0, KIND_ORDER.find(kind)),
		func(i: int): _apply({"kind": KIND_ORDER[i]}); _rebuild(),
		"The settlement's size class. Changing it also sets or clears the capital flag: a capital or metropolis is its polity's seat.")
	## Corrected 2026-09-24 (audit B18): it said the Settlement tool refuses
	## Metropolis, untrue since 2026-08-20 (`civ_tools_bridge.rs::kind_from_str`
	## accepts it; `_civSelectMetropolises` port). The capital flag is the same
	## fact stored twice, which is why class changes move it.

	var factions := bridge.get_factions()
	if factions.is_empty():
		DccWidgets.note(sec, "No factions -- generate a world first.")
		return
	var ids: Array = []
	var labels: Array = []
	for f in factions:
		var d: Dictionary = f
		ids.append(int(d.get("id", 1)))
		labels.append("%d · %s" % [int(d.get("id", 1)), String(d.get("name", "?"))])
	DccWidgets.choice(sec, "Polity", labels, maxi(0, ids.find(int(s.get("faction", 1)))),
		func(i: int): _apply({"faction": ids[i]}); _rebuild(),
		"Which polity this settlement belongs to. Changing it does not repaint the borders by itself; Civilization ▸ Territories ▸ Recalculate territories re-derives them from the current settlements.")
	## Corrected 2026-09-24 (audit B18): it said no function re-runs
	## `assign_territory` and then named the button that does (`civ_recompute`).


# -- Population + economy ---------------------------------------------------

func _build_economy(parent: Control, s: Dictionary, details: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Population & economy")
	## Step 1, not the reference's own `step="500"`: an HTML number input
	## only steps its ARROWS by that, while Godot's `SpinBox` snaps the
	## displayed value to `min + k*step` -- which would show a population of
	## 4500 for a settlement the engine holds at 4321, and write the lie back
	## on the next interaction. Correctness over arrow ergonomics.
	DccWidgets.number(sec, "Population", 0.0, 100000000.0, 1.0, float(int(s.get("population", 0))),
		func(v: float): _apply({"population": int(v)}))
	var specs := bridge.civ_specialisation_vocabulary()
	if not specs.is_empty():
		var keys: Array = []
		var labels: Array = []
		for e in specs:
			var d: Dictionary = e
			keys.append(String(d.get("key", "none")))
			labels.append(String(d.get("label", "?")))
		var cur := String(details.get("specialisation", "none"))
		DccWidgets.choice(sec, "Economy", labels, maxi(0, keys.find(cur)),
			func(i: int): _apply({"specialisation": keys[i]}),
			"CIV_SPECIALISATIONS, the reference's own vocabulary. Stored on the settlement but NOT fed back into civ_faction_aggregates' sector output -- doing so would change already-golden economy numbers on a user edit. See GUI_GAP_REGISTER.md ED-03.")


# -- Trade ------------------------------------------------------------------

## `_civGoodReach`'s bulk branch, in the one sentence a reader needs: what a
## settlement's own water lets its heavy goods actually reach. Keyed by
## `cartalith_civ::trade::NavKind`'s own strings.
const REACH_BY_WATER := {
	"sea": "long -- bulk goods reach anywhere",
	"river": "regional -- bulk goods reach the river's own network",
	"stream": "local -- a headwater stream carries no cargo",
	"none": "local -- bulk goods stop at 50 km",
}

## `GUI_GAP_REGISTER.md` **IN-13**'s per-settlement half: *"imports/exports
## per settlement as a ledger"*.
##
## Here rather than in a second settlement list in the dock, because this
## window is already where a settlement's own facts live — and because a
## partner is a *name*, which only means something next to the place it
## belongs to.
##
## Reads `TradeStore`, never the engine: the match is one computation shared
## by three surfaces, and re-running it on every place-editor open is exactly
## the cost `civ_trade_flows()`'s own doc comment explains this design avoids.
## When no match has run the section says so and points at the one control
## that runs it — a section that silently showed nothing would be
## indistinguishable from a settlement that trades nothing.
func _build_trade(parent: Control) -> void:
	var sec := DccWidgets.section(parent, "Trade")
	if not TradeStore.is_matched():
		DccWidgets.note(sec,
			"No trade match on this world yet. Civilization ▸ Economy ▸ Trade flows ▸ Match trade flows "
			+ "computes who supplies whom; it is derived on demand and held nowhere, so a "
			+ "generate clears it.")
		return

	var led := TradeStore.ledger(_index)
	var imports: Array = led.get("imports", [])
	var exports: Array = led.get("exports", [])
	var unmet := TradeStore.unmet_for(_index)

	if imports.is_empty() and exports.is_empty() and unmet.is_empty():
		DccWidgets.note(sec,
			"No trade relationship. Its hinterland is close enough to the world mean on every "
			+ "resource that nothing reads as a surplus or a shortage.")
	if not imports.is_empty():
		var g := DccWidgets.group(sec, "Imports")
		for f in imports:
			_trade_row(g, f, "from_name", "←")
	if not exports.is_empty():
		var g2 := DccWidgets.group(sec, "Exports")
		for f in exports:
			_trade_row(g2, f, "to_name", "→")
	if not unmet.is_empty():
		DccWidgets.note(sec,
			"Needs %s and nothing in reach supplies it. That is a dependency the world cannot "
			% ", ".join(unmet)
			+ "carry, not an import relationship -- the reference's own distinction.")

	var n := TradeStore.navigability(_index)
	if not n.is_empty():
		var kind := String(n.get("kind", "none"))
		var reach := String(REACH_BY_WATER.get(kind, "local"))
		DccWidgets.note(sec, "Water: %s (%s). Bulk reach is %s."
			% [kind, String(n.get("basis", "?")), reach])
	_food_shed_note(sec)
	_smelting_salt_note(sec)

## `ECONOMY_SCOPE.md` milestone 2's per-settlement half -- `_civFoodShed`, run
## for every settlement by `TradeStore.refresh()` in the same pass as the trade
## match above. Here, beside Water, because both answer the same question about
## this one place: what can actually reach it. The import term is even routed
## over the navigability `n` just read.
##
## **Every figure is a headcount, not a tonnage.** `civ_food_shed` scales each
## catchment's yield by that culture's farmers-per-urbanite ratio before summing
## (`cartalith_civ::trade::food_surplus_ratio`), so `supported` is the *urban
## population* this settlement's food logistics can carry -- which is why it is
## directly comparable to `pop`, and why the label says "people".
##
## Diagnostic only, and said so in the note: the reference reconciles the
## overshoot in `_civApplyFoodShedCeilings`, and **that function is not ported**
## (re-checked repo-wide 2026-09-05 -- `grep -rn "apply_food_shed\|ApplyFoodShed"`
## over `crates/` returns exactly one hit, a comment in `trade.rs`, and nothing
## implements it). Nothing here clamps a population, so a reader must not take
## an unsustainable settlement for one the engine will shrink.
##
## ## Two ways to have no row, and they are not the same fact
##
## `TradeStore.food_shed_for()` answers `{}` for **either** "no pass is held"
## **or** "the pass is held and this index is past its rows", and until
## 2026-09-05 both drew the same sentence: *"civ_food_shed() returned
## nothing, which is what an engine build older than milestone 2 does."* On
## the second branch that is false, and provably so in the same breath -- the
## pass is right there holding a row for every other settlement.
##
## Found by driving both branches (`_lanedfoodshed_probe.gd` T2, on a live
## 215-settlement world: index 215 drew the engine-too-old reason while
## indices 0..214 all answered). `MISTAKES.md`'s dash-reason row is exactly
## this shape -- *a wrong reason is worse than none, because it reads as
## freshly checked and it routes the next brief at a whole subsystem*. So the
## two branches now say the two different true things, and
## `is_food_shed_matched()` is what tells them apart.
func _food_shed_note(sec: Control) -> void:
	var shed := TradeStore.food_shed_for(_index)
	if shed.is_empty():
		if not TradeStore.is_food_shed_matched():
			DccWidgets.note(sec, "Food shed: — no row for this settlement. civ_food_shed() "
				+ "returned nothing, which is what an engine build older than ECONOMY_SCOPE.md "
				+ "milestone 2 does.")
		else:
			## Counted off the existing public reader rather than through a new
			## `row_count()` on `TradeStore`: one call site does not earn API.
			var held: int = (TradeStore.food_shed().get("rows", []) as Array).size()
			DccWidgets.note(sec, "Food shed: — the pass ran and covers %d settlement%s, "
				% [held, "" if held == 1 else "s"]
				+ "but has no row at index %d. The roster and the last food-shed pass " % _index
				+ "have drifted apart -- re-run Civilization ▸ Economy ▸ Trade flows ▸ Match trade flows.")
		return
	var supported := FactionRosterWindow._thousands(int(round(float(shed.get("supported", 0.0)))))
	var local := FactionRosterWindow._thousands(int(round(float(shed.get("local_capacity", 0.0)))))
	var hinter := FactionRosterWindow._thousands(int(round(float(shed.get("hinterland_capacity", 0.0)))))
	var suppliers := int(shed.get("suppliers", 0))
	## `best_mode` is `land` whether or not anything was imported, so it is only
	## reported when a supplier actually contributed -- the engine's own caveat.
	var import_clause := "nothing imported -- no settlement with spare capacity is in reach"
	if suppliers > 0:
		import_clause = "%s imported from %d settlement%s over %s" % [
			FactionRosterWindow._thousands(int(round(float(shed.get("import_capacity", 0.0))))),
			suppliers, "" if suppliers == 1 else "s", String(shed.get("best_mode", "land"))]
	DccWidgets.note(sec, "Food shed: supports %s people -- %s from its own catchment, %s from the "
		% [supported, local, hinter]
		+ "countryside within land reach, %s. Limited by %s." % [import_clause,
			String(shed.get("limited_by", "local"))])
	var pop := FactionRosterWindow._thousands(int(shed.get("pop", 0)))
	if bool(shed.get("sustainable", true)):
		DccWidgets.note(sec, "Population %s when the match ran, inside that ceiling." % pop)
	else:
		DccWidgets.note(sec, "Population %s when the match ran, over the ceiling by %s. "
			% [pop, FactionRosterWindow._thousands(int(round(float(shed.get("over_by", 0.0)))))]
			+ "A diagnostic, not a correction -- the reference's _civApplyFoodShedCeilings is "
			+ "not ported, so nothing here shrinks the settlement to fit.")

## `ECONOMY_SCOPE.md` EC-2/EC-7 -- `_civPlaceSmelting`/`_civSaltAccess`, run for
## every settlement by `TradeStore.refresh()` in the same pass as everything
## above. Beside the food shed for the same reason that sits beside Water: all
## three answer what this one place can actually reach, from its own ground.
##
## Smelting is gated by **fuel, not ore** -- the reference's own point, kept in
## the note rather than buried: `limited_by` names whichever of the two
## catchment budgets binds, and `fuel_poor`/`ore_rich` flag the two lopsided
## cases (ore to spare with no wood to fire it, and the converse -- a charcoal
## exporter with nothing to smelt).
##
## Both dashes below carry the **two-branch split** `_food_shed_note` documents,
## and for the identical reason: `smelting_for()`/`salt_access_for()` each
## answer `{}` for either "no pass is held" or "this index is past the pass's
## rows", and until 2026-09-05 both printed one whole-pass sentence -- which
## on the second branch is false. Fixed here in the same change that fixed the
## food shed's, since the defect is one shape in three readouts, not three
## defects. `coppice_ha_needed` is emitted by `civ_place_smelting` and drawn by
## nothing; that is a missing reader, not a missing value, and it is recorded
## in `trade_store.gd::smelting_for`'s doc rather than dashed here.
func _smelting_salt_note(sec: Control) -> void:
	var smelt := TradeStore.smelting_for(_index)
	if smelt.is_empty():
		if not TradeStore.is_smelting_matched():
			DccWidgets.note(sec, "Smelting: — no row for this settlement. civ_place_smelting() "
				+ "returned nothing, the same defensive case civ_food_shed()'s own reader states "
				+ "above for an engine build without the binding.")
		else:
			DccWidgets.note(sec, "Smelting: — the pass ran but has no row at index %d. " % _index
				+ "Re-run Civilization ▸ Economy ▸ Trade flows ▸ Match trade flows.")
	elif float(smelt.get("iron_kg_yr", 0.0)) <= 0.0:
		DccWidgets.note(sec, "Smelting: none possible here -- ore, fuel, or both are absent from "
			+ "this catchment.")
	else:
		var iron := FactionRosterWindow._thousands(int(round(float(smelt.get("iron_kg_yr", 0.0)))))
		var ore := FactionRosterWindow._thousands(int(round(float(smelt.get("ore_kg_yr", 0.0)))))
		var charcoal := FactionRosterWindow._thousands(int(round(float(smelt.get("charcoal_kg_yr", 0.0)))))
		var woodland := FactionRosterWindow._thousands(int(round(float(smelt.get("woodland_ha", 0.0)))))
		var flag := ""
		if bool(smelt.get("fuel_poor", false)):
			flag = " Fuel-poor: ore to spare, not enough woodland to fire it."
		elif bool(smelt.get("ore_rich", false)):
			flag = " A charcoal exporter: more fuel here than this catchment's ore can use."
		DccWidgets.note(sec, ("Smelting: %s kg iron/yr, limited by %s -- %s kg ore/yr, %s kg "
			+ "charcoal/yr from %s ha of woodland.%s") % [iron, String(smelt.get("limited_by", "ore")),
				ore, charcoal, woodland, flag])

	var salt := TradeStore.salt_access_for(_index)
	if salt.is_empty():
		if not TradeStore.is_salt_matched():
			DccWidgets.note(sec, "Salt: — no row for this settlement. civ_salt_access() "
				+ "returned nothing, the same defensive case civ_food_shed()'s own reader states "
				+ "above for an engine build without the binding.")
		else:
			DccWidgets.note(sec, "Salt: — the pass ran but has no row at index %d. " % _index
				+ "Re-run Civilization ▸ Economy ▸ Trade flows ▸ Match trade flows.")
	elif bool(salt.get("has", false)):
		DccWidgets.note(sec, "Salt: yes, from %s." % String(salt.get("source", "?")))
	else:
		DccWidgets.note(sec, "Salt: none in reach -- no sea route, salt deposit or salt lake.")

func _trade_row(parent: Control, flow: Variant, name_key: String, arrow: String) -> void:
	var f: Dictionary = flow
	var partner := int(f.get("from" if name_key == "from_name" else "to", -1))
	var b := DccWidgets.action(parent, "%s %s %s -- %s, %s %d km" % [
		String(f.get("good", "?")), arrow, String(f.get(name_key, "?")),
		FactionRosterWindow._thousands(int(round(float(f.get("volume", 0.0))))),
		String(f.get("mode", "land")), int(round(float(f.get("distance_km", 0.0))))],
		func():
			if partner >= 0:
				app.open_place_editor(partner))
	b.alignment = HORIZONTAL_ALIGNMENT_LEFT
	b.tooltip_text = ("%s reach; %d%% of the partner's scale survives the carriage. "
		+ "Opens the partner's own place editor.") % [
			String(f.get("reach", "?")),
			int(round(100.0 * float(f.get("deliverable", 0.0))))]


# -- Traits -----------------------------------------------------------------

func _build_traits(parent: Control, details: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Traits")
	var vocab := bridge.civ_trait_vocabulary()
	if vocab.is_empty():
		DccWidgets.note(sec, "No trait vocabulary -- the engine build is older than civ_trait_vocabulary().")
		return
	var on: PackedStringArray = details.get("traits", PackedStringArray())
	var flow := HFlowContainer.new()
	flow.add_theme_constant_override("h_separation", 4)
	flow.add_theme_constant_override("v_separation", 4)
	for e in vocab:
		var d: Dictionary = e
		var key := String(d.get("key", ""))
		var is_on := on.has(key)
		var b := Button.new()
		b.text = "%s %s" % [String(d.get("glyph", "")), String(d.get("label", key))]
		## **Not flat.** Both branches below paint a real "normal" fill (accent
		## when on, sunken when off) and a real "hover" fill -- a flat `Button`
		## skips both entirely (`layers_popover.gd`'s own finding, reproduced
		## independently on this build: an isolated probe with the identical
		## shape drew nothing on `normal`/`hover` while `flat` was true and drew
		## correctly the instant it went `false`). Every trait chip was rendering
		## as bare text, on or off alike, until this changed.
		b.flat = false
		b.focus_mode = Control.FOCUS_NONE
		b.custom_minimum_size.y = 22
		b.add_theme_font_size_override("font_size", DccTheme.FS_SMALL)
		## `accent_ink` on the filled half since the 2026-08-31 re-base -- see
		## the token's own comment; `c("bg")` here was near-black on amber.
		b.add_theme_color_override("font_color",
			DccTheme.c("accent_ink") if is_on else DccTheme.c("text_dim"))
		b.add_theme_stylebox_override("normal",
			DccTheme.flat(DccTheme.c("accent") if is_on else DccTheme.c("sunken")))
		## **The off-chip's hover was inverted by the 2026-08-31 token re-base.**
		## It was `raised`, which is a lift over the old `sunken` and is not one
		## over the new: `--ins` moved #101112 -> #191c1e, so on dark the hover
		## went from *lighter by (7,8,8)* to *darker by (2,3,4)* -- a hover that
		## reads as a press, at a delta too small to read as anything.
		##
		## `outline("border", "sunken")` keeps the well and adds the hairline edge
		## the shell already uses for a chip hover (`dcc_widgets.gd`'s `outline(...)`
		## pair), so the affordance is an edge rather than a fill and works the
		## same in both palettes -- `border` is rgba(255,255,255,.16) on dark and
		## rgba(0,0,0,.20) on light. Both are real tokens, so `DccTheme.remap()`
		## repaints them on a theme flip; a `lightened()`/blended literal would not
		## be matched by either of its passes.
		b.add_theme_stylebox_override("hover",
			DccTheme.flat(DccTheme.c("accent").lightened(0.1)) if is_on
			else DccTheme.outline("border", "sunken"))
		b.pressed.connect(func():
			bridge.civ_settlement_toggle_trait(_index, key)
			## The map's badge row is joined by `tid` from
			## `civ_settlement_details()`, so it only changes when something
			## re-reads that -- a toggle here is the one edit that moves it.
			if app != null and app.viewport != null and app.viewport.has_method("refresh_settlement_traits"):
				app.viewport.refresh_settlement_traits()
			_rebuild())
		flow.add_child(b)
	sec.add_child(flow)
	DccWidgets.note(sec,
		"Map-glyph badges, deliberately overlapping Economy on mining/trade hub -- the "
		+ "reference keeps both vocabularies on purpose. Toggling one draws it under the "
		+ "settlement's pin immediately (map_overlay.gd's `_draw_trait_badges`, the "
		+ "reference's own no-art disc-and-glyph branch; no asset-pack sprite reaches a "
		+ "Godot draw call yet).")


# -- Age + walls ------------------------------------------------------------

func _build_urban(parent: Control, details: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Settlement fabric")
	var age := int(details.get("age", -1))
	## `-1` is the stored "no override" -- never shown as though it were an age
	## (`MISTAKES.md`: never encode "no value" as a plausible value). Auto names
	## what it resolves to, `age_inferred` (`civ_settlement_details`: the same
	## `um_infer_age` the layout uses), and Set starts from that same number, so
	## switching over changes nothing until the user edits it.
	var inferred := int(details.get("age_inferred", -1))
	var auto_label := "Auto" if inferred < 0 else "Auto (~%d yr)" % inferred
	DccWidgets.choice(sec, "Age", [auto_label, "Set"], 0 if age < 0 else 1,
		func(i: int):
			_apply({"age": -1 if i == 0 else clampi(inferred if inferred > 0 else 30, 30, 1000)})
			_rebuild(),
		"Auto infers age from population, as the reference's _umInferAge does. Set overrides it.")
	if age >= 0:
		## Step 1 for the same reason Population above uses it -- see there.
		DccWidgets.number(sec, "Age (yr)", 30.0, 1000.0, 1.0, float(age),
			func(v: float): _apply({"age": int(v)}),
			"Clamped to 30..1000, exactly as the reference's own field does.")
	var walls := int(details.get("walls", -1))
	DccWidgets.choice(sec, "Walls", ["Auto", "No fortifications", "Fortified"],
		0 if walls < 0 else (1 if walls == 0 else 2),
		func(i: int): _apply({"walls": (-1 if i == 0 else (0 if i == 1 else 1))}),
		"The reference's own checkbox cannot return to Auto once clicked (native checkboxes have no third state); this picker can.")
	## **This note has now been wrong three times, each time about a gap that
	## had just closed. Third correction, 2026-09-05.**
	##
	## It first blamed `_umInferAge`/`_umWallSpec` being "not ported" -- both
	## were. Re-cut 2026-09-03 to blame `WallPlace` hardcoding `None` -- it had
	## started reading a `PlaceOverrides` struct in the same batch. Re-cut again
	## to blame one undelivered call site, `urban_bridge.rs` calling
	## `settlement_layout()` -- and that call site is now
	## `urban_adapter::settlement_layout_with(&world, s, &civ.ways, &o)`
	## (`urban_bridge.rs`, inside `urban_layouts`), building `o` from the
	## settlement's own `place_extras` row. Its doc comment dates the change to
	## 2026-09-03 and opens **"The place editor's overrides reach the layout"**.
	##
	## So the note below no longer disclaims anything: the row is live, and it
	## says what the two controls now do rather than why they do nothing.
	DccWidgets.note(sec,
		"Both overrides reach the drawn town. um_wall_spec branches on "
		+ "walls_override and age_override before anything else, the adapter's "
		+ "WallPlace reads them off a PlaceOverrides struct, and urban_bridge.rs "
		+ "builds that struct from this settlement's own stored fields and hands "
		+ "it to settlement_layout_with() -- so marking a settlement Fortified "
		+ "gives it a circuit in the City Viewer, and an explicit age displaces "
		+ "_umInferAge's guess. Leaving both on Auto is every field absent, which "
		+ "is the default, so an unedited settlement draws exactly as before.")


# -- History ----------------------------------------------------------------

func _build_history(parent: Control, details: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "History")
	var te := TextEdit.new()
	te.text = String(details.get("history", ""))
	te.placeholder_text = "Lore, founding, notable events…"
	te.custom_minimum_size.y = 84
	te.wrap_mode = TextEdit.LINE_WRAPPING_BOUNDARY
	## Same guard as the name field above (PE-01). The cross-settlement case is
	## the dangerous one: `open_for()` sets `_index` and only then rebuilds, so
	## an unguarded teardown commit writes THIS settlement's history onto the
	## one the user just opened.
	te.focus_exited.connect(func():
		if _rebuilding:
			return
		_apply({"history": te.text}))
	sec.add_child(te)


# -- Knowledge (Markdown vault) ---------------------------------------------

## `MARKDOWN_VAULT_INTEGRATION.md` §28's KNOWLEDGE block, which the design
## sketches inside exactly this panel: *"The Markdown functionality should
## appear in entity information panels rather than as an isolated utility."*
##
## What lives here is the affordance and the status; the browser, the reader
## and the two write actions live in `vault_window.gd`, which this opens
## already scoped to this settlement.
##
## **Keyed by `tid`, not by `_index`.** A settlement's index shifts every time
## an earlier one is deleted, and a knowledge link that followed the index
## would silently re-point at a different town. `tid` is this port's own
## stable id and is what the engine stores.
func _build_knowledge(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Knowledge")
	var tid := int(s.get("tid", 0))
	if tid == 0:
		DccWidgets.note(sec, "This settlement has no stable id yet, so nothing can be linked to it.")
		return
	var name := String(s.get("name", "this settlement"))
	var summary := bridge.vault_entity_summary("settlement", tid)
	var n := int(summary.get("link_count", 0))
	if n == 0:
		DccWidgets.note(sec, "No Markdown notes linked.")
	else:
		DccWidgets.note(sec, "%d linked note%s — %s" % [n, "" if n == 1 else "s",
			String(VaultWindow.STATUS_TEXT.get(String(summary.get("status", "")), ""))])
	var open := DccWidgets.action(sec, "Linked notes…" if n > 0 else "Attach a Markdown note…", func():
		app.open_vault("settlement", tid, name))
	open.tooltip_text = ("Links this settlement to a note in an external Markdown vault — any folder "
		+ "of .md files, Obsidian's included, and nothing here requires Obsidian. Cartalith reads on "
		+ "demand and writes only on an explicit, previewed action.")
	_build_backlinks(sec, "settlement", tid, name)


## `GUI_GAP_REGISTER.md` **VA-01**: what points *at* this entity, as opposed to
## what it points at.
##
## Three states, kept apart because on screen they mean different things:
##
## - **not indexed** — say so and offer the one control that fixes it. An
##   empty list here would read as "nothing references this place", which is a
##   claim the shell has no basis for until the index exists.
## - **backlinks** — exact references. A `block` row is a note carrying this
##   entity's own Cartalith block, which finds it even when it has no note of
##   its own; it is not a link and is labelled differently.
## - **unlinked mentions** — a name in prose, and a *guess*. Visually
##   subordinate, with the excerpt shown so the reader can judge it, because a
##   place called Nareth and a person called Nareth read identically to a
##   substring match.
##
## Static-shaped enough to live in the base window rather than in each caller:
## the faction roster and the province rows call it with their own kind.
func _build_backlinks(sec: Control, kind: String, entity_id: int, name: String) -> void:
	var stats := bridge.vault_backlink_stats()
	if not bool(stats.get("built", false)):
		var note := DccWidgets.note(sec,
			"Backlinks are not indexed for this vault yet. Building the index reads every "
			+ "note once; after that a refresh only re-opens the files that changed.")
		note.tooltip_text = "Data ▸ Markdown vault… ▸ Index builds it."
		return

	var back: Array = bridge.vault_entity_backlinks(kind, entity_id)
	if back.is_empty():
		DccWidgets.note(sec, "No note references this %s." % kind)
	else:
		var g := DccWidgets.group(sec, "Backlinks (%d)" % back.size())
		for row in back:
			var d: Dictionary = row
			var rel := String(d.get("rel", ""))
			var form := String(d.get("form", "wiki"))
			var count := int(d.get("count", 1))
			var b := DccWidgets.action(g, "%s%s" % [rel, "" if count < 2 else "  ×%d" % count],
				func(): app.open_vault_overview())
			b.alignment = HORIZONTAL_ALIGNMENT_LEFT
			b.tooltip_text = {
				"wiki": "A [[wikilink]] in this note points here.",
				"markdown": "A [markdown](link) in this note points here.",
				"block": "This note carries a Cartalith block naming %s:%d directly, so the reference survives a rename of the note and of the %s." % [kind, entity_id, kind],
			}.get(form, "") + " Opens the vault panel."

	var mentions: Array = bridge.vault_entity_mentions(kind, entity_id, name, 8)
	if mentions.is_empty():
		return
	var mg := DccWidgets.group(sec, "Unlinked mentions (%d)" % mentions.size(), false)
	DccWidgets.note(mg,
		"A guess: these notes contain the name and do not link here. Cartalith opened only "
		+ "the files its index said could match, and it changed none of them.")
	for row in mentions:
		var d: Dictionary = row
		DccWidgets.note(mg, "%s
    %s" % [String(d.get("rel", "")), String(d.get("excerpt", ""))])


# -- Actions ----------------------------------------------------------------

func _build_actions(parent: Control, s: Dictionary) -> void:
	var sec := DccWidgets.section(parent, "Actions")
	DccWidgets.action(sec, "Focus camera on settlement", func():
		app.viewport.move_view_to(float(int(s.get("x", 0))), float(int(s.get("y", 0)))))
	## `peCityOpen` (`GUI_GAP_REGISTER.md` UM-03). That row predicted "a popup
	## can call it in one line" once a popup existed; this is the line.
	##
	## `has_method`-guarded because `CityViewerWindow` is a separate, parallel
	## piece of work: this window degrades to a disabled button rather than a
	## runtime error against a shell that does not carry it -- the same guard
	## discipline `engine_bridge.gd` applies to every `#[func]` it calls.
	var idx := _index
	var cv := DccWidgets.action(sec, "Open in City Viewer", func():
		if app.has_method("open_city_viewer"):
			app.open_city_viewer(idx))
	cv.disabled = not app.has_method("open_city_viewer")
	cv.tooltip_text = "The reference's peCityOpen. peCityPreview (the layout thumbnail inline in this popup) is still open -- it needs a rendered layout at icon size, not a modal."
	var del := DccWidgets.action(sec, "Delete place", func(): confirm_delete(_index))
	del.add_theme_color_override("font_color", DccTheme.c("accent"))
	del.tooltip_text = "The reference confirms first (its own v1.24 data-loss fix); so does this."


## Shared with the map context menu and the Delete key, so all three
## destructive paths ask exactly once, the same way.
func confirm_delete(index: int) -> void:
	var all := bridge.settlements()
	if index < 0 or index >= all.size():
		return
	var name := String((all[index] as Dictionary).get("name", "this place"))
	## `DccWidgets.confirm()` -- see `right_dock.gd::_confirm_revert`.
	DccWidgets.confirm(app, "Delete place?",
		"Delete %s?\n\nProvinces, trade balances, roads and territory were computed before this edit and are not recomputed by the delete itself. The Civilization dock's Settlements ▸ Recompute civilisation rebuilds them against the current roster and terrain." % name,
		"Delete",
		func():
			if bridge.civ_delete_settlement(index):
				place_deleted.emit()
				if index == _index:
					_index = -1
					hide()
				else:
					_rebuild())


func _build_footer(parent: Control) -> void:
	_footer = DccWidgets.note(parent,
		"Not built here, each for a stated reason: Category (settlement ↔ POI) -- POI is not a "
		+ "ported concept (GUI_GAP_REGISTER.md CV-01); the inline town-layout thumbnail (UM-03) "
		+ "-- no layout renders at icon size yet, though its City Viewer launcher above is live; "
		+ "\"Connect to road network\" -- no civ_connect_place_to_network binding; Econ. "
		+ "importance and Trade volume -- NamedSettlement carries neither field.")


## One engine call, then a refresh. `civ_edit_settlement` is all-or-nothing:
## a rejected value applies nothing, so a `false` here means the form and the
## engine disagree and the form must be rebuilt from the engine's truth,
## never left showing a value that was refused.
func _apply(fields: Dictionary) -> void:
	if _index < 0:
		return
	if not bridge.civ_edit_settlement(_index, fields):
		app.set_status("hint", "Edit refused — a value was outside the engine's own vocabulary.", "accent")
		_rebuild()
		return
	place_changed.emit()
