//! GENERATED by the milestone-12 golden capture -- do not hand-edit.
//!
//! Every value below is the reference engine's own output. Neither
//! `buildBlocks` nor `buildParcels` is on `UME`'s public export or its
//! `_test` one, so the capture adds them (with `buildSite`, `makeGraph`,
//! `addStreet` and `placeAnchors`, which the fixtures need) by a single
//! anchored replacement of the `return {` line, asserted to match exactly
//! once. The frozen reference file itself is untouched, and both slice
//! boundaries are asserted -- start, end, and block-comment balance.
//!
//! The fixture grid is deliberately **not** axis-aligned: every interior node
//! is pushed off the lattice by a fixed jitter table, so the vertex-bisector
//! ray-cast caps and the per-edge depth clamps take different values per
//! vertex instead of collapsing to one symmetric case. Three site kinds are
//! captured so the wet-parcel rejection is exercised (`river` uses the
//! `riverW/2 + 1` margin, the other two the flat 3 m one).
//!
//! `narrow_rows` exists because a mutation survived without it. On the wide
//! grid every block is far deeper than the 14-46 m plot depth, so
//! `min(t_min*0.42, depthTarget*1.35)` is always won by the depth term and
//! the ray-cast caps never bind -- lengthening the 2000 m probe ray changed
//! nothing. Its rows are ~30 m deep, where `0.42*t_min` lands *under* the
//! depth target and the cap is what decides the lot.
//!
//! The capture asserts each scenario produced a non-empty block AND parcel
//! list before writing -- a silently-empty golden is this project's
//! most-repeated failure.

#![allow(
    clippy::approx_constant,
    clippy::unreadable_literal,
    clippy::excessive_precision
)]

pub struct BlockGolden {
    pub id: &'static str,
    pub poly: &'static [(f64, f64)],
    pub area: f64,
    pub plaza: bool,
}

pub struct ParcelGolden {
    pub id: &'static str,
    pub poly: &'static [(f64, f64)],
    pub block: &'static str,
    pub frontage: f64,
    pub depth: f64,
    pub area: f64,
    pub age: f64,
    pub edge_cls: &'static str,
}

pub struct Scenario {
    pub name: &'static str,
    pub seed: u32,
    pub kind: &'static str,
    pub market: (f64, f64),
    pub block_count: usize,
    pub parcel_count: usize,
    /// The reference's OWN `fnv1a` over its own canonical dump of **every**
    /// block and parcel -- id, area, plaza flag, both polygons, the face ids
    /// and edge distances, then every parcel's id, block, frontage, depth,
    /// area, age, class and quad -- with each double written as its exact 64
    /// bits. `blocks`/`parcels` below carry only the first few in full, as a
    /// readable anchor; this is what actually covers the rest.
    pub hash: u32,
    pub blocks: &'static [BlockGolden],
    pub parcels: &'static [ParcelGolden],
}

static BLOCKS_PLAIN_GRID: &[BlockGolden] = &[
    BlockGolden {
        id: "blk0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (519.01418689648608, 284.89999999999998),
            (515.97995492502639, 460.41864942598158),
            (303.89999999999998, 455.19383530688799),
        ],
        area: 36936.230236167044,
        plaza: false,
    },
    BlockGolden {
        id: "blk1",
        poly: &[
            (533.81639820989676, 284.89999999999998),
            (752.26329534759657, 284.89999999999998),
            (766.95063296687567, 452.98841942063939),
            (530.78315902188274, 460.36122072204398),
        ],
        area: 39067.131735308038,
        plaza: false,
    },
    BlockGolden {
        id: "blk2",
        poly: &[
            (760.09301533201517, 284.89999999999998),
            (1015.0336979304916, 284.89999999999998),
            (1012.7004161160359, 458.26283881406323),
            (774.77451830976827, 452.92164518984089),
        ],
        area: 42047.762248523606,
        plaza: false,
    },
    BlockGolden {
        id: "blk3",
        poly: &[
            (1022.8344043575299, 284.89999999999998),
            (1236.0999999999999, 284.89999999999998),
            (1236.0999999999999, 471.35579930843596),
            (1020.4969351498513, 458.57396213051885),
        ],
        area: 38619.561385667883,
        plaza: false,
    },
];

static PARCELS_PLAIN_GRID: &[ParcelGolden] = &[
    ParcelGolden {
        id: "par0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (312.33159107856193, 284.89999999999998),
            (336.56009621263217, 311.19005339735685),
            (330.19900084781563, 311.19900084781563),
        ],
        block: "blk0",
        frontage: 8.4315910785619508,
        depth: 36.472075024059166,
        area: 194.59637053980987,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par1",
        poly: &[
            (312.33159107856193, 284.89999999999998),
            (316.61566078985044, 284.89999999999998),
            (339.79215238436910, 311.18550722082313),
            (336.56009621263217, 311.19005339735685),
        ],
        block: "blk0",
        frontage: 4.2840697112885096,
        depth: 35.397842628003929,
        area: 98.845010865145014,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par2",
        poly: &[
            (316.61566078985044, 284.89999999999998),
            (319.55013737232781, 284.89999999999998),
            (342.00602699154979, 311.18239320786881),
            (339.79215238436910, 311.18550722082313),
        ],
        block: "blk0",
        frontage: 2.9344765824773731,
        depth: 34.806580887626851,
        area: 67.695028134032327,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par3",
        poly: &[
            (319.55013737232781, 284.89999999999998),
            (322.43224213960355, 284.89999999999998),
            (344.18039041895167, 311.17933477092828),
            (342.00602699154979, 311.18239320786881),
        ],
        block: "blk0",
        frontage: 2.8821047672757345,
        depth: 34.340295172769842,
        area: 66.477975261128449,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
];

static BLOCKS_RIVER_GRID: &[BlockGolden] = &[
    BlockGolden {
        id: "blk0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (519.01418689648608, 284.89999999999998),
            (515.97995492502639, 460.41864942598158),
            (303.89999999999998, 455.19383530688799),
        ],
        area: 36936.230236167044,
        plaza: false,
    },
    BlockGolden {
        id: "blk1",
        poly: &[
            (533.81639820989676, 284.89999999999998),
            (752.26329534759657, 284.89999999999998),
            (766.95063296687567, 452.98841942063939),
            (530.78315902188274, 460.36122072204398),
        ],
        area: 39067.131735308038,
        plaza: false,
    },
    BlockGolden {
        id: "blk2",
        poly: &[
            (760.09301533201517, 284.89999999999998),
            (1015.0336979304916, 284.89999999999998),
            (1012.7004161160359, 458.26283881406323),
            (774.77451830976827, 452.92164518984089),
        ],
        area: 42047.762248523606,
        plaza: false,
    },
    BlockGolden {
        id: "blk3",
        poly: &[
            (1022.8344043575299, 284.89999999999998),
            (1236.0999999999999, 284.89999999999998),
            (1236.0999999999999, 471.35579930843596),
            (1020.4969351498513, 458.57396213051885),
        ],
        area: 38619.561385667883,
        plaza: false,
    },
];

static PARCELS_RIVER_GRID: &[ParcelGolden] = &[
    ParcelGolden {
        id: "par0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (312.33159107856193, 284.89999999999998),
            (336.56009621263217, 311.19005339735685),
            (330.19900084781563, 311.19900084781563),
        ],
        block: "blk0",
        frontage: 8.4315910785619508,
        depth: 36.472075024059166,
        area: 194.59637053980987,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par1",
        poly: &[
            (312.33159107856193, 284.89999999999998),
            (316.61566078985044, 284.89999999999998),
            (339.79215238436910, 311.18550722082313),
            (336.56009621263217, 311.19005339735685),
        ],
        block: "blk0",
        frontage: 4.2840697112885096,
        depth: 35.397842628003929,
        area: 98.845010865145014,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par2",
        poly: &[
            (316.61566078985044, 284.89999999999998),
            (319.55013737232781, 284.89999999999998),
            (342.00602699154979, 311.18239320786881),
            (339.79215238436910, 311.18550722082313),
        ],
        block: "blk0",
        frontage: 2.9344765824773731,
        depth: 34.806580887626851,
        area: 67.695028134032327,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par3",
        poly: &[
            (319.55013737232781, 284.89999999999998),
            (322.43224213960355, 284.89999999999998),
            (344.18039041895167, 311.17933477092828),
            (342.00602699154979, 311.18239320786881),
        ],
        block: "blk0",
        frontage: 2.8821047672757345,
        depth: 34.340295172769842,
        area: 66.477975261128449,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
];

static BLOCKS_COAST_GRID: &[BlockGolden] = &[
    BlockGolden {
        id: "blk0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (519.01418689648608, 284.89999999999998),
            (515.97995492502639, 460.41864942598158),
            (303.89999999999998, 455.19383530688799),
        ],
        area: 36936.230236167044,
        plaza: false,
    },
    BlockGolden {
        id: "blk1",
        poly: &[
            (533.81639820989676, 284.89999999999998),
            (752.26329534759657, 284.89999999999998),
            (766.95063296687567, 452.98841942063939),
            (530.78315902188274, 460.36122072204398),
        ],
        area: 39067.131735308038,
        plaza: false,
    },
    BlockGolden {
        id: "blk2",
        poly: &[
            (760.09301533201517, 284.89999999999998),
            (1015.0336979304916, 284.89999999999998),
            (1012.7004161160359, 458.26283881406323),
            (774.77451830976827, 452.92164518984089),
        ],
        area: 42047.762248523606,
        plaza: false,
    },
    BlockGolden {
        id: "blk3",
        poly: &[
            (1022.8344043575299, 284.89999999999998),
            (1236.0999999999999, 284.89999999999998),
            (1236.0999999999999, 471.35579930843596),
            (1020.4969351498513, 458.57396213051885),
        ],
        area: 38619.561385667883,
        plaza: false,
    },
];

static PARCELS_COAST_GRID: &[ParcelGolden] = &[
    ParcelGolden {
        id: "par0",
        poly: &[
            (303.89999999999998, 284.89999999999998),
            (312.33159107856193, 284.89999999999998),
            (336.56009621263217, 311.19005339735685),
            (330.19900084781563, 311.19900084781563),
        ],
        block: "blk0",
        frontage: 8.4315910785619508,
        depth: 36.472075024059166,
        area: 194.59637053980987,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par1",
        poly: &[
            (312.33159107856193, 284.89999999999998),
            (316.61566078985044, 284.89999999999998),
            (339.79215238436910, 311.18550722082313),
            (336.56009621263217, 311.19005339735685),
        ],
        block: "blk0",
        frontage: 4.2840697112885096,
        depth: 35.397842628003929,
        area: 98.845010865145014,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par2",
        poly: &[
            (316.61566078985044, 284.89999999999998),
            (319.55013737232781, 284.89999999999998),
            (342.00602699154979, 311.18239320786881),
            (339.79215238436910, 311.18550722082313),
        ],
        block: "blk0",
        frontage: 2.9344765824773731,
        depth: 34.806580887626851,
        area: 67.695028134032327,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par3",
        poly: &[
            (319.55013737232781, 284.89999999999998),
            (322.43224213960355, 284.89999999999998),
            (344.18039041895167, 311.17933477092828),
            (342.00602699154979, 311.18239320786881),
        ],
        block: "blk0",
        frontage: 2.8821047672757345,
        depth: 34.340295172769842,
        area: 66.477975261128449,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
];

static BLOCKS_NARROW_ROWS: &[BlockGolden] = &[
    BlockGolden {
        id: "blk0",
        poly: &[
            (303.89999999999998, 304.89999999999998),
            (558.52586971945004, 304.89999999999998),
            (556.62354281998307, 322.45994061046412),
            (303.89999999999998, 317.17986659143315),
        ],
        area: 3787.3132702525472,
        plaza: false,
    },
    BlockGolden {
        id: "blk1",
        poly: &[
            (573.41246361388335, 304.89999999999998),
            (824.44032608208704, 304.89999999999998),
            (831.67525694183212, 315.12077534154474),
            (571.52022885245151, 322.36678241321664),
        ],
        area: 3548.0297548172966,
        plaza: false,
    },
    BlockGolden {
        id: "blk2",
        poly: &[
            (833.99675256959836, 304.89999999999998),
            (1094.6427639045839, 304.89999999999998),
            (1093.2573279627850, 320.27833895396873),
            (841.03164197702029, 314.83817709937381),
        ],
        area: 3238.3476543207216,
        plaza: false,
    },
    BlockGolden {
        id: "blk3",
        poly: &[
            (1102.4743532125333, 304.89999999999998),
            (1336.0999999999999, 304.89999999999998),
            (1336.0999999999999, 333.37683485424952),
            (1101.0610880650511, 320.58724313705005),
        ],
        area: 5179.0533018497808,
        plaza: false,
    },
];

static PARCELS_NARROW_ROWS: &[ParcelGolden] = &[
    ParcelGolden {
        id: "par0",
        poly: &[
            (303.89999999999998, 304.89999999999998),
            (312.41731603456685, 304.89999999999998),
            (316.54958451083257, 309.32866706197484),
            (308.33688709461529, 309.33688709461529),
        ],
        block: "blk0",
        frontage: 8.5173160345668748,
        depth: 6.1659142731898715,
        area: 37.097819756723766,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par1",
        poly: &[
            (326.52100745493874, 304.89999999999998),
            (334.77122872319779, 304.89999999999998),
            (338.10401788341090, 309.30709337711954),
            (330.14886268920804, 309.31505563751250),
        ],
        block: "blk0",
        frontage: 8.2502212682590539,
        depth: 5.6198820593874013,
        area: 35.755417113294243,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par2",
        poly: &[
            (334.77122872319779, 304.89999999999998),
            (340.87420069770826, 304.89999999999998),
            (343.98871935073839, 309.30120341969274),
            (338.10401788341090, 309.30709337711954),
        ],
        block: "blk0",
        frontage: 6.1029719745104671,
        depth: 5.4585639899248335,
        area: 26.407239986881905,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par3",
        poly: &[
            (340.87420069770826, 304.89999999999998),
            (350.64578581711129, 304.89999999999998),
            (353.41082738768046, 309.29177289623857),
            (343.98871935073839, 309.30120341969274),
        ],
        block: "blk0",
        frontage: 9.7715851194030279,
        depth: 5.2907246874557359,
        area: 42.206284167397826,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
];

static BLOCKS_WEDGES: &[BlockGolden] = &[
    BlockGolden {
        id: "blk0",
        poly: &[
            (310.60749577660613, 284.89999999999998),
            (514.99958153540570, 284.89999999999998),
            (407.65082128321592, 371.39513795154352),
        ],
        area: 8839.4608269555320,
        plaza: false,
    },
    BlockGolden {
        id: "blk1",
        poly: &[
            (533.81639820989676, 284.89999999999998),
            (745.06548901462941, 284.89999999999998),
            (546.96301224010790, 459.85610949368049),
            (530.78315902188274, 460.36122072204398),
        ],
        area: 19898.361867437183,
        plaza: false,
    },
    BlockGolden {
        id: "blk2",
        poly: &[
            (766.60929365942275, 284.89999999999998),
            (1015.0336979304916, 284.89999999999998),
            (1012.7004161160359, 458.26283881406323),
            (965.75148138940608, 457.20888313652665),
        ],
        area: 25473.695711462584,
        plaza: false,
    },
    BlockGolden {
        id: "blk3",
        poly: &[
            (1029.5227778416481, 284.89999999999998),
            (1236.0999999999999, 284.89999999999998),
            (1236.0999999999999, 470.91297379869684),
        ],
        area: 19213.021706374508,
        plaza: false,
    },
];

static PARCELS_WEDGES: &[ParcelGolden] = &[
    ParcelGolden {
        id: "par0",
        poly: &[
            (310.60749577660613, 284.89999999999998),
            (319.03769870423559, 284.89999999999998),
            (348.67785745896094, 297.17902367453246),
            (342.92583089432935, 297.21234136333675),
        ],
        block: "blk0",
        frontage: 8.4302029276294661,
        depth: 33.333569379555698,
        area: 87.706174078171898,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par1",
        poly: &[
            (319.03769870423559, 284.89999999999998),
            (323.32106309961051, 284.89999999999998),
            (351.60044734199261, 297.16209504266135),
            (348.67785745896094, 297.17902367453246),
        ],
        block: "blk0",
        frontage: 4.2833643953749174,
        depth: 31.453162033648727,
        area: 44.455669509647123,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par2",
        poly: &[
            (323.32106309961051, 284.89999999999998),
            (326.25505655898974, 284.89999999999998),
            (353.60234557192643, 297.15049936912033),
            (351.60044734199261, 297.16209504266135),
        ],
        block: "blk0",
        frontage: 2.9339934593792236,
        depth: 30.394602722447292,
        area: 30.409134945955884,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
    ParcelGolden {
        id: "par3",
        poly: &[
            (326.25505655898974, 284.89999999999998),
            (329.13668682550002, 284.89999999999998),
            (355.56851577977397, 297.13911064440128),
            (353.60234557192643, 297.15049936912033),
        ],
        block: "blk0",
        frontage: 2.8816302665102853,
        depth: 29.546872662471209,
        area: 29.833304652638617,
        age: 7.0000000000000000,
        edge_cls: "street",
    },
];

pub static SCENARIOS: &[Scenario] = &[
    Scenario {
        name: "plain_grid",
        seed: 20260824,
        kind: "plain",
        market: (1028.8985184448836, 802.04263882630732),
        block_count: 12,
        parcel_count: 1344,
        hash: 0x31f4ca26,
        blocks: BLOCKS_PLAIN_GRID,
        parcels: PARCELS_PLAIN_GRID,
    },
    Scenario {
        name: "river_grid",
        seed: 771013,
        kind: "river",
        market: (393.35776449342950, 741.94282052700453),
        block_count: 11,
        parcel_count: 1346,
        hash: 0x6ac6cff7,
        blocks: BLOCKS_RIVER_GRID,
        parcels: PARCELS_RIVER_GRID,
    },
    Scenario {
        name: "coast_grid",
        seed: 4242,
        kind: "coast",
        market: (930.17687477041545, 809.87856943310487),
        block_count: 12,
        parcel_count: 1347,
        hash: 0xeec50861,
        blocks: BLOCKS_COAST_GRID,
        parcels: PARCELS_COAST_GRID,
    },
    Scenario {
        name: "narrow_rows",
        seed: 90210,
        kind: "plain",
        market: (786.70864584306310, 858.36338944190982),
        block_count: 16,
        parcel_count: 999,
        hash: 0x14ae77d,
        blocks: BLOCKS_NARROW_ROWS,
        parcels: PARCELS_NARROW_ROWS,
    },
    Scenario {
        name: "wedges",
        seed: 31337,
        kind: "plain",
        market: (726.77396474742750, 792.42701022447625),
        block_count: 22,
        parcel_count: 1772,
        hash: 0x99382bc3,
        blocks: BLOCKS_WEDGES,
        parcels: PARCELS_WEDGES,
    },
];
